Failures in [node-test-pull-request/62554](https://ci.nodejs.org/job/node-test-pull-request/62554/) to [node-test-pull-request/62650](https://ci.nodejs.org/job/node-test-pull-request/62650/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2024-09-22.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2024-09-22 00:10 | 2       | 15      | 22       | 10      | 51      | 17.05%     |


### Jenkins Failure

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55024/](https://ci.nodejs.org/job/node-test-pull-request/62597/), [https://github.com/nodejs/node/pull/55019/](https://ci.nodejs.org/job/node-test-pull-request/62636/)) |
| Appeared | [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/46543/console), [test-digitalocean-ubi81_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/46510/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62597/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62636/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/46543/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------


### Build Failure

| Reason | <code>fatal: '/home/iojs/.ccache/node.shared.reference' does not appear to be a git repository</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/54999/](https://ci.nodejs.org/job/node-test-pull-request/62554/), [https://github.com/nodejs/node/pull/54971/](https://ci.nodejs.org/job/node-test-pull-request/62606/), [https://github.com/nodejs/node/pull/54500/](https://ci.nodejs.org/job/node-test-pull-request/62607/), [https://github.com/nodejs/node/pull/54680/](https://ci.nodejs.org/job/node-test-pull-request/62626/), [https://github.com/nodejs/node/pull/52685/](https://ci.nodejs.org/job/node-test-pull-request/62631/), [https://github.com/nodejs/node/pull/55019/](https://ci.nodejs.org/job/node-test-pull-request/62636/), [https://github.com/nodejs/node/pull/54596/](https://ci.nodejs.org/job/node-test-pull-request/62640/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/13799/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62554/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62640/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/13799/console">Example</a></summary>

```
fatal: '/home/iojs/.ccache/node.shared.reference' does not appear to be a git repository
fatal: Could not read from remote repository.
fatal: unable to create thread: Resource temporarily unavailable
fatal: failed to run repack
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/54993/](https://ci.nodejs.org/job/node-test-pull-request/62565/), [https://github.com/nodejs/node/pull/53763/](https://ci.nodejs.org/job/node-test-pull-request/62601/), [https://github.com/nodejs/node/pull/54971/](https://ci.nodejs.org/job/node-test-pull-request/62606/), [https://github.com/nodejs/node/pull/54500/](https://ci.nodejs.org/job/node-test-pull-request/62607/), [https://github.com/nodejs/node/pull/54911/](https://ci.nodejs.org/job/node-test-pull-request/62613/), [https://github.com/nodejs/node/pull/53978/](https://ci.nodejs.org/job/node-test-pull-request/62628/), [https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/62634/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/46541/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46538/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/56861/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46519/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46518/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/46484/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62565/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62634/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/46541/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>ERROR: Step �Publish JUnit test result report� failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/54999/](https://ci.nodejs.org/job/node-test-pull-request/62554/), [https://github.com/nodejs/node/pull/55006/](https://ci.nodejs.org/job/node-test-pull-request/62650/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-6](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2022-vs2022-COMPILED_BY-vs2022/24866/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022/30357/console), [test-azure_msft-win11_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022/30357/console), [test-rackspace-win2019_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2022/30357/console), [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022/30357/console), [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022/30357/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/30357/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/30357/console), [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2022-COMPILED_BY-vs2022/30357/console), [test-azure_msft-win10_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022/30357/console), [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/30357/console), [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022/30357/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62554/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62650/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2022-vs2022-COMPILED_BY-vs2022/24866/console">Example</a></summary>

```
ERROR: Step �Publish JUnit test result report� failed: No test report files were found. Configuration error?
Collecting metadata...
Metadata collection done.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>Failed to trigger sub builds</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/53763/](https://ci.nodejs.org/job/node-test-pull-request/62599/), [https://github.com/nodejs/node/pull/53381/](https://ci.nodejs.org/job/node-test-pull-request/62633/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit/74662/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62599/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62633/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit/74662/console">Example</a></summary>

```
Failed to trigger sub builds
```
</details>

-------

| Reason | <code>fatal error: Killed signal terminated program cc1plus</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55015/](https://ci.nodejs.org/job/node-test-pull-request/62569/), [https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/62570/)) |
| Appeared | [test-digitalocean-alpine319_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/60733/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/46484/console), [test-digitalocean-rhel9_arm_cross_container-x64-2](https://ci.nodejs.org/job/node-cross-compile/nodes=cross-compiler-rhel9-armv7-gcc-12-glibc-2.28/50013/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62569/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62570/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/60733/console">Example</a></summary>

```
fatal error: Killed signal terminated program cc1plus
```
</details>

-------


### JSTest Failure

| Reason | <code>node-api/test_threadsafe_function/test</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/54999/](https://ci.nodejs.org/job/node-test-pull-request/62555/), [https://github.com/nodejs/node/pull/54993/](https://ci.nodejs.org/job/node-test-pull-request/62558/), [https://github.com/nodejs/node/pull/54545/](https://ci.nodejs.org/job/node-test-pull-request/62560/), [https://github.com/nodejs/node/pull/54596/](https://ci.nodejs.org/job/node-test-pull-request/62578/), [https://github.com/nodejs/node/pull/55019/](https://ci.nodejs.org/job/node-test-pull-request/62580/), [https://github.com/nodejs/node/pull/54750/](https://ci.nodejs.org/job/node-test-pull-request/62602/), [https://github.com/nodejs/node/pull/54911/](https://ci.nodejs.org/job/node-test-pull-request/62612/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/13778/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62555/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62612/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/13778/console">Example</a></summary>

```
not ok 144 node-api/test_threadsafe_function/test
  ---
  duration_ms: 360016.38900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>es-module/test-loaders-workers-spawned</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/54993/](https://ci.nodejs.org/job/node-test-pull-request/62558/), [https://github.com/nodejs/node/pull/54545/](https://ci.nodejs.org/job/node-test-pull-request/62560/), [https://github.com/nodejs/node/pull/52627/](https://ci.nodejs.org/job/node-test-pull-request/62564/), [https://github.com/nodejs/node/pull/54957/](https://ci.nodejs.org/job/node-test-pull-request/62568/), [https://github.com/nodejs/node/pull/53937/](https://ci.nodejs.org/job/node-test-pull-request/62583/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/46497/console), [test-ibm-alpine319_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/60731/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/46475/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/46472/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62558/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62583/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/46497/console">Example</a></summary>

```
not ok 234 es-module/test-loaders-workers-spawned
  ---
  duration_ms: 1251.73400
  severity: fail
  exitcode: 1
  stack: |-
    ▶ Worker threads do not spawn infinitely
      ✔ should not trigger an infinite loop when using a loader exports no recognized hooks (242.535831ms)
      ✔ should support a CommonJS entry point and a loader that imports a CommonJS module (229.805184ms)
      ✔ should support --require and --import along with using a loader written in CJS and CJS entry point (218.849314ms)
      ✖ should support --require and --import along with using a loader written in ESM and ESM entry point (243.226052ms)
        AssertionError [ERR_ASSERTION]: The input did not match the regular expression /^A\r?\nA\r?\n(B\r?\nC|C\r?\nB)\r?\nD\r?\n$/. Input:
        
        'A\nC\nA\nB\nD\n'
        
            at TestContext.<anonymous> (file:///home/iojs/build/workspace/node-test-commit-linux-containered/test/es-module/test-loaders-workers-spawned.mjs:79:12)
            at process.processTicksAndRejections (...
```
</details>

-------

| Reason | <code>parallel/test-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/55016/](https://ci.nodejs.org/job/node-test-pull-request/62574/), [https://github.com/nodejs/node/pull/54997/](https://ci.nodejs.org/job/node-test-pull-request/62575/), [https://github.com/nodejs/node/pull/55004/](https://ci.nodejs.org/job/node-test-pull-request/62576/), [https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/62634/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46541/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46490/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46489/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62574/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62634/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46541/console">Example</a></summary>

```
not ok 262 parallel/test-async-context-frame
  ---
  duration_ms: 120061.63500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    ▶ AsyncContextFrame
      ✔ async-hooks/test-async-local-storage-async-functions.js (4552.312568ms)
      ✔ async-hooks/test-async-local-storage-args.js (4527.615928ms)
      ✔ async-hooks/test-async-local-storage-dgram.js (4591.141232ms)
      ✔ async-hooks/test-async-local-storage-socket.js (4407.786192ms)
      ✔ async-hooks/test-async-local-storage-tlssocket.js (5651.807164ms)
      ✔ async-hooks/test-async-local-storage-promises.js (5123.522008ms)
      ✔ async-hooks/test-async-local-storage-errors.js (5811.758657ms)
      ✔ async-hooks/test-async-local-storage-thenable.js (5590.998519ms)
      ✔ async-hooks/test-async-local-storage-enable-disable.js (5304.192653ms)
      ✔ async-hooks/test-async-local-storage-http.js (5668.59418ms)
      ✔ async-hooks/test-async-local-storage-enter-with.js (6493.76411ms)
      ✔ async-hooks/test-async-local-storage-misc-stores.js (5...
```
</details>

-------

| Reason | <code>parallel/test-http2-large-write-multiple-requests</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/54993/](https://ci.nodejs.org/job/node-test-pull-request/62558/), [https://github.com/nodejs/node/pull/54997/](https://ci.nodejs.org/job/node-test-pull-request/62575/), [https://github.com/nodejs/node/pull/54500/](https://ci.nodejs.org/job/node-test-pull-request/62614/), [https://github.com/nodejs/node/pull/53757/](https://ci.nodejs.org/job/node-test-pull-request/62632/)) |
| Appeared | [test-digitalocean-fedora40-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/60782/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/46525/console), [test-ibm-rhel8-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/60736/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/46472/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62558/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62632/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/60782/console">Example</a></summary>

```
not ok 2215 parallel/test-http2-large-write-multiple-requests
  ---
  duration_ms: 120107.18700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    server sends content 1
    server sends content 2
    server sends content 3
    server sends content 4
    server sends content 5
    server sends content 6
    server sends content 7
    server sends content 8
    server sends content 9
    server sends content 10
    server sends content 11
    server sends content 12
    server sends content 13
    server sends content 14
    server sends content 15
    server sends content 16
    server sends content 17
    server sends content 18
    server sends content 19
    server sends content 20
    server sends content 21
    server sends content 22
    server sends content 23
    server sends content 24
    server sends content 25
    server sends content 26
    server sends content 27
    server sends content 28
    server sends content 29
    server sends content 30
    server sends content 31
    server s...
```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/55024/](https://ci.nodejs.org/job/node-test-pull-request/62597/), [https://github.com/nodejs/node/pull/55037/](https://ci.nodejs.org/job/node-test-pull-request/62649/), [https://github.com/nodejs/node/pull/55006/](https://ci.nodejs.org/job/node-test-pull-request/62650/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/54985/console), [test-rackspace-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/60794/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/38506/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62597/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62650/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/54985/console">Example</a></summary>

```
not ok 4001 parallel/test-file-write-stream4
  ---
  duration_ms: 360021.76500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-remove-header-stays-removed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54892/](https://ci.nodejs.org/job/node-test-pull-request/62579/), [https://github.com/nodejs/node/pull/54896/](https://ci.nodejs.org/job/node-test-pull-request/62635/), [https://github.com/nodejs/node/pull/54957/](https://ci.nodejs.org/job/node-test-pull-request/62638/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/46545/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46542/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/46492/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62579/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62638/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/46545/console">Example</a></summary>

```
not ok 1355 parallel/test-http-remove-header-stays-removed
  ---
  duration_ms: 435.61900
  severity: fail
  exitcode: 1
  stack: |-
    ok
    node:assert:90
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    false !== true
    
        at Timeout._onTimeout (/home/iojs/build/workspace/node-test-commit-linux-containered/test/parallel/test-http-remove-header-stays-removed.js:61:18)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: 'strictEqual'
    }
    
    Node.js v23.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/55004/](https://ci.nodejs.org/job/node-test-pull-request/62576/), [https://github.com/nodejs/node/pull/55038/](https://ci.nodejs.org/job/node-test-pull-request/62616/), [https://github.com/nodejs/node/pull/54911/](https://ci.nodejs.org/job/node-test-pull-request/62624/)) |
| Appeared | [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/54973/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/46526/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62576/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62624/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/54973/console">Example</a></summary>

```
not ok 4072 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 360089.58400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-complex</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54957/](https://ci.nodejs.org/job/node-test-pull-request/62568/), [https://github.com/nodejs/node/pull/54997/](https://ci.nodejs.org/job/node-test-pull-request/62575/), [https://github.com/nodejs/node/pull/53937/](https://ci.nodejs.org/job/node-test-pull-request/62586/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46500/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46489/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46482/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62568/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62586/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46500/console">Example</a></summary>

```
not ok 2483 parallel/test-runner-watch-mode-complex
  ---
  duration_ms: 5635.32500
  severity: fail
  exitcode: 1
  stack: |-
    ▶ test runner watch mode with more complex setup
      ✖ should run tests when a dependency changed after a watched test file being deleted (4697.267293ms)
        AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 2/. Input:
        
        '✔ second test has ran (7.971891ms)\n' +
          '✔ first test has ran (8.178247ms)\n' +
          '✔ first test has ran (3.892934ms)\n' +
          'ℹ tests 3\n' +
          'ℹ suites 0\n' +
          'ℹ pass 3\n' +
          'ℹ fail 0\n' +
          'ℹ cancelled 0\n' +
          'ℹ skipped 0\n' +
          'ℹ todo 0\n' +
          'ℹ duration_ms 1232.278633\n'
        
            at TestContext.<anonymous> (file:///home/iojs/build/workspace/node-test-commit-linux-containered/test/parallel/test-runner-watch-mode-complex.mjs:99:12)
            at process.processTicksAndRejections (node:internal/process/ta...
```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-rangeerror</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55004/](https://ci.nodejs.org/job/node-test-pull-request/62566/), [https://github.com/nodejs/node/pull/54432/](https://ci.nodejs.org/job/node-test-pull-request/62630/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/60780/console), [test-ibm-rhel8-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/60729/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62566/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62630/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/60780/console">Example</a></summary>

```
not ok 808 parallel/test-buffer-tostring-rangeerror
  ---
  duration_ms: 120090.67800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    (node:1812181) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-unpipe-resume</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55024/](https://ci.nodejs.org/job/node-test-pull-request/62597/), [https://github.com/nodejs/node/pull/55038/](https://ci.nodejs.org/job/node-test-pull-request/62616/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/54962/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/46510/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62597/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62616/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/54962/console">Example</a></summary>

```
not ok 4096 parallel/test-stream-readable-unpipe-resume
  ---
  duration_ms: 360109.68900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

