Failures in [node-test-pull-request/64146](https://ci.nodejs.org/job/node-test-pull-request/64146/) to [node-test-pull-request/64243](https://ci.nodejs.org/job/node-test-pull-request/64243/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2024-12-29.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2024-12-29 00:11 | 1       | 10      | 21       | 0       | 68      | 10.10%     |


### Jenkins Failure


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56231/](https://ci.nodejs.org/job/node-test-pull-request/64166/), [https://github.com/nodejs/node/pull/56147/](https://ci.nodejs.org/job/node-test-pull-request/64224/)) |
| Appeared | [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/62298/console), [test-ibm-ubuntu2204-x64-3](https://ci.nodejs.org/job/node-test-commit-linux/62244/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64166/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64224/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/62298/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:997)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1239)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1310)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1277)
```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56344/](https://ci.nodejs.org/job/node-test-pull-request/64191/), [https://github.com/nodejs/node/pull/56365/](https://ci.nodejs.org/job/node-test-pull-request/64207/), [https://github.com/nodejs/node/pull/56358/](https://ci.nodejs.org/job/node-test-pull-request/64230/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48107/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48086/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48069/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64191/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64230/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48107/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56325/](https://ci.nodejs.org/job/node-test-pull-request/64149/), [https://github.com/nodejs/node/pull/56237/](https://ci.nodejs.org/job/node-test-pull-request/64167/)) |
| Appeared | [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15131/console), [test-mnx-smartos22-x64-1](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/58280/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64149/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64167/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15131/console">Example</a></summary>

```
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
[PostBuildScript] - [INFO] Executing post build scripts.
[node-test-binary-armv7l] $ /bin/bash -ex /tmp/jenkins13760763845883183201.sh
+ '[' -d .git ']'
+ git clean -fdx
Removing out/
```
</details>

-------

| Reason | <code>Failed to trigger sub builds</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56231/](https://ci.nodejs.org/job/node-test-pull-request/64161/), [https://github.com/nodejs/node/pull/56287/](https://ci.nodejs.org/job/node-test-pull-request/64243/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit/76687/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64161/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64243/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit/76687/console">Example</a></summary>

```
Failed to trigger sub builds
```
</details>

-------


### JSTest Failure

| Reason | <code>sequential/test-http-server-request-timeouts-mixed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 15 ([https://github.com/nodejs/node/pull/56211/](https://ci.nodejs.org/job/node-test-pull-request/64146/), [https://github.com/nodejs/node/pull/56332/](https://ci.nodejs.org/job/node-test-pull-request/64151/), [https://github.com/nodejs/node/pull/56231/](https://ci.nodejs.org/job/node-test-pull-request/64166/), [https://github.com/nodejs/node/pull/56237/](https://ci.nodejs.org/job/node-test-pull-request/64168/), [https://github.com/nodejs/node/pull/50482/](https://ci.nodejs.org/job/node-test-pull-request/64180/), [https://github.com/nodejs/node/pull/56302/](https://ci.nodejs.org/job/node-test-pull-request/64184/), [https://github.com/nodejs/node/pull/56349/](https://ci.nodejs.org/job/node-test-pull-request/64190/), [https://github.com/nodejs/node/pull/56240/](https://ci.nodejs.org/job/node-test-pull-request/64198/), [https://github.com/nodejs/node/pull/56352/](https://ci.nodejs.org/job/node-test-pull-request/64199/), [https://github.com/nodejs/node/pull/56160/](https://ci.nodejs.org/job/node-test-pull-request/64210/), [https://github.com/nodejs/node/pull/56350/](https://ci.nodejs.org/job/node-test-pull-request/64217/), [https://github.com/nodejs/node/pull/56364/](https://ci.nodejs.org/job/node-test-pull-request/64218/), [https://github.com/nodejs/node/pull/56147/](https://ci.nodejs.org/job/node-test-pull-request/64228/), [https://github.com/nodejs/node/pull/56358/](https://ci.nodejs.org/job/node-test-pull-request/64230/), [https://github.com/nodejs/node/pull/56328/](https://ci.nodejs.org/job/node-test-pull-request/64239/)) |
| Appeared | [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/18300/console), [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62769/console), [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62718/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64146/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64239/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/18300/console">Example</a></summary>

```
not ok 4279 sequential/test-http-server-request-timeouts-mixed
  ---
  duration_ms: 3116.11700
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(request2.completed)
    
        at Timeout._onTimeout (/Users/iojs/build/workspace/node-test-commit-osx-arm/nodes/osx11/test/sequential/test-http-server-request-timeouts-mixed.js:108:5)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>es-module/test-wasm-web-api</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/56237/](https://ci.nodejs.org/job/node-test-pull-request/64148/), [https://github.com/nodejs/node/pull/56231/](https://ci.nodejs.org/job/node-test-pull-request/64165/), [https://github.com/nodejs/node/pull/56364/](https://ci.nodejs.org/job/node-test-pull-request/64208/), [https://github.com/nodejs/node/pull/56160/](https://ci.nodejs.org/job/node-test-pull-request/64210/), [https://github.com/nodejs/node/pull/56335/](https://ci.nodejs.org/job/node-test-pull-request/64225/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48103/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48089/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48087/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48044/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48027/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64148/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64225/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48103/console">Example</a></summary>

```
not ok 3827 es-module/test-wasm-web-api
  ---
  duration_ms: 608.24100
  severity: crashed
  exitcode: -11
  stack: |-
    (node:2236889) Warning: Closing file descriptor 27 on garbage collection
    (Use `node --trace-warnings ...` to show where the warning was created)
    (node:2236889) [DEP0137] DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. Please close FileHandle objects explicitly using FileHandle.prototype.close(). In the future, an error will be thrown if a file descriptor is closed during garbage collection.
  ...

```
</details>

-------

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/56325/](https://ci.nodejs.org/job/node-test-pull-request/64149/), [https://github.com/nodejs/node/pull/56341/](https://ci.nodejs.org/job/node-test-pull-request/64187/), [https://github.com/nodejs/node/pull/56349/](https://ci.nodejs.org/job/node-test-pull-request/64190/), [https://github.com/nodejs/node/pull/56358/](https://ci.nodejs.org/job/node-test-pull-request/64233/), [https://github.com/nodejs/node/pull/56372/](https://ci.nodejs.org/job/node-test-pull-request/64240/)) |
| Appeared | [test-mnx-smartos22-x64-1](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/58371/console), [test-mnx-smartos23-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/58322/console), [test-mnx-smartos22-x64-2](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/58316/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64149/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64240/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/58371/console">Example</a></summary>

```
not ok 4333 sequential/test-worker-prof
  ---
  duration_ms: 1926.50300
  severity: fail
  exitcode: 1
  stack: |-
    [process 27233]: --- stderr ---
    
    [process 27233]: --- stdout ---
    files found in working directory before worker starts [ 'isolate-0x817f000-27233-v8.log' ]
    parent prof file: isolate-0x817f000-27233-v8.log
    parent posted 10745 messages
    files found in working directory before worker exits [ 'isolate-0x817f000-27233-v8.log', 'isolate-0x84df000-27233-v8.log' ]
    worker prof file: isolate-0x84df000-27233-v8.log
    
    [process 27233]: status = null, signal = SIGPROF
    /home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos22-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGPROF, expected null
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos22-x64/test/sequential/test-worker-prof.js:53:22)
 ...
```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56335/](https://ci.nodejs.org/job/node-test-pull-request/64177/), [https://github.com/nodejs/node/pull/56344/](https://ci.nodejs.org/job/node-test-pull-request/64185/), [https://github.com/nodejs/node/pull/56359/](https://ci.nodejs.org/job/node-test-pull-request/64206/), [https://github.com/nodejs/node/pull/56350/](https://ci.nodejs.org/job/node-test-pull-request/64217/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/56388/console), [test-rackspace-win2019_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2022/31821/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/48061/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/56358/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64177/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64217/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/56388/console">Example</a></summary>

```
not ok 4058 parallel/test-file-write-stream4
  ---
  duration_ms: 360076.77800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-watch-file-shared-dependency</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56332/](https://ci.nodejs.org/job/node-test-pull-request/64151/), [https://github.com/nodejs/node/pull/56237/](https://ci.nodejs.org/job/node-test-pull-request/64167/), [https://github.com/nodejs/node/pull/56349/](https://ci.nodejs.org/job/node-test-pull-request/64188/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62743/console), [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62724/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64151/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64188/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62743/console">Example</a></summary>

```
not ok 3951 parallel/test-watch-file-shared-dependency
  ---
  duration_ms: 120073.10800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    ▶ watch file with shared dependency
      ✔ should not remove shared dependencies when unfiltering an owner (16.197949ms)
    ✔ watch file with shared dependency (19.853204ms)
  ...

```
</details>

-------

| Reason | <code>parallel/test-abortsignal-drop-settled-signals</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56334/](https://ci.nodejs.org/job/node-test-pull-request/64150/), [https://github.com/nodejs/node/pull/56329/](https://ci.nodejs.org/job/node-test-pull-request/64226/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/39977/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64150/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64226/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/39977/console">Example</a></summary>

```
not ok 375 parallel/test-abortsignal-drop-settled-signals
  ---
  duration_ms: 2015.02400
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: when there is a long-lived signal
        # Subtest: drops settled dependant signals
        ok 1 - drops settled dependant signals
          ---
          duration_ms: 453.707305
          ...

```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-rangeerror</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56341/](https://ci.nodejs.org/job/node-test-pull-request/64187/), [https://github.com/nodejs/node/pull/56335/](https://ci.nodejs.org/job/node-test-pull-request/64215/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/48093/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/48063/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64187/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64215/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/48093/console">Example</a></summary>

```
not ok 1293 parallel/test-buffer-tostring-rangeerror
  ---
  duration_ms: 120023.35600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    (node:3090402) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    (node:3090402) [DEP0030] DeprecationWarning: SlowBuffer() is deprecated. Please use Buffer.allocUnsafeSlow()
  ...

```
</details>

-------

| Reason | <code>parallel/test-fs-stat-bigint</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55811/](https://ci.nodejs.org/job/node-test-pull-request/64200/), [https://github.com/nodejs/node/pull/56147/](https://ci.nodejs.org/job/node-test-pull-request/64224/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/62298/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64200/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64224/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/62298/console">Example</a></summary>

```
not ok 1320 parallel/test-fs-stat-bigint
  ---
  duration_ms: 78.63100
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Number version atimeMs = 1735233442249.8384, BigInt version atimeMs = 1735233442249n, Allowable delta = 0
        at verifyStats (/home/iojs/build/workspace/node/test/parallel/test-fs-stat-bigint.js:70:7)
        at runSyncTest (/home/iojs/build/workspace/node/test/parallel/test-fs-stat-bigint.js:102:3)
        at Object.<anonymous> (/home/iojs/build/workspace/node/test/parallel/test-fs-stat-bigint.js:114:3)
        at Module._compile (node:internal/modules/cjs/loader:1739:14)
        at Object..js (node:internal/modules/cjs/loader:1904:10)
        at Module.load (node:internal/modules/cjs/loader:1473:32)
        at Function._load (node:internal/modules/cjs/loader:1285:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/...
```
</details>

-------

| Reason | <code>parallel/test-http-chunk-problem</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56106/](https://ci.nodejs.org/job/node-test-pull-request/64204/), [https://github.com/nodejs/node/pull/56364/](https://ci.nodejs.org/job/node-test-pull-request/64213/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48091/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64204/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64213/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48091/console">Example</a></summary>

```
not ok 1484 parallel/test-http-chunk-problem
  ---
  duration_ms: 120057.80000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56285/](https://ci.nodejs.org/job/node-test-pull-request/64189/), [https://github.com/nodejs/node/pull/56335/](https://ci.nodejs.org/job/node-test-pull-request/64197/)) |
| Appeared | [test-ibm-alpine319_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/62273/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/56368/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64189/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64197/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/62273/console">Example</a></summary>

```
not ok 3366 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 120047.41100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56349/](https://ci.nodejs.org/job/node-test-pull-request/64190/), [https://github.com/nodejs/node/pull/56352/](https://ci.nodejs.org/job/node-test-pull-request/64212/)) |
| Appeared | [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62766/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64190/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64212/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62766/console">Example</a></summary>

```
not ok 4307 sequential/test-perf-hooks
  ---
  duration_ms: 1514.98400
  severity: fail
  exitcode: 1
  stack: |-
    check initial nodeTiming
    {
      "name": "node",
      "entryType": "node",
      "startTime": 0,
      "duration": 56.800431,
      "nodeStart": 5.3349210023880005,
      "v8Start": 11.339950025081635,
      "environment": 21.466413021087646,
      "loopStart": -1,
      "loopExit": -1,
      "bootstrapComplete": 30.11537003517151,
      "idleTime": 0,
      "uvMetricsInfo": {
        "loopCount": 0,
        "events": 0,
        "eventsWaiting": 0
      }
    }
    Start timer
    Check nodeTiming in timer
    {
      "name": "node",
      "entryType": "node",
      "startTime": 0,
      "duration": 1191.988001,
      "nodeStart": 5.3349210023880005,
      "v8Start": 11.339950025081635,
      "environment": 21.466413021087646,
      "loopStart": 57.60866802930832,
      "loopExit": -1,
      "bootstrapComplete": 30.11537003517151,
      "idleTime": 1132.034109,
      "uvMetricsInfo": {
  ...
```
</details>

-------

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56237/](https://ci.nodejs.org/job/node-test-pull-request/64148/), [https://github.com/nodejs/node/pull/56335/](https://ci.nodejs.org/job/node-test-pull-request/64177/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48057/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48027/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64148/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64177/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48057/console">Example</a></summary>

```
not ok 4375 sequential/test-tls-session-timeout
  ---
  duration_ms: 135.53900
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:126
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at /home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:146:16
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:130:7)
        at ChildProcess.emit (node:events:507:28)
        at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual'
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

