Failures in [node-test-pull-request/62855](https://ci.nodejs.org/job/node-test-pull-request/62855/) to [node-test-pull-request/62952](https://ci.nodejs.org/job/node-test-pull-request/62952/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2024-10-07.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2024-10-07 00:10 | 3       | 16      | 19       | 3       | 59      | 17.02%     |


### JSTest Failure

| Reason | <code>es-module/test-loaders-workers-spawned</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/53848/](https://ci.nodejs.org/job/node-test-pull-request/62868/), [https://github.com/nodejs/node/pull/55184/](https://ci.nodejs.org/job/node-test-pull-request/62875/), [https://github.com/nodejs/node/pull/55255/](https://ci.nodejs.org/job/node-test-pull-request/62912/), [https://github.com/nodejs/node/pull/55262/](https://ci.nodejs.org/job/node-test-pull-request/62920/), [https://github.com/nodejs/node/pull/55274/](https://ci.nodejs.org/job/node-test-pull-request/62928/), [https://github.com/nodejs/node/pull/55276/](https://ci.nodejs.org/job/node-test-pull-request/62930/), [https://github.com/nodejs/node/pull/55231/](https://ci.nodejs.org/job/node-test-pull-request/62933/), [https://github.com/nodejs/node/pull/54721/](https://ci.nodejs.org/job/node-test-pull-request/62939/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/46819/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/46811/console), [test-ibm-alpine319_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/61049/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62868/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62939/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/46819/console">Example</a></summary>

```
not ok 3730 es-module/test-loaders-workers-spawned
  ---
  duration_ms: 1110.33100
  severity: fail
  exitcode: 1
  stack: |-
    ▶ Worker threads do not spawn infinitely
      ✔ should not trigger an infinite loop when using a loader exports no recognized hooks (209.088291ms)
      ✔ should support a CommonJS entry point and a loader that imports a CommonJS module (221.066185ms)
      ✔ should support --require and --import along with using a loader written in CJS and CJS entry point (230.866722ms)
      ✖ should support --require and --import along with using a loader written in ESM and ESM entry point (232.854478ms)
        AssertionError [ERR_ASSERTION]: The input did not match the regular expression /^A\r?\nA\r?\n(B\r?\nC|C\r?\nB)\r?\nD\r?\n$/. Input:
        
        'A\nC\nA\nB\nD\n'
        
            at TestContext.<anonymous> (file:///home/iojs/build/workspace/node-test-commit-linux-containered/test/es-module/test-loaders-workers-spawned.mjs:79:12)
            at process.processTicksAndRejections ...
```
</details>

-------

| Reason | <code>parallel/test-stream-readable-unpipe-resume</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/54929/](https://ci.nodejs.org/job/node-test-pull-request/62855/), [https://github.com/nodejs/node/pull/55206/](https://ci.nodejs.org/job/node-test-pull-request/62871/), [https://github.com/nodejs/node/pull/55071/](https://ci.nodejs.org/job/node-test-pull-request/62883/), [https://github.com/nodejs/node/pull/54295/](https://ci.nodejs.org/job/node-test-pull-request/62897/), [https://github.com/nodejs/node/pull/55234/](https://ci.nodejs.org/job/node-test-pull-request/62901/), [https://github.com/nodejs/node/pull/55202/](https://ci.nodejs.org/job/node-test-pull-request/62914/), [https://github.com/nodejs/node/pull/55241/](https://ci.nodejs.org/job/node-test-pull-request/62936/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/46813/console), [test-equinix_mnx-smartos20-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57187/console), [test-equinix_mnx-smartos20-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57182/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/55187/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/46774/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55171/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62855/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62936/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/46813/console">Example</a></summary>

```
not ok 3884 parallel/test-stream-readable-unpipe-resume
  ---
  duration_ms: 120082.73700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-http-server-request-timeouts-mixed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/55170/](https://ci.nodejs.org/job/node-test-pull-request/62889/), [https://github.com/nodejs/node/pull/53848/](https://ci.nodejs.org/job/node-test-pull-request/62890/), [https://github.com/nodejs/node/pull/55260/](https://ci.nodejs.org/job/node-test-pull-request/62916/), [https://github.com/nodejs/node/pull/55202/](https://ci.nodejs.org/job/node-test-pull-request/62921/), [https://github.com/nodejs/node/pull/55261/](https://ci.nodejs.org/job/node-test-pull-request/62929/), [https://github.com/nodejs/node/pull/54721/](https://ci.nodejs.org/job/node-test-pull-request/62939/), [https://github.com/nodejs/node/pull/55055/](https://ci.nodejs.org/job/node-test-pull-request/62947/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/61437/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17007/console), [test-macstadium-macos11.0-arm64-4](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/16997/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62889/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62947/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/61437/console">Example</a></summary>

```
not ok 4204 sequential/test-http-server-request-timeouts-mixed
  ---
  duration_ms: 3271.23300
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(request2.completed)
    
        at Timeout._onTimeout (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/sequential/test-http-server-request-timeouts-mixed.js:108:5)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v23.0.0-pre
  ...

```
</details>

-------

| Reason | <code>node-api/test_threadsafe_function/test</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/54563/](https://ci.nodejs.org/job/node-test-pull-request/62882/), [https://github.com/nodejs/node/pull/54679/](https://ci.nodejs.org/job/node-test-pull-request/62919/), [https://github.com/nodejs/node/pull/54777/](https://ci.nodejs.org/job/node-test-pull-request/62940/), [https://github.com/nodejs/node/pull/55228/](https://ci.nodejs.org/job/node-test-pull-request/62948/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/14046/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62882/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62948/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/14046/console">Example</a></summary>

```
not ok 144 node-api/test_threadsafe_function/test
  ---
  duration_ms: 360018.70700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/55114/](https://ci.nodejs.org/job/node-test-pull-request/62910/), [https://github.com/nodejs/node/pull/55255/](https://ci.nodejs.org/job/node-test-pull-request/62911/), [https://github.com/nodejs/node/pull/55228/](https://ci.nodejs.org/job/node-test-pull-request/62948/)) |
| Appeared | [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55229/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55196/console), [test-equinix_mnx-smartos20-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57179/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62910/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62948/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55229/console">Example</a></summary>

```
not ok 4102 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 360065.33100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>pummel/test-hash-seed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/55184/](https://ci.nodejs.org/job/node-test-pull-request/62875/), [https://github.com/nodejs/node/pull/53848/](https://ci.nodejs.org/job/node-test-pull-request/62888/), [https://github.com/nodejs/node/pull/54777/](https://ci.nodejs.org/job/node-test-pull-request/62940/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61060/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62875/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62940/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61060/console">Example</a></summary>

```
not ok 3891 pummel/test-hash-seed
  ---
  duration_ms: 68483.19100
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/errors:983
      const err = new Error(message);
                  ^
    
    Error: Command failed: /home/iojs/build/workspace/node/out/Release/node --allow-natives-syntax /home/iojs/build/workspace/node/test/fixtures/guess-hash-seed.js
    /home/iojs/build/workspace/node/test/fixtures/guess-hash-seed.js:163
      throw new Error('no candidates remaining');
      ^
    
    Error: no candidates remaining
        at Object.<anonymous> (/home/iojs/build/workspace/node/test/fixtures/guess-hash-seed.js:163:9)
        at Module._compile (node:internal/modules/cjs/loader:1560:14)
        at Object..js (node:internal/modules/cjs/loader:1703:10)
        at Module.load (node:internal/modules/cjs/loader:1328:32)
        at Function._load (node:internal/modules/cjs/loader:1138:12)
        at TracingChannel.traceSync (node:diagnostics_channel:315:14)
        at wrapModuleLoad (node:internal/mod...
```
</details>

-------

| Reason | <code>parallel/test-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55241/](https://ci.nodejs.org/job/node-test-pull-request/62917/), [https://github.com/nodejs/node/pull/54679/](https://ci.nodejs.org/job/node-test-pull-request/62919/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46796/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62917/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62919/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46796/console">Example</a></summary>

```
not ok 256 parallel/test-async-context-frame
  ---
  duration_ms: 120107.56000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    ▶ AsyncContextFrame
      ✔ async-hooks/test-async-local-storage-async-functions.js (5083.334483ms)
      ✔ async-hooks/test-async-local-storage-args.js (4658.472167ms)
      ✔ async-hooks/test-async-local-storage-dgram.js (4896.011231ms)
      ✔ async-hooks/test-async-local-storage-socket.js (4450.987905ms)
      ✔ async-hooks/test-async-local-storage-tlssocket.js (5507.551577ms)
      ✔ async-hooks/test-async-local-storage-promises.js (4961.701606ms)
      ✔ async-hooks/test-async-local-storage-errors.js (5213.700934ms)
      ✔ async-hooks/test-async-local-storage-thenable.js (5810.528121ms)
      ✔ async-hooks/test-async-local-storage-enable-disable.js (5153.761451ms)
      ✔ async-hooks/test-async-local-storage-http.js (4998.619165ms)
      ✔ async-hooks/test-async-local-storage-enter-with.js (6330.485864ms)
      ✔ async-hooks/test-async-local-storage-misc-stores.js ...
```
</details>

-------

| Reason | <code>parallel/test-performance-eventlooputil</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55170/](https://ci.nodejs.org/job/node-test-pull-request/62889/), [https://github.com/nodejs/node/pull/55241/](https://ci.nodejs.org/job/node-test-pull-request/62934/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61052/console), [test-ibm-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/61000/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62889/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62934/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61052/console">Example</a></summary>

```
not ok 2429 parallel/test-performance-eventlooputil
  ---
  duration_ms: 178.93400
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: 75.8161449432373 < 75.81614502539063
        at Timeout.runCalcTest (/home/iojs/build/workspace/node/test/parallel/test-performance-eventlooputil.js:85:10)
        at Timeout.runCalcTest [as _onTimeout] (/home/iojs/build/workspace/node/test/common/index.js:491:15)
        at listOnTimeout (node:internal/timers:616:11)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v23.0.0-pre
  ...

```
</details>

-------


### Jenkins Failure


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55231/](https://ci.nodejs.org/job/node-test-pull-request/62894/), [https://github.com/nodejs/node/pull/55241/](https://ci.nodejs.org/job/node-test-pull-request/62936/)) |
| Appeared | [test-digitalocean-fedora40-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/61053/console), [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/61008/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62894/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62936/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/61053/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:997)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1239)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1310)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1277)
```
</details>

-------


### Build Failure

| Reason | <code>Error: invalid syntax</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 11 ([https://github.com/nodejs/node/pull/55160/](https://ci.nodejs.org/job/node-test-pull-request/62872/), [https://github.com/nodejs/node/pull/55184/](https://ci.nodejs.org/job/node-test-pull-request/62875/), [https://github.com/nodejs/node/pull/53848/](https://ci.nodejs.org/job/node-test-pull-request/62888/), [https://github.com/nodejs/node/pull/55170/](https://ci.nodejs.org/job/node-test-pull-request/62891/), [https://github.com/nodejs/node/pull/55231/](https://ci.nodejs.org/job/node-test-pull-request/62894/), [https://github.com/nodejs/node/pull/55255/](https://ci.nodejs.org/job/node-test-pull-request/62912/), [https://github.com/nodejs/node/pull/55262/](https://ci.nodejs.org/job/node-test-pull-request/62920/), [https://github.com/nodejs/node/pull/55274/](https://ci.nodejs.org/job/node-test-pull-request/62928/), [https://github.com/nodejs/node/pull/55276/](https://ci.nodejs.org/job/node-test-pull-request/62930/), [https://github.com/nodejs/node/pull/55241/](https://ci.nodejs.org/job/node-test-pull-request/62936/), [https://github.com/nodejs/node/pull/54777/](https://ci.nodejs.org/job/node-test-pull-request/62940/)) |
| Appeared | [test-rackspace-debian10-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian10-x64/60964/console), [test-orka-macos10.15-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/61380/console), [test-orka-macos10.15-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/61376/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62872/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62940/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian10-x64/60964/console">Example</a></summary>

```
Error: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/home/iojs/build/workspace/node/deps/npm/node_modules/node-gyp/lib/configure.js:317:18)
gyp ERR! stack at ChildProcess.emit (node:events:519:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/55174/](https://ci.nodejs.org/job/node-test-pull-request/62860/), [https://github.com/nodejs/node/pull/55192/](https://ci.nodejs.org/job/node-test-pull-request/62879/), [https://github.com/nodejs/node/pull/55014/](https://ci.nodejs.org/job/node-test-pull-request/62895/), [https://github.com/nodejs/node/pull/55262/](https://ci.nodejs.org/job/node-test-pull-request/62920/), [https://github.com/nodejs/node/pull/55202/](https://ci.nodejs.org/job/node-test-pull-request/62921/), [https://github.com/nodejs/node/pull/55239/](https://ci.nodejs.org/job/node-test-pull-request/62952/)) |
| Appeared | [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/46827/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/57082/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46797/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/16969/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46760/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46741/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62860/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62952/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/46827/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>Failed to trigger sub builds</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/54295/](https://ci.nodejs.org/job/node-test-pull-request/62887/), [https://github.com/nodejs/node/pull/55241/](https://ci.nodejs.org/job/node-test-pull-request/62931/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit/75008/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62887/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62931/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit/75008/console">Example</a></summary>

```
Failed to trigger sub builds
```
</details>

-------

| Reason | <code>fatal error: Killed signal terminated program cc1plus</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55260/](https://ci.nodejs.org/job/node-test-pull-request/62916/), [https://github.com/nodejs/node/pull/55262/](https://ci.nodejs.org/job/node-test-pull-request/62918/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/46795/console), [test-digitalocean-rhel8_arm_cross_container-x64-1](https://ci.nodejs.org/job/node-cross-compile/nodes=cross-compiler-rhel8-armv7-gcc-10-glibc-2.28/50268/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62916/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62918/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/46795/console">Example</a></summary>

```
fatal error: Killed signal terminated program cc1plus
```
</details>

-------

