Failures in [node-test-pull-request/63732](https://ci.nodejs.org/job/node-test-pull-request/63732/) to [node-test-pull-request/63831](https://ci.nodejs.org/job/node-test-pull-request/63831/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2024-12-02.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2024-12-02 00:11 | 0       | 11      | 23       | 1       | 65      | 11.11%     |


### JSTest Failure

| Reason | <code>sequential/test-http-server-request-timeouts-mixed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 14 ([https://github.com/nodejs/node/pull/56041/](https://ci.nodejs.org/job/node-test-pull-request/63733/), [https://github.com/nodejs/node/pull/55996/](https://ci.nodejs.org/job/node-test-pull-request/63767/), [https://github.com/nodejs/node/pull/56072/](https://ci.nodejs.org/job/node-test-pull-request/63773/), [https://github.com/nodejs/node/pull/56074/](https://ci.nodejs.org/job/node-test-pull-request/63780/), [https://github.com/nodejs/node/pull/55896/](https://ci.nodejs.org/job/node-test-pull-request/63781/), [https://github.com/nodejs/node/pull/56071/](https://ci.nodejs.org/job/node-test-pull-request/63786/), [https://github.com/nodejs/node/pull/56082/](https://ci.nodejs.org/job/node-test-pull-request/63787/), [https://github.com/nodejs/node/pull/56086/](https://ci.nodejs.org/job/node-test-pull-request/63791/), [https://github.com/nodejs/node/pull/56084/](https://ci.nodejs.org/job/node-test-pull-request/63807/), [https://github.com/nodejs/node/pull/56079/](https://ci.nodejs.org/job/node-test-pull-request/63810/), [https://github.com/nodejs/node/pull/56088/](https://ci.nodejs.org/job/node-test-pull-request/63817/), [https://github.com/nodejs/node/pull/56075/](https://ci.nodejs.org/job/node-test-pull-request/63818/), [https://github.com/nodejs/node/pull/56093/](https://ci.nodejs.org/job/node-test-pull-request/63822/), [https://github.com/nodejs/node/pull/56095/](https://ci.nodejs.org/job/node-test-pull-request/63826/)) |
| Appeared | [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62345/console), [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62337/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17888/console), [test-macstadium-macos11.0-arm64-4](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17877/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63733/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63826/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62345/console">Example</a></summary>

```
not ok 4242 sequential/test-http-server-request-timeouts-mixed
  ---
  duration_ms: 3266.68700
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(request2.completed)
    
        at Timeout._onTimeout (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/sequential/test-http-server-request-timeouts-mixed.js:108:5)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/56053/](https://ci.nodejs.org/job/node-test-pull-request/63755/), [https://github.com/nodejs/node/pull/56078/](https://ci.nodejs.org/job/node-test-pull-request/63779/), [https://github.com/nodejs/node/pull/55096/](https://ci.nodejs.org/job/node-test-pull-request/63804/), [https://github.com/nodejs/node/pull/56062/](https://ci.nodejs.org/job/node-test-pull-request/63814/), [https://github.com/nodejs/node/pull/56095/](https://ci.nodejs.org/job/node-test-pull-request/63826/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61922/console), [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62342/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/39593/console), [test-rackspace-win2022_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022/31468/console), [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62270/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63755/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63826/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61922/console">Example</a></summary>

```
not ok 1560 parallel/test-file-write-stream4
  ---
  duration_ms: 120062.57500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-watch-file-shared-dependency</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/55051/](https://ci.nodejs.org/job/node-test-pull-request/63735/), [https://github.com/nodejs/node/pull/56050/](https://ci.nodejs.org/job/node-test-pull-request/63742/), [https://github.com/nodejs/node/pull/56053/](https://ci.nodejs.org/job/node-test-pull-request/63755/), [https://github.com/nodejs/node/pull/55896/](https://ci.nodejs.org/job/node-test-pull-request/63781/), [https://github.com/nodejs/node/pull/56095/](https://ci.nodejs.org/job/node-test-pull-request/63831/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62349/console), [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62345/console), [test-macstadium-macos11.0-arm64-4](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17849/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17803/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63735/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63831/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62349/console">Example</a></summary>

```
not ok 3919 parallel/test-watch-file-shared-dependency
  ---
  duration_ms: 120063.23900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    ▶ watch file with shared dependency
      ✔ should not remove shared dependencies when unfiltering an owner (13.371368ms)
    ✔ watch file with shared dependency (16.163107ms)
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/55905/](https://ci.nodejs.org/job/node-test-pull-request/63750/), [https://github.com/nodejs/node/pull/56084/](https://ci.nodejs.org/job/node-test-pull-request/63803/), [https://github.com/nodejs/node/pull/55896/](https://ci.nodejs.org/job/node-test-pull-request/63808/)) |
| Appeared | [test-equinix_mnx-smartos20-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57967/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/56016/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63750/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63808/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57967/console">Example</a></summary>

```
not ok 3920 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 300099.67500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-unpipe-resume</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56051/](https://ci.nodejs.org/job/node-test-pull-request/63738/), [https://github.com/nodejs/node/pull/55905/](https://ci.nodejs.org/job/node-test-pull-request/63750/), [https://github.com/nodejs/node/pull/55270/](https://ci.nodejs.org/job/node-test-pull-request/63758/)) |
| Appeared | [test-equinix_mnx-smartos20-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57930/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55977/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/55968/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63738/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63758/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57930/console">Example</a></summary>

```
not ok 3935 parallel/test-stream-readable-unpipe-resume
  ---
  duration_ms: 300085.15400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>wpt/test-compression</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/55718/](https://ci.nodejs.org/job/node-test-pull-request/63756/), [https://github.com/nodejs/node/pull/56062/](https://ci.nodejs.org/job/node-test-pull-request/63806/), [https://github.com/nodejs/node/pull/56092/](https://ci.nodejs.org/job/node-test-pull-request/63820/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47694/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47681/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/31447/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63756/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63820/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47694/console">Example</a></summary>

```
not ok 4201 wpt/test-compression
  ---
  duration_ms: 1440059.33400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    [SKIPPED] compression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-buffersource.tentative.any.js: ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] third_party/pako/pako_inflate.min.js: This is not a test file.
    [PASS] "a" should cause the constructor to throw
    [PASS] no input should cause the constructor to throw
    [PASS] non-string input should cause the constructor to throw
    [PASS] "a" should cause the constructor to throw
    [PASS] no inpu...
```
</details>

-------

| Reason | <code>parallel/test-runner-run</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55718/](https://ci.nodejs.org/job/node-test-pull-request/63759/), [https://github.com/nodejs/node/pull/55915/](https://ci.nodejs.org/job/node-test-pull-request/63766/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022/31453/console), [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/31448/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63759/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63766/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022/31453/console">Example</a></summary>

```
not ok 697 parallel/test-runner-run
  ---
  duration_ms: 1781.03900
  severity: fail
  exitcode: 1
  stack: |-
    ▶ require('node:test').run
      ✔ should run with no tests (270.0005ms)
      ✔ should fail with non existing file (701.8812ms)
      ✔ should succeed with a file (813.5092ms)
      ✔ should allow custom arguments via execArgv (651.1334ms)
      ✔ should allow custom arguments via argv (643.3148ms)
      ✔ should run same file twice (1257.7848ms)
      ✔ should run a failed test (630.6717ms)
      ✔ should support timeout (280.1064ms)
      ✔ should be piped with dot (733.8416ms)
      ▶ should be piped with spec reporter
        ✔ new spec (811.9979ms)
        ✔ spec() (696.9829ms)
        ✔ spec (925.2609ms)
      ✔ should be piped with spec reporter (939.1605ms)
      ✔ should be piped with tap (674.1844ms)
      ✔ should skip tests not matching testNamePatterns - RegExp (759.5896ms)
      ✔ should skip tests not matching testNamePatterns - string (952.7326ms)
      ✔ should pass only to chil...
```
</details>

-------

| Reason | <code>parallel/test-watch-mode-files_watcher</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55718/](https://ci.nodejs.org/job/node-test-pull-request/63756/), [https://github.com/nodejs/node/pull/56065/](https://ci.nodejs.org/job/node-test-pull-request/63757/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022/31449/console), [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022/31447/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63756/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63757/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022/31449/console">Example</a></summary>

```
not ok 1012 parallel/test-watch-mode-files_watcher
  ---
  duration_ms: 120219.38000
  severity: fail
  exitcode: 1
  stack: |-
    timeout
    ▶ watch mode file watcher
      ✔ should watch changed files (228.0336ms)
      ✔ should debounce changes (533.2841ms)
      ✔ should debounce changes on multiple files (348.9436ms)
      ✔ should ignore files in watched directory if they are not filtered (1003.7335ms)
      ✔ should allow clearing filters (1227.6471ms)
      ✔ should watch all files in watched path when in "all" mode (243.1608ms)
      ✔ should ruse existing watcher if it exists (1.9374ms)
      ✔ should ruse existing watcher of a parent directory (0.7576ms)
      ✔ should remove existing watcher if adding a parent directory watcher (1.7958ms)
      ✔ should clear all watchers when calling clear (1.485ms)
      ✖ should watch files from subprocess IPC events (143.161ms)
        AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
        + actual - expected
        
          [
...
```
</details>

-------

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55905/](https://ci.nodejs.org/job/node-test-pull-request/63789/), [https://github.com/nodejs/node/pull/55561/](https://ci.nodejs.org/job/node-test-pull-request/63796/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/47674/console), [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/56010/console), [test-osuosl-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/55975/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63789/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63796/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/47674/console">Example</a></summary>

```
not ok 4283 sequential/test-tls-session-timeout
  ---
  duration_ms: 213.09000
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:113
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at /home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:146:16
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:130:7)
        at ChildProcess.emit (node:events:513:28)
        at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual'
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------


### Jenkins Failure

| Reason | <code>Backing channel 'JNLP4-connect connection from ... is disconnected.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56052/](https://ci.nodejs.org/job/node-test-pull-request/63741/), [https://github.com/nodejs/node/pull/56055/](https://ci.nodejs.org/job/node-test-pull-request/63775/)) |
| Appeared | [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17843/console), [test-linuxonecc-rhel9-s390x-2](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/46943/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63741/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63775/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17843/console">Example</a></summary>

```
java.io.IOException: Backing channel 'JNLP4-connect connection from 207.254.38.86/207.254.38.86:49155' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:215)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:285)
	at jdk.proxy2/jdk.proxy2.$Proxy197.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1212)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1204)
```
</details>

-------

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56000/](https://ci.nodejs.org/job/node-test-pull-request/63737/), [https://github.com/nodejs/node/pull/56053/](https://ci.nodejs.org/job/node-test-pull-request/63765/)) |
| Appeared | [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/47641/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63737/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63765/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/47641/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/56050/](https://ci.nodejs.org/job/node-test-pull-request/63742/), [https://github.com/nodejs/node/pull/56065/](https://ci.nodejs.org/job/node-test-pull-request/63757/), [https://github.com/nodejs/node/pull/55896/](https://ci.nodejs.org/job/node-test-pull-request/63781/), [https://github.com/nodejs/node/pull/56076/](https://ci.nodejs.org/job/node-test-pull-request/63782/), [https://github.com/nodejs/node/pull/56080/](https://ci.nodejs.org/job/node-test-pull-request/63784/), [https://github.com/nodejs/node/pull/56084/](https://ci.nodejs.org/job/node-test-pull-request/63803/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/61897/console), [test-digitalocean-fedora40-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/61881/console), [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/61879/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63742/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63803/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/61897/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:997)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1239)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1310)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1277)
```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56040/](https://ci.nodejs.org/job/node-test-pull-request/63736/), [https://github.com/nodejs/node/pull/55896/](https://ci.nodejs.org/job/node-test-pull-request/63781/), [https://github.com/nodejs/node/pull/56071/](https://ci.nodejs.org/job/node-test-pull-request/63786/), [https://github.com/nodejs/node/pull/56063/](https://ci.nodejs.org/job/node-test-pull-request/63793/)) |
| Appeared | [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62310/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17862/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47665/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47660/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/57770/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63736/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63793/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62310/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>fatal: '/home/iojs/.ccache/node.shared.reference' does not appear to be a git repository</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56053/](https://ci.nodejs.org/job/node-test-pull-request/63744/), [https://github.com/nodejs/node/pull/56050/](https://ci.nodejs.org/job/node-test-pull-request/63752/), [https://github.com/nodejs/node/pull/56079/](https://ci.nodejs.org/job/node-test-pull-request/63828/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14831/console), [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14767/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14764/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63744/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63828/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14831/console">Example</a></summary>

```
fatal: '/home/iojs/.ccache/node.shared.reference' does not appear to be a git repository
fatal: Could not read from remote repository.
```
</details>

-------

| Reason | <code>ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56076/](https://ci.nodejs.org/job/node-test-pull-request/63777/), [https://github.com/nodejs/node/pull/56078/](https://ci.nodejs.org/job/node-test-pull-request/63816/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14819/console), [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/14819/console), [test-osuosl-aix72-ppc64_be-3](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54843/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55997/console), [test-osuosl-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/55997/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/55997/console), [test-equinix_mnx-smartos20-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57945/console), [test-equinix-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/16092/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63777/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63816/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14819/console">Example</a></summary>

```
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
[PostBuildScript] - [INFO] Executing post build scripts.
[node-test-binary-armv7l] $ /bin/bash -ex /tmp/jenkins14227543368464153291.sh
+ '[' -d .git ']'
+ git clean -fdx
Removing out/
```
</details>

-------

| Reason | <code>Error: - process terminated with status 1, expected 0</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56058/](https://ci.nodejs.org/job/node-test-pull-request/63774/), [https://github.com/nodejs/node/pull/56055/](https://ci.nodejs.org/job/node-test-pull-request/63775/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022/31465/console), [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022/31464/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63774/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63775/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022/31465/console">Example</a></summary>

```
Error: - process terminated with status 1, expected 0
  ---
  duration_ms: 44839.48000
  ...
ok 1012 sequential/test-single-executable-application-use-code-cache # skip Cannot find signtool: Error: - process terminated with status 1, expected 0
  ---
```
</details>

-------

| Reason | <code>fatal error: 'ranges' file not found</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56080/](https://ci.nodejs.org/job/node-test-pull-request/63784/), [https://github.com/nodejs/node/pull/56063/](https://ci.nodejs.org/job/node-test-pull-request/63801/)) |
| Appeared | [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62315/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17869/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63784/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63801/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62315/console">Example</a></summary>

```
fatal error: 'ranges' file not found
```
</details>

-------

