Failures in [node-test-pull-request/64792](https://ci.nodejs.org/job/node-test-pull-request/64792/) to [node-test-pull-request/64886](https://ci.nodejs.org/job/node-test-pull-request/64886/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-02-01.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-02-01 00:10 | 6       | 18      | 11       | 14      | 51      | 22.50%     |


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56790/](https://ci.nodejs.org/job/node-test-pull-request/64816/), [https://github.com/nodejs/node/pull/56811/](https://ci.nodejs.org/job/node-test-pull-request/64834/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/32368/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64816/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64834/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/32368/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56811/](https://ci.nodejs.org/job/node-test-pull-request/64834/), [https://github.com/nodejs/node/pull/56080/](https://ci.nodejs.org/job/node-test-pull-request/64845/)) |
| Appeared | [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/48731/console), [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/62881/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64834/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64845/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/48731/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1240)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1278)
```
</details>

-------


### undefined

| Reason | <code>Unknown</code> |
| - | :- |
| Type | undefined |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56790/](https://ci.nodejs.org/job/node-test-pull-request/64828/), [https://github.com/nodejs/node/pull/56727/](https://ci.nodejs.org/job/node-test-pull-request/64829/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-compile-windows-debug/nodes=win-vs2019/25911/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64828/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64829/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-compile-windows-debug/nodes=win-vs2019/25911/">Example</a></summary>

```
Unknown
```
</details>

-------


### JSTest Failure

| Reason | <code>parallel/test-assert-fail</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/56787/](https://ci.nodejs.org/job/node-test-pull-request/64843/), [https://github.com/nodejs/node/pull/56063/](https://ci.nodejs.org/job/node-test-pull-request/64844/), [https://github.com/nodejs/node/pull/56080/](https://ci.nodejs.org/job/node-test-pull-request/64845/), [https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/64846/), [https://github.com/nodejs/node/pull/56452/](https://ci.nodejs.org/job/node-test-pull-request/64847/), [https://github.com/nodejs/node/pull/56833/](https://ci.nodejs.org/job/node-test-pull-request/64855/), [https://github.com/nodejs/node/pull/56767/](https://ci.nodejs.org/job/node-test-pull-request/64865/), [https://github.com/nodejs/node/pull/56834/](https://ci.nodejs.org/job/node-test-pull-request/64886/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64843/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64886/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console">Example</a></summary>

```
not ok 18 parallel/test-assert-fail
  ---
  duration_ms: 432.50400
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'Object prototype get'
    Location: test/parallel/test-assert-fail.js:46:1
    Error: fail
        at TestContext.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/parallel/test-assert-fail.js:50:9)
        at Test.runInAsyncScope (node:async_hooks:211:14)
        at Test.run (node:internal/test_runner/test:980:25)
        at Test.processPendingSubtests (node:internal/test_runner/test:678:18)
        at Test.postRun (node:internal/test_runner/test:1091:19)
        at Test.run (node:internal/test_runner/test:1019:12)
        at async Test.processPendingSubtests (node:internal/test_runner/test:678:7)
    
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/56664/](https://ci.nodejs.org/job/node-test-pull-request/64842/), [https://github.com/nodejs/node/pull/56787/](https://ci.nodejs.org/job/node-test-pull-request/64843/), [https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/64846/), [https://github.com/nodejs/node/pull/56452/](https://ci.nodejs.org/job/node-test-pull-request/64847/), [https://github.com/nodejs/node/pull/56833/](https://ci.nodejs.org/job/node-test-pull-request/64855/), [https://github.com/nodejs/node/pull/56767/](https://ci.nodejs.org/job/node-test-pull-request/64865/), [https://github.com/nodejs/node/pull/56834/](https://ci.nodejs.org/job/node-test-pull-request/64886/)) |
| Appeared | [vm-4z8s5](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63417/console), [vm-cn7q6](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63391/console), [vm-jbbmk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63383/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64842/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64886/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63417/console">Example</a></summary>

```
not ok 2590 parallel/test-runner-run-watch
  ---
  duration_ms: 28059.54200
  severity: fail
  exitcode: 1
  stack: |-
    ▶ test runner watch mode
      ✔ should run tests repeatedly (3045.658412ms)
      ✔ should run tests with dependency repeatedly (2138.088143ms)
      ✔ should run tests with ESM dependency (2049.299132ms)
      ✔ should support running tests without a file (2600.677704ms)
      ✔ should support a watched test file rename (2417.05259ms)
      ✔ should not throw when deleting a watched test file (2783.588337ms)
      ✔ should run tests with dependency repeatedly in a different cwd (2951.65296ms)
      ✔ should handle renames in a different cwd (2242.642631ms)
      ✔ should run new tests when a new file is created in the watched directory (2040.628012ms)
      ▶ test runner watch mode with different cwd
        ✔ should execute run using a different cwd for the runner than the process cwd (1951.437786ms)
        ✔ should execute run using a different cwd for the runner than the process cwd...
```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/56250/](https://ci.nodejs.org/job/node-test-pull-request/64809/), [https://github.com/nodejs/node/pull/56624/](https://ci.nodejs.org/job/node-test-pull-request/64822/), [https://github.com/nodejs/node/pull/56826/](https://ci.nodejs.org/job/node-test-pull-request/64838/), [https://github.com/nodejs/node/pull/56063/](https://ci.nodejs.org/job/node-test-pull-request/64844/), [https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/64846/), [https://github.com/nodejs/node/pull/56818/](https://ci.nodejs.org/job/node-test-pull-request/64852/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/56952/console), [test-rackspace-win2019_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022/32382/console), [vm-ck2hm](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63381/console), [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/62887/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/48694/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64809/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64852/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/56952/console">Example</a></summary>

```
not ok 4164 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 360101.95600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-permission-fs-read</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/56739/](https://ci.nodejs.org/job/node-test-pull-request/64799/), [https://github.com/nodejs/node/pull/56782/](https://ci.nodejs.org/job/node-test-pull-request/64808/), [https://github.com/nodejs/node/pull/56675/](https://ci.nodejs.org/job/node-test-pull-request/64815/), [https://github.com/nodejs/node/pull/56805/](https://ci.nodejs.org/job/node-test-pull-request/64820/), [https://github.com/nodejs/node/pull/56790/](https://ci.nodejs.org/job/node-test-pull-request/64828/), [https://github.com/nodejs/node/pull/56811/](https://ci.nodejs.org/job/node-test-pull-request/64834/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2019/32353/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/32353/console), [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2019-x86/32353/console), [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2019/32353/console), [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2022-COMPILED_BY-vs2019/32353/console), [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/32353/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/32345/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/32345/console), [test-rackspace-win2016_vs2015-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2019-x86/32336/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2019/32336/console), [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2022-COMPILED_BY-vs2019/32336/console), [test-azure_msft-win11_vs2022-arm64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/32336/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64799/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64834/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2019/32353/console">Example</a></summary>

```
not ok 597 parallel/test-permission-fs-read
  ---
  duration_ms: 273.01800
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:90
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: node:assert:377
    
          throw err;
    
          ^
    
    
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    
    + actual - expected
    
    
    
      Comparison {
    
        code: 'ERR_ACCESS_DENIED',
    
        permission: 'FileSystemRead',
    
    +   resource: 'c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\fixtures\\permission\\deny\\protected-file.md'
    
    -   resource: '\\\\?\\c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\fixtures\\permission\\deny\\protected-file.md'
    
      }
    
        at ReadFileContext.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\common\index.js:727:12)
    
        at ReadFileContext.callback (c:\workspace\node-test-binary-windows-js-suit...
```
</details>

-------

| Reason | <code>parallel/test-permission-fs-write</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/56739/](https://ci.nodejs.org/job/node-test-pull-request/64799/), [https://github.com/nodejs/node/pull/56782/](https://ci.nodejs.org/job/node-test-pull-request/64808/), [https://github.com/nodejs/node/pull/56675/](https://ci.nodejs.org/job/node-test-pull-request/64815/), [https://github.com/nodejs/node/pull/56805/](https://ci.nodejs.org/job/node-test-pull-request/64820/), [https://github.com/nodejs/node/pull/56790/](https://ci.nodejs.org/job/node-test-pull-request/64828/), [https://github.com/nodejs/node/pull/56811/](https://ci.nodejs.org/job/node-test-pull-request/64834/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2019/32353/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/32353/console), [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2019-x86/32353/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2019/32353/console), [test-rackspace-win2022_vs2022-x64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2019/32353/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/32353/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2019/32345/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/32345/console), [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2019/32345/console), [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2019/32336/console), [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2019/32336/console), [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/32336/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64799/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64834/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2019/32353/console">Example</a></summary>

```
not ok 600 parallel/test-permission-fs-write
  ---
  duration_ms: 218.75100
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:90
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: node:assert:377
    
          throw err;
    
          ^
    
    
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    
    + actual - expected
    
    
    
      Comparison {
    
        code: 'ERR_ACCESS_DENIED',
    
        permission: 'FileSystemWrite',
    
    +   resource: 'c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\fixtures\\permission\\deny\\protected-file.md'
    
    -   resource: '\\\\?\\c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\fixtures\\permission\\deny\\protected-file.md'
    
      }
    
        at c:\workspace\node-test-binary-windows-js-suites\node\test\common\index.js:727:12
    
        at c:\workspace\node-test-binary-windows-js-suites\node\test\common\index.js:474:15
    
        at no...
```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-rangeerror</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/56781/](https://ci.nodejs.org/job/node-test-pull-request/64813/), [https://github.com/nodejs/node/pull/55014/](https://ci.nodejs.org/job/node-test-pull-request/64848/), [https://github.com/nodejs/node/pull/56819/](https://ci.nodejs.org/job/node-test-pull-request/64853/), [https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/64862/), [https://github.com/nodejs/node/pull/56826/](https://ci.nodejs.org/job/node-test-pull-request/64866/)) |
| Appeared | [test-ibm-rhel9-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/62909/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48748/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15695/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48734/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15661/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64813/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64866/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/62909/console">Example</a></summary>

```
not ok 809 parallel/test-buffer-tostring-rangeerror
  ---
  duration_ms: 120066.51200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    (node:163980) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    (node:163980) [DEP0030] DeprecationWarning: SlowBuffer() is deprecated. Please use Buffer.allocUnsafeSlow()
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/56290/](https://ci.nodejs.org/job/node-test-pull-request/64810/), [https://github.com/nodejs/node/pull/56727/](https://ci.nodejs.org/job/node-test-pull-request/64835/), [https://github.com/nodejs/node/pull/56826/](https://ci.nodejs.org/job/node-test-pull-request/64838/), [https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/64846/), [https://github.com/nodejs/node/pull/56699/](https://ci.nodejs.org/job/node-test-pull-request/64873/)) |
| Appeared | [test-digitalocean-freebsd13-x64-1](https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd13-x64/58696/console), [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/55724/console), [test-osuosl-aix72-ppc64_be-3](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/55718/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/47833/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64810/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64873/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd13-x64/58696/console">Example</a></summary>

```
not ok 2712 parallel/test-runner-output
  ---
  duration_ms: 29208.53900
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: test runner output
        # Subtest: test-runner/output/abort.js
        ok 1 - test-runner/output/abort.js
          ---
          duration_ms: 14641.953036
          ...

```
</details>

-------

| Reason | <code>wpt/test-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56827/](https://ci.nodejs.org/job/node-test-pull-request/64837/), [https://github.com/nodejs/node/pull/56826/](https://ci.nodejs.org/job/node-test-pull-request/64838/), [https://github.com/nodejs/node/pull/56080/](https://ci.nodejs.org/job/node-test-pull-request/64845/), [https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/64846/)) |
| Appeared | [test-digitalocean-alpine318_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/62885/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64837/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64846/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/62885/console">Example</a></summary>

```
not ok 4126 wpt/test-url
  ---
  duration_ms: 1513.07000
  severity: crashed
  exitcode: -11
  stack: |-
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] javascript-urls.window.js: requires document.body reference
    [SKIPPED] percent-encoding.window.js: TODO: port from .window.js
    [SKIPPED] url-setters-a-area.window.js?include=file: already tested in url-setters.any.js
    [SKIPPED] url-setters-a-area.window.js?include=javascript: already tested in url-setters.any.js
    [SKIPPED] url-setters-a-area.window.js?include=mailto: already tested in url-setters.any.js
    [SKIPPED] url-setters-a-area.window.js?exclude=(file|javascript|mailto): already tested in url-setters.any.js
    [PASS] ToASCII("fass.de")
    [PASS] ToASCII("faß.de")
    [PASS] ToASCII("Faß.de")
    [PASS] ToASCII("xn--fa-hia.de")
    [PASS] ToASCII("à.א̈")
    [PASS] ToASCII("à.א̈")
    [PASS] ToASCII("À.א̈")
    [PASS] ToASCII("À.א̈")
    [PASS] ToASCII("xn--0ca.xn--ssa73l")
    [PASS] ToA...
```
</details>

-------

| Reason | <code>parallel/test-cluster-fork-stdio</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56805/](https://ci.nodejs.org/job/node-test-pull-request/64820/), [https://github.com/nodejs/node/pull/56790/](https://ci.nodejs.org/job/node-test-pull-request/64828/), [https://github.com/nodejs/node/pull/56811/](https://ci.nodejs.org/job/node-test-pull-request/64834/)) |
| Appeared | [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2019-x86/32353/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64820/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64834/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2019-x86/32353/console">Example</a></summary>

```
not ok 945 parallel/test-cluster-fork-stdio
  ---
  duration_ms: 120176.94300
  severity: fail
  exitcode: 1
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56781/](https://ci.nodejs.org/job/node-test-pull-request/64813/), [https://github.com/nodejs/node/pull/56805/](https://ci.nodejs.org/job/node-test-pull-request/64814/), [https://github.com/nodejs/node/pull/56452/](https://ci.nodejs.org/job/node-test-pull-request/64859/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/56958/console), [vm-xbzlj](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/63383/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15663/console), [test-osuosl-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/56919/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64813/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64859/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/56958/console">Example</a></summary>

```
not ok 4022 parallel/test-file-write-stream4
  ---
  duration_ms: 360032.82200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-hex-string</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56655/](https://ci.nodejs.org/job/node-test-pull-request/64823/), [https://github.com/nodejs/node/pull/54030/](https://ci.nodejs.org/job/node-test-pull-request/64833/), [https://github.com/nodejs/node/pull/56080/](https://ci.nodejs.org/job/node-test-pull-request/64845/)) |
| Appeared | [vm-4z8s5](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63382/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/48719/console), [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15670/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64823/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64845/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63382/console">Example</a></summary>

```
not ok 2595 parallel/test-net-write-fully-async-hex-string
  ---
  duration_ms: 120217.93600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>wpt/test-compression</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56063/](https://ci.nodejs.org/job/node-test-pull-request/64844/), [https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/64862/), [https://github.com/nodejs/node/pull/56452/](https://ci.nodejs.org/job/node-test-pull-request/64884/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48769/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48748/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64844/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64884/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48769/console">Example</a></summary>

```
not ok 4283 wpt/test-compression
  ---
  duration_ms: 1440057.79100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    [SKIPPED] compression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-buffersource.tentative.any.js: ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] third_party/pako/pako_inflate.min.js: This is not a test file.
    [PASS] "a" should cause the constructor to throw
    [PASS] no input should cause the constructor to throw
    [PASS] non-string input should cause the constructor to throw
    [PASS] "a" should cause the constructor to throw
    [PASS] no inpu...
```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-range</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56782/](https://ci.nodejs.org/job/node-test-pull-request/64808/), [https://github.com/nodejs/node/pull/56727/](https://ci.nodejs.org/job/node-test-pull-request/64849/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/47872/console), [test-mnx-smartos22-x64-1](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/58900/console), [test-mnx-smartos23-x64-5](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/58900/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64808/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64849/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/47872/console">Example</a></summary>

```
not ok 142 parallel/test-buffer-tostring-range
  ---
  duration_ms: 410.78200
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/buffer:961
        super(bufferOrLength, byteOffset, length);
        ^
    
    RangeError: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at new Uint8Array (<anonymous>)
        at new FastBuffer (node:internal/buffer:961:5)
        at Function.alloc (node:buffer:395:10)
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-linuxone/test/parallel/test-buffer-tostring-range.js:107:28)
        at Module._compile (node:internal/modules/cjs/loader:1469:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
        at Module.load (node:internal/modules/cjs/loader:1288:32)
        at Module._load (node:internal/modules/cjs/loader:1104:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:173:12)
    
    Node.js v20.18.3-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-child-process-bad-stdio</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56250/](https://ci.nodejs.org/job/node-test-pull-request/64809/), [https://github.com/nodejs/node/pull/56787/](https://ci.nodejs.org/job/node-test-pull-request/64843/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/48729/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/48694/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64809/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64843/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/48729/console">Example</a></summary>

```
not ok 156 parallel/test-child-process-bad-stdio
  ---
  duration_ms: 2331.36900
  severity: fail
  exitcode: 1
  stack: |-
    ✔ normal execution of a child process is handled (160.751438ms)
    ✔ execution with an error event is handled (2.427236ms)
    ✖ execution with a killed process is handled (1869.659822ms)
    ℹ tests 3
    ℹ suites 0
    ℹ pass 2
    ℹ fail 1
    ℹ cancelled 0
    ℹ skipped 0
    ℹ todo 0
    ℹ duration_ms 2055.543584
    
    ✖ failing tests:
    
    test at test/parallel/test-child-process-bad-stdio.js:59:1
    ✖ execution with a killed process is handled (1869.659822ms)
      TypeError: Cannot read properties of null (reading 'killed')
          at /home/iojs/build/workspace/node-test-commit-linux-containered/test/parallel/test-child-process-bad-stdio.js:61:28
          at /home/iojs/build/workspace/node-test-commit-linux-containered/test/common/index.js:435:15
          at ChildProcess.exithandler (node:child_process:407:7)
          at ChildProcess.emit (node:events:507:28)
  ...
```
</details>

-------

| Reason | <code>parallel/test-esm-loader-hooks-inspect-wait</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56727/](https://ci.nodejs.org/job/node-test-pull-request/64829/), [https://github.com/nodejs/node/pull/56699/](https://ci.nodejs.org/job/node-test-pull-request/64869/)) |
| Appeared | [test-digitalocean-freebsd13-x64-1](https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd13-x64/58691/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64829/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64869/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd13-x64/58691/console">Example</a></summary>

```
not ok 1014 parallel/test-esm-loader-hooks-inspect-wait
  ---
  duration_ms: 871.89600
  severity: fail
  exitcode: 1
  stack: |-
    [test] Connecting to a child Node process
    [test] Testing /json/list
    [err] Debugger listening on ws://127.0.0.1:32891/158cc9d7-cf9a-4bcb-bb21-e91821281178
    [err] For help, see: https://nodejs.org/en/docs/inspector
    [err] 
    [err] Debugger attached.
    [err] 
    [err] Waiting for the debugger to disconnect...
    [err] 
    [err] child process crashed, signal SIGSEGV
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    null !== 0
    
        at runTest (/usr/home/iojs/build/workspace/node-test-commit-freebsd/nodes/freebsd13-x64/test/parallel/test-esm-loader-hooks-inspect-wait.js:27:10)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: null,
      expected: 0,
      operator: 'strictEqual'
    }
    1
  ...

```
</details>

-------

| Reason | <code>parallel/test-fs-cp</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56739/](https://ci.nodejs.org/job/node-test-pull-request/64799/), [https://github.com/nodejs/node/pull/56675/](https://ci.nodejs.org/job/node-test-pull-request/64815/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022/32350/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64799/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64815/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022/32350/console">Example</a></summary>

```
not ok 303 parallel/test-fs-cp
  ---
  duration_ms: 572.01500
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:128
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    
    + 'ERR_FS_EISDIR'
    - 'ERR_FS_CP_EINVAL'
              ^
    
        at file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-fs-cp.mjs:687:12
        at c:\workspace\node-test-binary-windows-js-suites\node\test\common\index.js:491:15
        at node:fs:190:23
        at callbackifyOnRejected (node:util:230:10)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'ERR_FS_EISDIR',
      expected: 'ERR_FS_CP_EINVAL',
      operator: 'strictEqual'
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-pipe-file-to-http</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56827/](https://ci.nodejs.org/job/node-test-pull-request/64837/), [https://github.com/nodejs/node/pull/56452/](https://ci.nodejs.org/job/node-test-pull-request/64847/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15690/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15684/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64837/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64847/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15690/console">Example</a></summary>

```
not ok 4032 parallel/test-pipe-file-to-http
  ---
  duration_ms: 360098.63700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-unpipe-resume</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56798/](https://ci.nodejs.org/job/node-test-pull-request/64797/), [https://github.com/nodejs/node/pull/56452/](https://ci.nodejs.org/job/node-test-pull-request/64859/)) |
| Appeared | [test-mnx-smartos23-x64-5](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/58946/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/48687/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64797/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64859/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/58946/console">Example</a></summary>

```
not ok 3990 parallel/test-stream-readable-unpipe-resume
  ---
  duration_ms: 300121.03900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>pummel/test-heapdump-http2</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56800/](https://ci.nodejs.org/job/node-test-pull-request/64796/), [https://github.com/nodejs/node/pull/56826/](https://ci.nodejs.org/job/node-test-pull-request/64850/)) |
| Appeared | [test-digitalocean-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/62896/console), [test-rackspace-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/62853/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64796/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64850/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/62896/console">Example</a></summary>

```
not ok 4003 pummel/test-heapdump-http2
  ---
  duration_ms: 720039.55900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    (node:2112022) internal/test/binding: These APIs are for internal testing only. Do not use them.
    (Use `node --trace-warnings ...` to show where the warning was created)
  ...

```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56811/](https://ci.nodejs.org/job/node-test-pull-request/64834/), [https://github.com/nodejs/node/pull/56833/](https://ci.nodejs.org/job/node-test-pull-request/64855/), [https://github.com/nodejs/node/pull/56664/](https://ci.nodejs.org/job/node-test-pull-request/64856/), [https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/64862/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/48748/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48741/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/58678/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/48733/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64834/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64862/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/48748/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

