Failures in [node-test-pull-request/67745](https://ci.nodejs.org/job/node-test-pull-request/67745/) to [node-test-pull-request/67844](https://ci.nodejs.org/job/node-test-pull-request/67844/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-07-05.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-07-05 00:11 | 0       | 0       | 25       | 1       | 74      | 0.00%      |


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 13 ([https://github.com/nodejs/node/pull/58745/](https://ci.nodejs.org/job/node-test-pull-request/67747/), [https://github.com/nodejs/node/pull/58749/](https://ci.nodejs.org/job/node-test-pull-request/67749/), [https://github.com/nodejs/node/pull/58914/](https://ci.nodejs.org/job/node-test-pull-request/67762/), [https://github.com/nodejs/node/pull/58915/](https://ci.nodejs.org/job/node-test-pull-request/67768/), [https://github.com/nodejs/node/pull/58253/](https://ci.nodejs.org/job/node-test-pull-request/67772/), [https://github.com/nodejs/node/pull/58087/](https://ci.nodejs.org/job/node-test-pull-request/67777/), [https://github.com/nodejs/node/pull/58928/](https://ci.nodejs.org/job/node-test-pull-request/67792/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/67806/), [https://github.com/nodejs/node/pull/58902/](https://ci.nodejs.org/job/node-test-pull-request/67811/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/67835/), [https://github.com/nodejs/node/pull/58077/](https://ci.nodejs.org/job/node-test-pull-request/67839/), [https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67843/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67844/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/35217/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67747/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67844/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/35217/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58773/](https://ci.nodejs.org/job/node-test-pull-request/67804/), [https://github.com/nodejs/node/pull/58886/](https://ci.nodejs.org/job/node-test-pull-request/67820/)) |
| Appeared | [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57984/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51514/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67804/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67820/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57984/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/67806/), [https://github.com/nodejs/node/pull/58121/](https://ci.nodejs.org/job/node-test-pull-request/67834/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19239/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67806/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67834/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19239/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1240)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1278)
```
</details>

-------


### Build Failure

| Reason | <code>Failed to trigger sub builds</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58253/](https://ci.nodejs.org/job/node-test-pull-request/67767/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67823/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit/81044/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67767/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67823/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit/81044/console">Example</a></summary>

```
Failed to trigger sub builds
```
</details>

-------

| Reason | <code>fatal error: Killed signal terminated program cc1plus</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58818/](https://ci.nodejs.org/job/node-test-pull-request/67776/), [https://github.com/nodejs/node/pull/58902/](https://ci.nodejs.org/job/node-test-pull-request/67784/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/51495/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51495/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51488/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51488/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67776/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67784/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/51495/console">Example</a></summary>

```
fatal error: Killed signal terminated program cc1plus
```
</details>

-------


### JSTest Failure

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 19 ([https://github.com/nodejs/node/pull/58845/](https://ci.nodejs.org/job/node-test-pull-request/67745/), [https://github.com/nodejs/node/pull/58853/](https://ci.nodejs.org/job/node-test-pull-request/67750/), [https://github.com/nodejs/node/pull/58861/](https://ci.nodejs.org/job/node-test-pull-request/67756/), [https://github.com/nodejs/node/pull/58896/](https://ci.nodejs.org/job/node-test-pull-request/67757/), [https://github.com/nodejs/node/pull/58898/](https://ci.nodejs.org/job/node-test-pull-request/67763/), [https://github.com/nodejs/node/pull/58916/](https://ci.nodejs.org/job/node-test-pull-request/67766/), [https://github.com/nodejs/node/pull/58920/](https://ci.nodejs.org/job/node-test-pull-request/67782/), [https://github.com/nodejs/node/pull/58886/](https://ci.nodejs.org/job/node-test-pull-request/67783/), [https://github.com/nodejs/node/pull/52329/](https://ci.nodejs.org/job/node-test-pull-request/67785/), [https://github.com/nodejs/node/pull/58928/](https://ci.nodejs.org/job/node-test-pull-request/67786/), [https://github.com/nodejs/node/pull/57214/](https://ci.nodejs.org/job/node-test-pull-request/67787/), [https://github.com/nodejs/node/pull/58749/](https://ci.nodejs.org/job/node-test-pull-request/67794/), [https://github.com/nodejs/node/pull/58713/](https://ci.nodejs.org/job/node-test-pull-request/67805/), [https://github.com/nodejs/node/pull/58938/](https://ci.nodejs.org/job/node-test-pull-request/67807/), [https://github.com/nodejs/node/pull/58948/](https://ci.nodejs.org/job/node-test-pull-request/67826/), [https://github.com/nodejs/node/pull/58951/](https://ci.nodejs.org/job/node-test-pull-request/67837/), [https://github.com/nodejs/node/pull/58077/](https://ci.nodejs.org/job/node-test-pull-request/67839/), [https://github.com/nodejs/node/pull/58940/](https://ci.nodejs.org/job/node-test-pull-request/67840/), [https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67843/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/42962/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51541/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/59767/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/51540/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51539/console), [test-digitalocean-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65461/console), [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65453/console), [test-mnx-smartos23-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/61388/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50359/console), [test-ibm-rhel9-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/65434/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51496/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50341/console), [test-digitalocean-ubuntu2204-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/65418/console), [test-osuosl-rhel9-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/59709/console), [test-osuosl-rhel8-ppc64_le-4](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/59704/console), [vm-2l6mr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65759/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67745/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67843/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/42962/console">Example</a></summary>

```
not ok 3036 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 1411.94000
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'can be overridden (to SIGINT)'
    Location: test/parallel/test-runner-watch-mode-kill-signal.mjs:80:3
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /__SIGINT received__/. Input:
    
    'ready!\n' +
      "Restarting '/home/iojs/node-tmp/.tmp.3038/index.js'\n" +
      '__SIGTERM received__\n'
    
        at TestContext.<anonymous> (file:///home/iojs/build/workspace/node/test/parallel/test-runner-watch-mode-kill-signal.mjs:102:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Test.run (node:internal/test_runner/test:1069:7)
        at async Suite.processPendingSubtests (node:internal/test_runner/test:752:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'ready!\n' +
        "Restarting '/home/iojs/node-tmp/.tmp.3038/index.js'\n" +
        ...
```
</details>

-------

| Reason | <code>pummel/test-string-decoder-large-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 18 ([https://github.com/nodejs/node/pull/58749/](https://ci.nodejs.org/job/node-test-pull-request/67749/), [https://github.com/nodejs/node/pull/58915/](https://ci.nodejs.org/job/node-test-pull-request/67768/), [https://github.com/nodejs/node/pull/58253/](https://ci.nodejs.org/job/node-test-pull-request/67772/), [https://github.com/nodejs/node/pull/58818/](https://ci.nodejs.org/job/node-test-pull-request/67776/), [https://github.com/nodejs/node/pull/58087/](https://ci.nodejs.org/job/node-test-pull-request/67777/), [https://github.com/nodejs/node/pull/58914/](https://ci.nodejs.org/job/node-test-pull-request/67780/), [https://github.com/nodejs/node/pull/58901/](https://ci.nodejs.org/job/node-test-pull-request/67781/), [https://github.com/nodejs/node/pull/58745/](https://ci.nodejs.org/job/node-test-pull-request/67791/), [https://github.com/nodejs/node/pull/58928/](https://ci.nodejs.org/job/node-test-pull-request/67792/), [https://github.com/nodejs/node/pull/58713/](https://ci.nodejs.org/job/node-test-pull-request/67805/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/67806/), [https://github.com/nodejs/node/pull/58902/](https://ci.nodejs.org/job/node-test-pull-request/67811/), [https://github.com/nodejs/node/pull/58952/](https://ci.nodejs.org/job/node-test-pull-request/67828/), [https://github.com/nodejs/node/pull/57298/](https://ci.nodejs.org/job/node-test-pull-request/67830/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/67835/), [https://github.com/nodejs/node/pull/58077/](https://ci.nodejs.org/job/node-test-pull-request/67839/), [https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67843/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67844/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/35217/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67749/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67844/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/35217/console">Example</a></summary>

```
not ok 1028 pummel/test-string-decoder-large-buffer
  ---
  duration_ms: 155.10900
  severity: fail
  exitcode: 1
  stack: |-
    c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-string-decoder-large-buffer.js:26
        throw e;
        ^
    
    RangeError: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at new Uint8Array (<anonymous>)
        at new FastBuffer (node:internal/buffer:961:5)
        at createUnsafeBuffer (node:internal/buffer:1097:12)
        at allocate (node:buffer:444:10)
        at Function.allocUnsafe (node:buffer:409:10)
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-string-decoder-large-buffer.js:21:22)
        at Module._compile (node:internal/modules/cjs/loader:1688:14)
        at Object..js (node:internal/modules/cjs/loader:1820:10)
        at Module.load (node:internal/modules/cjs/loader:1423:32)
    
    Node.js v22.17.1-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-child-process-advanced-serialization-splitted-length-field</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 13 ([https://github.com/nodejs/node/pull/58915/](https://ci.nodejs.org/job/node-test-pull-request/67768/), [https://github.com/nodejs/node/pull/58253/](https://ci.nodejs.org/job/node-test-pull-request/67772/), [https://github.com/nodejs/node/pull/58818/](https://ci.nodejs.org/job/node-test-pull-request/67776/), [https://github.com/nodejs/node/pull/58087/](https://ci.nodejs.org/job/node-test-pull-request/67777/), [https://github.com/nodejs/node/pull/58914/](https://ci.nodejs.org/job/node-test-pull-request/67780/), [https://github.com/nodejs/node/pull/58901/](https://ci.nodejs.org/job/node-test-pull-request/67781/), [https://github.com/nodejs/node/pull/58886/](https://ci.nodejs.org/job/node-test-pull-request/67783/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67803/), [https://github.com/nodejs/node/pull/58713/](https://ci.nodejs.org/job/node-test-pull-request/67805/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/67806/), [https://github.com/nodejs/node/pull/58902/](https://ci.nodejs.org/job/node-test-pull-request/67811/), [https://github.com/nodejs/node/pull/58952/](https://ci.nodejs.org/job/node-test-pull-request/67828/), [https://github.com/nodejs/node/pull/57298/](https://ci.nodejs.org/job/node-test-pull-request/67830/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/35189/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/35148/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67768/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67830/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/35189/console">Example</a></summary>

```
not ok 104 parallel/test-child-process-advanced-serialization-splitted-length-field
  ---
  duration_ms: 112.99700
  severity: crashed
  exitcode: 2147483651
  stack: |-
    
    <--- Last few GCs --->
    
    
    <--- JS stacktrace --->
    
    
    #
    # Fatal javascript OOM in MemoryChunk allocation failed during deserialization.
    #
    
  ...

```
</details>

-------

| Reason | <code>parallel/test-config-file</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/57298/](https://ci.nodejs.org/job/node-test-pull-request/67761/), [https://github.com/nodejs/node/pull/58818/](https://ci.nodejs.org/job/node-test-pull-request/67776/), [https://github.com/nodejs/node/pull/58087/](https://ci.nodejs.org/job/node-test-pull-request/67777/), [https://github.com/nodejs/node/pull/58914/](https://ci.nodejs.org/job/node-test-pull-request/67780/), [https://github.com/nodejs/node/pull/58901/](https://ci.nodejs.org/job/node-test-pull-request/67781/), [https://github.com/nodejs/node/pull/58886/](https://ci.nodejs.org/job/node-test-pull-request/67783/), [https://github.com/nodejs/node/pull/58745/](https://ci.nodejs.org/job/node-test-pull-request/67791/), [https://github.com/nodejs/node/pull/58928/](https://ci.nodejs.org/job/node-test-pull-request/67792/), [https://github.com/nodejs/node/pull/58902/](https://ci.nodejs.org/job/node-test-pull-request/67793/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/35183/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/35167/console), [test-rackspace-win2022_vs2022-x64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/35161/console), [test-azure_msft-win11_vs2022-arm64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35165/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67761/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67793/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/35183/console">Example</a></summary>

```
not ok 229 parallel/test-config-file
  ---
  duration_ms: 3806.10700
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: '--inspect=true should be parsed correctly'
    Location: test\parallel\test-config-file.js:237:1
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /^Debugger listening on (ws:\/\/[^\s]+)/. Input:
    
    'Starting inspector on 127.0.0.1:9229 failed: address already in use\r\n'
    
        at TestContext.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-config-file.js:244:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Test.run (node:internal/test_runner/test:1054:7)
        at async Test.processPendingSubtests (node:internal/test_runner/test:744:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'Starting inspector on 127.0.0.1:9229 failed: address already in use\r\n',
      expected: /^Debugger listening on (ws:\/\/[^\s]+)/,
 ...
```
</details>

-------

| Reason | <code>parallel/test-worker-message-port-transfer-filehandle</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/58253/](https://ci.nodejs.org/job/node-test-pull-request/67772/), [https://github.com/nodejs/node/pull/58886/](https://ci.nodejs.org/job/node-test-pull-request/67783/), [https://github.com/nodejs/node/pull/58902/](https://ci.nodejs.org/job/node-test-pull-request/67784/), [https://github.com/nodejs/node/pull/58713/](https://ci.nodejs.org/job/node-test-pull-request/67805/), [https://github.com/nodejs/node/pull/58952/](https://ci.nodejs.org/job/node-test-pull-request/67828/), [https://github.com/nodejs/node/pull/57298/](https://ci.nodejs.org/job/node-test-pull-request/67830/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35213/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35194/console), [test-azure_msft-win11_vs2022-arm64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35159/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67772/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67830/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35213/console">Example</a></summary>

```
not ok 980 parallel/test-worker-message-port-transfer-filehandle
  ---
  duration_ms: 277.00000
  severity: fail
  exitcode: 1
  stack: |-
    <anonymous_script>:0
    
    
    [Error: A FileHandle object was closed during garbage collection. This used to be allowed with a deprecation warning but is now considered an error. Please close FileHandle objects explicitly.] {
      code: 'ERR_INVALID_STATE'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-to-web</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58898/](https://ci.nodejs.org/job/node-test-pull-request/67746/), [https://github.com/nodejs/node/pull/58087/](https://ci.nodejs.org/job/node-test-pull-request/67771/), [https://github.com/nodejs/node/pull/58938/](https://ci.nodejs.org/job/node-test-pull-request/67799/), [https://github.com/nodejs/node/pull/58948/](https://ci.nodejs.org/job/node-test-pull-request/67822/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51526/console), [test-osuosl-rhel9-ppc64_le-4](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/59740/console), [test-osuosl-rhel9-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/59721/console), [test-ibm-rhel8-s390x-3](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50312/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67746/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67822/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51526/console">Example</a></summary>

```
not ok 2847 parallel/test-stream-readable-to-web
  ---
  duration_ms: 119.22600
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/util:234
        throw new ERR_NO_CRYPTO();
              ^
    
    Error [ERR_NO_CRYPTO]: Node.js is not compiled with OpenSSL crypto support
        at assertCrypto (node:internal/util:234:11)
        at node:crypto:36:1
        at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:398:7)
        at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:337:10)
        at loadBuiltinModule (node:internal/modules/helpers:109:7)
        at ModuleLoader.builtinStrategy (node:internal/modules/esm/translators:417:18)
        at #translate (node:internal/modules/esm/loader:546:12)
        at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:593:27)
        at async #link (node:internal/modules/esm/module_job:180:19) {
      code: 'ERR_NO_CRYPTO'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>es-module/test-vm-contextified-script-leak</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58749/](https://ci.nodejs.org/job/node-test-pull-request/67749/), [https://github.com/nodejs/node/pull/58915/](https://ci.nodejs.org/job/node-test-pull-request/67768/), [https://github.com/nodejs/node/pull/58901/](https://ci.nodejs.org/job/node-test-pull-request/67781/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35168/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35155/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67749/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67781/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35168/console">Example</a></summary>

```
not ok 65 es-module/test-vm-contextified-script-leak
  ---
  duration_ms: 265.01000
  severity: crashed
  exitcode: 3221225477
  stack: |-
    Created 128 objects
    Created 256 objects
    Found finalized object at 299, stop testing
  ...

```
</details>

-------

| Reason | <code>sequential/test-child-process-pass-fd</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58077/](https://ci.nodejs.org/job/node-test-pull-request/67839/), [https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67843/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67844/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/35231/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67839/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67844/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/35231/console">Example</a></summary>

```
not ok 1047 sequential/test-child-process-pass-fd
  ---
  duration_ms: 120309.42300
  severity: fail
  exitcode: 1
  stack: |-
    timeout
    
    <--- Last few GCs --->
    
    
    <--- Last few GCs --->
    
    
    <--- Last few GCs --->
    
    
    
    #
    # Fatal JavaScript out of memory: MemoryChunk allocation failed during deserialization.
    #
    
    #
    # Fatal JavaScript out of memory: MemoryChunk allocation failed during deserialization.
    #
    
    ----- Native stack trace -----
    
    
    <--- Last few GCs --->
    [10432:000001E1F55B1000]       99 ms: Scavenge 5.6 (6.5) -> 5.1 (7.5) MB, pooled: 0 MB, 1.32 / 0.00 ms  (average mu = 1.000, current mu = 1.000) allocation failure; 
    
    FATAL ERROR: Zone Allocation failed - process out of memory
    ----- Native stack trace -----
    
     1: 00007FF644E4BCB9 
    
    <--- Last few GCs --->
    [13572:000001F816163000]      187 ms: Scavenge 5.6 (6.5) -> 5.1 (7.5) MB, pooled: 0 MB, 0.93 / 0.00 ms  (average mu = 1.000, current ...
```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58901/](https://ci.nodejs.org/job/node-test-pull-request/67754/), [https://github.com/nodejs/node/pull/58773/](https://ci.nodejs.org/job/node-test-pull-request/67804/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51514/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50315/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51468/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67754/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67804/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51514/console">Example</a></summary>

```
not ok 4482 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 7347.87000
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:272
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

