Failures in [node-test-pull-request/67798](https://ci.nodejs.org/job/node-test-pull-request/67798/) to [node-test-pull-request/67892](https://ci.nodejs.org/job/node-test-pull-request/67892/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-07-09.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-07-09 00:12 | 1       | 1       | 27       | 2       | 69      | 1.03%      |


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/67806/), [https://github.com/nodejs/node/pull/58902/](https://ci.nodejs.org/job/node-test-pull-request/67811/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/67835/), [https://github.com/nodejs/node/pull/58077/](https://ci.nodejs.org/job/node-test-pull-request/67839/), [https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67843/), [https://github.com/nodejs/node/pull/58961/](https://ci.nodejs.org/job/node-test-pull-request/67849/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67868/), [https://github.com/nodejs/node/pull/58948/](https://ci.nodejs.org/job/node-test-pull-request/67878/), [https://github.com/nodejs/node/pull/58978/](https://ci.nodejs.org/job/node-test-pull-request/67890/), [https://github.com/nodejs/node/pull/58977/](https://ci.nodejs.org/job/node-test-pull-request/67892/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/35302/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35293/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67806/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67892/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/35302/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58773/](https://ci.nodejs.org/job/node-test-pull-request/67804/), [https://github.com/nodejs/node/pull/58886/](https://ci.nodejs.org/job/node-test-pull-request/67820/), [https://github.com/nodejs/node/pull/58986/](https://ci.nodejs.org/job/node-test-pull-request/67885/), [https://github.com/nodejs/node/pull/58997/](https://ci.nodejs.org/job/node-test-pull-request/67891/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58038/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51596/console), [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57984/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67804/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67891/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58038/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/67806/), [https://github.com/nodejs/node/pull/58121/](https://ci.nodejs.org/job/node-test-pull-request/67834/), [https://github.com/nodejs/node/pull/58961/](https://ci.nodejs.org/job/node-test-pull-request/67849/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/67873/), [https://github.com/nodejs/node/pull/58440/](https://ci.nodejs.org/job/node-test-pull-request/67874/), [https://github.com/nodejs/node/pull/58948/](https://ci.nodejs.org/job/node-test-pull-request/67878/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/65509/console), [test-equinix-ubuntu2204_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19275/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67806/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67878/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/65509/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1240)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1278)
```
</details>

-------

| Reason | <code>Command "git reset --hard" returned status code 128:</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58938/](https://ci.nodejs.org/job/node-test-pull-request/67799/), [https://github.com/nodejs/node/pull/58966/](https://ci.nodejs.org/job/node-test-pull-request/67871/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/65504/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67799/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67871/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/65504/console">Example</a></summary>

```
hudson.plugins.git.GitException: Command "git reset --hard" returned status code 128:
stdout: 
stderr: fatal: Unable to create '/home/iojs/build/workspace/node/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58967/](https://ci.nodejs.org/job/node-test-pull-request/67861/), [https://github.com/nodejs/node/pull/58680/](https://ci.nodejs.org/job/node-test-pull-request/67867/), [https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67875/), [https://github.com/nodejs/node/pull/58948/](https://ci.nodejs.org/job/node-test-pull-request/67878/), [https://github.com/nodejs/node/pull/58957/](https://ci.nodejs.org/job/node-test-pull-request/67886/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51597/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51581/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51572/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51563/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67861/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67886/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51597/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------


### undefined


### JSTest Failure

| Reason | <code>pummel/test-string-decoder-large-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 14 ([https://github.com/nodejs/node/pull/58713/](https://ci.nodejs.org/job/node-test-pull-request/67805/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/67806/), [https://github.com/nodejs/node/pull/58902/](https://ci.nodejs.org/job/node-test-pull-request/67811/), [https://github.com/nodejs/node/pull/58952/](https://ci.nodejs.org/job/node-test-pull-request/67828/), [https://github.com/nodejs/node/pull/57298/](https://ci.nodejs.org/job/node-test-pull-request/67830/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/67835/), [https://github.com/nodejs/node/pull/58077/](https://ci.nodejs.org/job/node-test-pull-request/67839/), [https://github.com/nodejs/node/pull/58960/](https://ci.nodejs.org/job/node-test-pull-request/67848/), [https://github.com/nodejs/node/pull/58961/](https://ci.nodejs.org/job/node-test-pull-request/67850/), [https://github.com/nodejs/node/pull/58940/](https://ci.nodejs.org/job/node-test-pull-request/67851/), [https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67862/), [https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67863/), [https://github.com/nodejs/node/pull/58680/](https://ci.nodejs.org/job/node-test-pull-request/67867/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67868/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/35268/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67805/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67868/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/35268/console">Example</a></summary>

```
not ok 1028 pummel/test-string-decoder-large-buffer
  ---
  duration_ms: 169.26500
  severity: fail
  exitcode: 1
  stack: |-
    c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-string-decoder-large-buffer.js:26
        throw e;
        ^
    
    RangeError: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at new Uint8Array (<anonymous>)
        at new FastBuffer (node:internal/buffer:961:5)
        at createUnsafeBuffer (node:internal/buffer:1097:12)
        at allocate (node:buffer:444:10)
        at Function.allocUnsafe (node:buffer:409:10)
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-string-decoder-large-buffer.js:21:22)
        at Module._compile (node:internal/modules/cjs/loader:1688:14)
        at Object..js (node:internal/modules/cjs/loader:1820:10)
        at Module.load (node:internal/modules/cjs/loader:1423:32)
    
    Node.js v22.17.1-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/58713/](https://ci.nodejs.org/job/node-test-pull-request/67805/), [https://github.com/nodejs/node/pull/58938/](https://ci.nodejs.org/job/node-test-pull-request/67807/), [https://github.com/nodejs/node/pull/58951/](https://ci.nodejs.org/job/node-test-pull-request/67837/), [https://github.com/nodejs/node/pull/58077/](https://ci.nodejs.org/job/node-test-pull-request/67839/), [https://github.com/nodejs/node/pull/58940/](https://ci.nodejs.org/job/node-test-pull-request/67840/), [https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67843/), [https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67860/), [https://github.com/nodejs/node/pull/58966/](https://ci.nodejs.org/job/node-test-pull-request/67871/), [https://github.com/nodejs/node/pull/58948/](https://ci.nodejs.org/job/node-test-pull-request/67878/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51583/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51577/console), [vm-2wfdk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65832/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51562/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/42962/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/59767/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51539/console), [test-digitalocean-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65461/console), [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65453/console), [test-mnx-smartos23-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/61388/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50359/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67805/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67878/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51583/console">Example</a></summary>

```
not ok 2642 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 1416.86000
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'defaults to SIGTERM'
    Location: test/parallel/test-runner-watch-mode-kill-signal.mjs:56:3
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    0 !== 123
    
        at TestContext.<anonymous> (file:///home/iojs/build/workspace/node-test-commit-linux-containered/test/parallel/test-runner-watch-mode-kill-signal.mjs:77:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Test.run (node:internal/test_runner/test:1069:7)
        at async Promise.all (index 0)
        at async Suite.run (node:internal/test_runner/test:1466:7)
        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:332:3) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 0,
      expected: 123,
      operator: 'strictEqual'
    }
    
  ...

```
</details>

-------

| Reason | <code>parallel/test-child-process-advanced-serialization-splitted-length-field</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67803/), [https://github.com/nodejs/node/pull/58713/](https://ci.nodejs.org/job/node-test-pull-request/67805/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/67806/), [https://github.com/nodejs/node/pull/58902/](https://ci.nodejs.org/job/node-test-pull-request/67811/), [https://github.com/nodejs/node/pull/58952/](https://ci.nodejs.org/job/node-test-pull-request/67828/), [https://github.com/nodejs/node/pull/57298/](https://ci.nodejs.org/job/node-test-pull-request/67830/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/35189/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67803/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67830/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/35189/console">Example</a></summary>

```
not ok 104 parallel/test-child-process-advanced-serialization-splitted-length-field
  ---
  duration_ms: 112.99700
  severity: crashed
  exitcode: 2147483651
  stack: |-
    
    <--- Last few GCs --->
    
    
    <--- JS stacktrace --->
    
    
    #
    # Fatal javascript OOM in MemoryChunk allocation failed during deserialization.
    #
    
  ...

```
</details>

-------

| Reason | <code>es-module/test-esm-loader-chaining</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58680/](https://ci.nodejs.org/job/node-test-pull-request/67867/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67868/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/67873/), [https://github.com/nodejs/node/pull/58948/](https://ci.nodejs.org/job/node-test-pull-request/67878/), [https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67881/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2019/35271/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67867/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67881/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2019/35271/console">Example</a></summary>

```
not ok 41 es-module/test-esm-loader-chaining
  ---
  duration_ms: 1764.11500
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: ESM: loader chaining
        # Subtest: should load unadulterated source when there are no loaders
        ok 1 - should load unadulterated source when there are no loaders
          ---
          duration_ms: 632.2352
          ...

```
</details>

-------

| Reason | <code>es-module/test-esm-loader-event-loop</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58680/](https://ci.nodejs.org/job/node-test-pull-request/67867/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67868/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/67873/), [https://github.com/nodejs/node/pull/58948/](https://ci.nodejs.org/job/node-test-pull-request/67878/), [https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67881/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2019/35271/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67867/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67881/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2019/35271/console">Example</a></summary>

```
not ok 38 es-module/test-esm-loader-event-loop
  ---
  duration_ms: 1015.97800
  severity: crashed
  exitcode: 3221225725
  stack: |-
    (node:3444) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
    --import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("./test/fixtures/es-module-loaders/hooks-custom.mjs", pathToFileURL("./"));'
    (Use `node --trace-warnings ...` to show where the warning was created)
  ...

```
</details>

-------

| Reason | <code>es-module/test-esm-loader-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58960/](https://ci.nodejs.org/job/node-test-pull-request/67848/), [https://github.com/nodejs/node/pull/58961/](https://ci.nodejs.org/job/node-test-pull-request/67850/), [https://github.com/nodejs/node/pull/58940/](https://ci.nodejs.org/job/node-test-pull-request/67851/), [https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67862/), [https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67863/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/35263/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67848/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67863/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/35263/console">Example</a></summary>

```
not ok 848 es-module/test-esm-loader-hooks
  ---
  duration_ms: 120318.79500
  severity: fail
  exitcode: 1
  stack: |-
    timeout
    TAP version 13
    # Subtest: Loader hooks
        # Subtest: are called with all expected arguments
        ok 1 - are called with all expected arguments
          ---
          duration_ms: 1101.8434
          ...

```
</details>

-------

| Reason | <code>es-module/test-esm-loader-not-found</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58680/](https://ci.nodejs.org/job/node-test-pull-request/67867/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67868/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/67873/), [https://github.com/nodejs/node/pull/58948/](https://ci.nodejs.org/job/node-test-pull-request/67878/), [https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67881/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2019/35271/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67867/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67881/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2019/35271/console">Example</a></summary>

```
not ok 39 es-module/test-esm-loader-not-found
  ---
  duration_ms: 1065.07000
  severity: fail
  exitcode: 1
  stack: |-
    node:os:223
      const data = getInterfaceAddresses();
                   ^
    
    SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 2 (Unknown system error 2)
        at Object.networkInterfaces (node:os:223:16)
        at get hasIPv6 [as hasIPv6] (c:\workspace\node-test-binary-windows-js-suites\node\test\common\index.js:1003:34)
        at Object.get (c:\workspace\node-test-binary-windows-js-suites\node\test\common\index.js:1113:15)
        at file:///c:/workspace/node-test-binary-windows-js-suites/node/test/common/index.mjs:22:3
        at ModuleJob.run (node:internal/modules/esm/module_job:263:25)
        at async ModuleLoader.import (node:internal/modules/esm/loader:540:24)
        at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
      code: 'ERR_SYSTEM_ERROR',
      info: {
        errn...
```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-range</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58960/](https://ci.nodejs.org/job/node-test-pull-request/67848/), [https://github.com/nodejs/node/pull/58961/](https://ci.nodejs.org/job/node-test-pull-request/67850/), [https://github.com/nodejs/node/pull/58940/](https://ci.nodejs.org/job/node-test-pull-request/67851/), [https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67862/), [https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67863/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/35263/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67848/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67863/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/35263/console">Example</a></summary>

```
not ok 102 parallel/test-buffer-tostring-range
  ---
  duration_ms: 189.01100
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/buffer:961
        super(bufferOrLength, byteOffset, length);
        ^
    
    RangeError: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at new Uint8Array (<anonymous>)
        at new FastBuffer (node:internal/buffer:961:5)
        at Function.alloc (node:buffer:397:10)
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-buffer-tostring-range.js:107:28)
        at Module._compile (node:internal/modules/cjs/loader:1529:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
        at Module.load (node:internal/modules/cjs/loader:1275:32)
        at Module._load (node:internal/modules/cjs/loader:1096:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    
    Node.js v20.19.4-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-string-decoder</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58680/](https://ci.nodejs.org/job/node-test-pull-request/67867/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67868/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/67873/), [https://github.com/nodejs/node/pull/58948/](https://ci.nodejs.org/job/node-test-pull-request/67878/), [https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67881/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2019/35271/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67867/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67881/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2019/35271/console">Example</a></summary>

```
not ok 758 parallel/test-string-decoder
  ---
  duration_ms: 176.01300
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:377
          throw err;
          ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
    + Comparison {}
    - Comparison {
    -   code: 'ERR_STRING_TOO_LONG'
    - }
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-string-decoder.js:205:10)
        at Module._compile (node:internal/modules/cjs/loader:1529:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
        at Module.load (node:internal/modules/cjs/loader:1275:32)
        at Module._load (node:internal/modules/cjs/loader:1096:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
        at node:internal/main/run_main_module:28:49 {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: RangeError: Array buffer alloc...
```
</details>

-------

| Reason | <code>sequential/test-child-process-pass-fd</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58077/](https://ci.nodejs.org/job/node-test-pull-request/67839/), [https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67843/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/67859/), [https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67862/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67868/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/35275/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67839/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67868/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/35275/console">Example</a></summary>

```
not ok 1047 sequential/test-child-process-pass-fd
  ---
  duration_ms: 120255.03700
  severity: fail
  exitcode: 1
  stack: |-
    timeout
    
    
    #
    # Fatal process out of memory: Re-embedded builtins: set permissions
    #
    ----- Native stack trace -----
    
     1: 00007FF7A376AF5D 
     2: 00007FF7A4A76136 
     3: 00007FF7A4440916 
     4: 00007FF7A42A8CCE 
     5: 00007FF7A42DC0FF 
     6: 00007FF7A42DCBB2 
     7: 00007FF7A42DD582 
     8: 00007FF7A3DD9BC3 
     9: 00007FF7A446B946 
    10: 00007FF7A390F9FD 
    11: 00007FF7A37A25CE 
    12: 00007FF7A3861864 
    13: 00007FF7A4749CF2 
    14: 00007FF7A5599FF4 
    15: 00007FFE8E19257D 
    16: 00007FFE8F20AF08 
    [low_level_alloc.cc : 554] RAW: Check new_pages != nullptr failed: VirtualAlloc failed
    [low_level_alloc.cc : 554] RAW: Check new_pages != nullptr failed: VirtualAlloc failed
    [low_level_alloc.cc : 554] RAW: Check new_pages != nullptr failed: VirtualAlloc failed
    [low_level_alloc.cc : 554] RAW: Check new_pages != nullpt...
```
</details>

-------

| Reason | <code>parallel/test-worker-message-port-transfer-filehandle</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58713/](https://ci.nodejs.org/job/node-test-pull-request/67805/), [https://github.com/nodejs/node/pull/58952/](https://ci.nodejs.org/job/node-test-pull-request/67828/), [https://github.com/nodejs/node/pull/57298/](https://ci.nodejs.org/job/node-test-pull-request/67830/), [https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67881/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35295/console), [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35213/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35194/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67805/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67881/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35295/console">Example</a></summary>

```
not ok 982 parallel/test-worker-message-port-transfer-filehandle
  ---
  duration_ms: 266.00100
  severity: fail
  exitcode: 1
  stack: |-
    <anonymous_script>:0
    
    
    [Error: A FileHandle object was closed during garbage collection. This used to be allowed with a deprecation warning but is now considered an error. Please close FileHandle objects explicitly.] {
      code: 'ERR_INVALID_STATE'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>wpt/test-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58680/](https://ci.nodejs.org/job/node-test-pull-request/67867/), [https://github.com/nodejs/node/pull/58952/](https://ci.nodejs.org/job/node-test-pull-request/67877/), [https://github.com/nodejs/node/pull/58976/](https://ci.nodejs.org/job/node-test-pull-request/67884/), [https://github.com/nodejs/node/pull/58993/](https://ci.nodejs.org/job/node-test-pull-request/67888/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58035/console), [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58019/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67867/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67888/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58035/console">Example</a></summary>

```
not ok 4571 wpt/test-streams
  ---
  duration_ms: 1380.09900
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] queuing-strategies-size-function-per-global.window.js: Browser-specific test
    [SKIPPED] readable-streams/cross-realm-crash.window.js: Browser-specific test
    [SKIPPED] readable-streams/owning-type-video-frame.any.js: Browser-specific test
    [SKIPPED] readable-streams/read-task-handling.window.js: Browser-specific test
    [SKIPPED] transferable/deserialize-error.window.js: Browser-specific test
    [SKIPPED] transferable/transfer-with-messageport.window.js: Browser-specific test
    [SKIPPED] transform-streams/invalid-realm.tentative.window.js: Browser-specific test
    [PASS] Closing must be propagated backward: starts closed; preventCancel omitted; fulfilled cancel promise
    [PASS] Closing must be propagated backward: starts closed; preventCancel omitted; rejected cancel promise
    [PASS] Closing must be propagated backward: starts closed; preventCancel = undefined (falsy); ful...
```
</details>

-------

| Reason | <code>es-module/test-esm-loader-default-resolver</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58960/](https://ci.nodejs.org/job/node-test-pull-request/67848/), [https://github.com/nodejs/node/pull/58961/](https://ci.nodejs.org/job/node-test-pull-request/67850/), [https://github.com/nodejs/node/pull/58940/](https://ci.nodejs.org/job/node-test-pull-request/67851/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/35242/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67848/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67851/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/35242/console">Example</a></summary>

```
not ok 39 es-module/test-esm-loader-default-resolver
  ---
  duration_ms: 3715.25000
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: default resolver
        # Subtest: should accept foreign schemas without exception (e.g. byop://something/or-other)
        ok 1 - should accept foreign schemas without exception (e.g. byop://something/or-other)
          ---
          duration_ms: 550.44
          ...

```
</details>

-------

| Reason | <code>es-module/test-vm-contextified-script-leak</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58940/](https://ci.nodejs.org/job/node-test-pull-request/67851/), [https://github.com/nodejs/node/pull/58680/](https://ci.nodejs.org/job/node-test-pull-request/67867/), [https://github.com/nodejs/node/pull/58977/](https://ci.nodejs.org/job/node-test-pull-request/67892/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35310/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35244/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67851/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67892/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35310/console">Example</a></summary>

```
not ok 65 es-module/test-vm-contextified-script-leak
  ---
  duration_ms: 308.01300
  severity: crashed
  exitcode: 3221225477
  stack: |-
    Created 128 objects
    Created 256 objects
    Found finalized object at 290, stop testing
  ...

```
</details>

-------

| Reason | <code>report/test-report-worker</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58960/](https://ci.nodejs.org/job/node-test-pull-request/67848/), [https://github.com/nodejs/node/pull/58961/](https://ci.nodejs.org/job/node-test-pull-request/67850/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/67873/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/35288/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/35288/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022_clang/35288/console), [test-rackspace-win2022_vs2022-x64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/35288/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35288/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19262/console), [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/35258/console), [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/35258/console), [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022_clang/35258/console), [test-rackspace-win2022_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/35258/console), [test-azure_msft-win11_vs2022-arm64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35258/console), [test-rackspace-win2019_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022_clang/35251/console), [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/35251/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/35239/console), [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/35239/console), [test-equinix-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19240/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/35224/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67848/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67873/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/35288/console">Example</a></summary>

```
not ok 1020 report/test-report-worker
  ---
  duration_ms: 334.00400
  severity: crashed
  exitcode: 3221225477
  stack: |-
  ...

```
</details>

-------

| Reason | <code>parallel/test-fs-cp</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58121/](https://ci.nodejs.org/job/node-test-pull-request/67846/), [https://github.com/nodejs/node/pull/58997/](https://ci.nodejs.org/job/node-test-pull-request/67891/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51602/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51549/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67846/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67891/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51602/console">Example</a></summary>

```
not ok 907 parallel/test-fs-cp
  ---
  duration_ms: 251.53400
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/modules/run_main:105
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    
    + 1752007454236
    - 1752007454235
                  ^
    
        at file:///home/iojs/build/workspace/node-test-commit-linux-containered/test/parallel/test-fs-cp.mjs:531:10 {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 1752007454236,
      expected: 1752007454235,
      operator: 'strictEqual'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-process-threadCpuUsage-worker-threads</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67863/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67868/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/35275/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67863/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67868/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/35275/console">Example</a></summary>

```
not ok 681 parallel/test-process-threadCpuUsage-worker-threads
  ---
  duration_ms: 439.02600
  severity: fail
  exitcode: 1
  stack: |-
    
    node:internal/event_target:1101
      process.nextTick(() => { throw err; });
                               ^
    RangeError [Error]: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at new Uint8Array (<anonymous>)
        at new FastBuffer (node:internal/buffer:968:5)
        at randomBytes (node:internal/crypto/random:104:15)
        at performLoad (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-process-threadCpuUsage-worker-threads.js:25:18)
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-process-threadCpuUsage-worker-threads.js:91:18)
        at Module._compile (node:internal/modules/cjs/loader:1692:14)
        at Object..js (node:internal/modules/cjs/loader:1824:10)
        at Module.load (node:internal/modules/cjs/loader:1427:32)
        at Module._l...
```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67860/), [https://github.com/nodejs/node/pull/58957/](https://ci.nodejs.org/job/node-test-pull-request/67872/)) |
| Appeared | [vm-b2wp4](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65843/console), [vm-2wfdk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65832/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67860/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67872/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65843/console">Example</a></summary>

```
not ok 2683 parallel/test-runner-run-watch
  ---
  duration_ms: 33404.19900
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should recalculate the run duration on a watch restart'
    Location: test/parallel/test-runner-run-watch.mjs:251:3
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 1/. Input:
    
    '# Subtest: test has ran\n' +
      'ok 1 - test has ran\n' +
      '  ---\n' +
      '  duration_ms: 7.310867\n' +
      "  type: 'test'\n" +
      '  ...\n' +
      '# Subtest: test.js\n' +
      'not ok 2 - test.js\n' +
      '  ---\n' +
      '  duration_ms: 1054.811866\n' +
      "  type: 'test'\n" +
      "  location: '/Users/admin/node-tmp/.tmp.2630/test.js:1:1'\n" +
      "  failureType: 'testCodeFailure'\n" +
      '  exitCode: ~\n' +
      "  signal: 'SIGTERM'\n" +
      "  error: 'test failed'\n" +
      "  code: 'ERR_TEST_FAILURE'\n" +
      '  ...\n' +
      '# Subtest: test has ran\n' +
      'ok 3 - test has ran\n' +
      '  ---\n' +
  ...
```
</details>

-------

| Reason | <code>parallel/test-stream-readable-to-web</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58938/](https://ci.nodejs.org/job/node-test-pull-request/67799/), [https://github.com/nodejs/node/pull/58948/](https://ci.nodejs.org/job/node-test-pull-request/67822/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51526/console), [test-osuosl-rhel9-ppc64_le-4](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/59740/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67799/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67822/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51526/console">Example</a></summary>

```
not ok 2847 parallel/test-stream-readable-to-web
  ---
  duration_ms: 119.22600
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/util:234
        throw new ERR_NO_CRYPTO();
              ^
    
    Error [ERR_NO_CRYPTO]: Node.js is not compiled with OpenSSL crypto support
        at assertCrypto (node:internal/util:234:11)
        at node:crypto:36:1
        at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:398:7)
        at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:337:10)
        at loadBuiltinModule (node:internal/modules/helpers:109:7)
        at ModuleLoader.builtinStrategy (node:internal/modules/esm/translators:417:18)
        at #translate (node:internal/modules/esm/loader:546:12)
        at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:593:27)
        at async #link (node:internal/modules/esm/module_job:180:19) {
      code: 'ERR_NO_CRYPTO'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-url-parse-invalid-input</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67862/), [https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67863/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/35263/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67862/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67863/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/35263/console">Example</a></summary>

```
not ok 850 parallel/test-url-parse-invalid-input
  ---
  duration_ms: 3029.19900
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/child_process:420
        throw new ErrnoException(err, 'spawn');
        ^
    
    Error: spawn UNKNOWN
        at ChildProcess.spawn (node:internal/child_process:420:11)
        at spawn (node:child_process:762:9)
        at Proxy.spawnPromisified (c:\workspace\node-test-binary-windows-js-suites\node\test\common\index.js:858:17)
        at c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-url-parse-invalid-input.js:84:12
        at Array.forEach (<anonymous>)
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-url-parse-invalid-input.js:83:11)
        at Module._compile (node:internal/modules/cjs/loader:1529:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
        at Module.load (node:internal/modules/cjs/loader:1275:32)
        at Module._load (node:internal/modu...
```
</details>

-------

| Reason | <code>parallel/test-v8-coverage</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58973/](https://ci.nodejs.org/job/node-test-pull-request/67862/), [https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67863/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/35263/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67862/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67863/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/35263/console">Example</a></summary>

```
not ok 849 parallel/test-v8-coverage
  ---
  duration_ms: 2036.13700
  severity: fail
  exitcode: 1
  stack: |-
    
    node:assert:90
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    3221225773 !== 0
    
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-v8-coverage.js:125:10)
        at Module._compile (node:internal/modules/cjs/loader:1529:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
        at Module.load (node:internal/modules/cjs/loader:1275:32)
        at Module._load (node:internal/modules/cjs/loader:1096:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
        at node:internal/main/run_main_module:28:49 {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 3221225773,
      expected: 0,
      operator: 'strictEqual'
    }
    
    Node.js v20.19.4-pre
  ...

```
</details>

-------

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58952/](https://ci.nodejs.org/job/node-test-pull-request/67828/), [https://github.com/nodejs/node/pull/58978/](https://ci.nodejs.org/job/node-test-pull-request/67890/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51601/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67828/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67890/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51601/console">Example</a></summary>

```
not ok 4514 sequential/test-tls-session-timeout
  ---
  duration_ms: 266.17800
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:92
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at /home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:150:16
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:134:7)
        at ChildProcess.emit (node:events:507:28)
        at ChildProcess._handle.onexit (node:internal/child_process:293:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

