Failures in [node-test-pull-request/67498](https://ci.nodejs.org/job/node-test-pull-request/67498/) to [node-test-pull-request/67595](https://ci.nodejs.org/job/node-test-pull-request/67595/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-06-22.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-06-22 00:13 | 0       | 1       | 21       | 5       | 73      | 1.05%      |


### JSTest Failure

| Reason | <code>pummel/test-string-decoder-large-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 17 ([https://github.com/nodejs/node/pull/58616/](https://ci.nodejs.org/job/node-test-pull-request/67503/), [https://github.com/nodejs/node/pull/58734/](https://ci.nodejs.org/job/node-test-pull-request/67504/), [https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/67505/), [https://github.com/nodejs/node/pull/58573/](https://ci.nodejs.org/job/node-test-pull-request/67512/), [https://github.com/nodejs/node/pull/58719/](https://ci.nodejs.org/job/node-test-pull-request/67518/), [https://github.com/nodejs/node/pull/58588/](https://ci.nodejs.org/job/node-test-pull-request/67555/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67563/), [https://github.com/nodejs/node/pull/58749/](https://ci.nodejs.org/job/node-test-pull-request/67564/), [https://github.com/nodejs/node/pull/58691/](https://ci.nodejs.org/job/node-test-pull-request/67566/), [https://github.com/nodejs/node/pull/58715/](https://ci.nodejs.org/job/node-test-pull-request/67568/), [https://github.com/nodejs/node/pull/58697/](https://ci.nodejs.org/job/node-test-pull-request/67571/), [https://github.com/nodejs/node/pull/58536/](https://ci.nodejs.org/job/node-test-pull-request/67581/), [https://github.com/nodejs/node/pull/58712/](https://ci.nodejs.org/job/node-test-pull-request/67583/), [https://github.com/nodejs/node/pull/58765/](https://ci.nodejs.org/job/node-test-pull-request/67588/), [https://github.com/nodejs/node/pull/58711/](https://ci.nodejs.org/job/node-test-pull-request/67589/), [https://github.com/nodejs/node/pull/57688/](https://ci.nodejs.org/job/node-test-pull-request/67590/), [https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/67591/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/34950/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67503/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67591/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/34950/console">Example</a></summary>

```
not ok 974 pummel/test-string-decoder-large-buffer
  ---
  duration_ms: 140.02600
  severity: fail
  exitcode: 1
  stack: |-
    c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-string-decoder-large-buffer.js:26
        throw e;
        ^
    
    RangeError: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at new Uint8Array (<anonymous>)
        at new FastBuffer (node:internal/buffer:961:5)
        at createUnsafeBuffer (node:internal/buffer:1064:12)
        at allocate (node:buffer:441:10)
        at Function.allocUnsafe (node:buffer:406:10)
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-string-decoder-large-buffer.js:21:22)
        at Module._compile (node:internal/modules/cjs/loader:1529:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
        at Module.load (node:internal/modules/cjs/loader:1275:32)
    
    Node.js v20.19.3-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-config-file</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 16 ([https://github.com/nodejs/node/pull/58719/](https://ci.nodejs.org/job/node-test-pull-request/67518/), [https://github.com/nodejs/node/pull/58697/](https://ci.nodejs.org/job/node-test-pull-request/67525/), [https://github.com/nodejs/node/pull/58749/](https://ci.nodejs.org/job/node-test-pull-request/67529/), [https://github.com/nodejs/node/pull/58758/](https://ci.nodejs.org/job/node-test-pull-request/67530/), [https://github.com/nodejs/node/pull/58760/](https://ci.nodejs.org/job/node-test-pull-request/67536/), [https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/67549/), [https://github.com/nodejs/node/pull/58678/](https://ci.nodejs.org/job/node-test-pull-request/67550/), [https://github.com/nodejs/node/pull/58715/](https://ci.nodejs.org/job/node-test-pull-request/67551/), [https://github.com/nodejs/node/pull/58588/](https://ci.nodejs.org/job/node-test-pull-request/67555/), [https://github.com/nodejs/node/pull/58767/](https://ci.nodejs.org/job/node-test-pull-request/67559/), [https://github.com/nodejs/node/pull/58691/](https://ci.nodejs.org/job/node-test-pull-request/67560/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67563/), [https://github.com/nodejs/node/pull/58765/](https://ci.nodejs.org/job/node-test-pull-request/67588/), [https://github.com/nodejs/node/pull/58711/](https://ci.nodejs.org/job/node-test-pull-request/67589/), [https://github.com/nodejs/node/pull/57688/](https://ci.nodejs.org/job/node-test-pull-request/67590/), [https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/67591/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/34949/console), [test-azure_msft-win11_vs2022-arm64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34924/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/34883/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67518/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67591/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/34949/console">Example</a></summary>

```
not ok 228 parallel/test-config-file
  ---
  duration_ms: 4215.14300
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: '--inspect=true should be parsed correctly'
    Location: test\parallel\test-config-file.js:237:1
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /^Debugger listening on (ws:\/\/[^\s]+)/. Input:
    
    'Starting inspector on 127.0.0.1:9229 failed: address already in use\r\n'
    
        at TestContext.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-config-file.js:244:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Test.run (node:internal/test_runner/test:1054:7)
        at async Test.processPendingSubtests (node:internal/test_runner/test:744:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'Starting inspector on 127.0.0.1:9229 failed: address already in use\r\n',
      expected: /^Debugger listening on (ws:\/\/[^\s]+)/,
 ...
```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-range</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/58616/](https://ci.nodejs.org/job/node-test-pull-request/67503/), [https://github.com/nodejs/node/pull/58734/](https://ci.nodejs.org/job/node-test-pull-request/67504/), [https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/67505/), [https://github.com/nodejs/node/pull/58573/](https://ci.nodejs.org/job/node-test-pull-request/67512/), [https://github.com/nodejs/node/pull/58719/](https://ci.nodejs.org/job/node-test-pull-request/67518/), [https://github.com/nodejs/node/pull/58588/](https://ci.nodejs.org/job/node-test-pull-request/67556/), [https://github.com/nodejs/node/pull/58765/](https://ci.nodejs.org/job/node-test-pull-request/67588/), [https://github.com/nodejs/node/pull/58711/](https://ci.nodejs.org/job/node-test-pull-request/67589/), [https://github.com/nodejs/node/pull/57688/](https://ci.nodejs.org/job/node-test-pull-request/67590/), [https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/67591/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/34950/console), [test-digitalocean-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/65243/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67503/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67591/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/34950/console">Example</a></summary>

```
not ok 105 parallel/test-buffer-tostring-range
  ---
  duration_ms: 204.01400
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/buffer:961
        super(bufferOrLength, byteOffset, length);
        ^
    
    RangeError: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at new Uint8Array (<anonymous>)
        at new FastBuffer (node:internal/buffer:961:5)
        at Function.alloc (node:buffer:397:10)
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-buffer-tostring-range.js:107:28)
        at Module._compile (node:internal/modules/cjs/loader:1529:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
        at Module.load (node:internal/modules/cjs/loader:1275:32)
        at Module._load (node:internal/modules/cjs/loader:1096:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    
    Node.js v20.19.3-pre
  ...

```
</details>

-------

| Reason | <code>pummel/test-buffer-large-size-buffer-alloc-unsafe</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/58734/](https://ci.nodejs.org/job/node-test-pull-request/67504/), [https://github.com/nodejs/node/pull/58765/](https://ci.nodejs.org/job/node-test-pull-request/67535/), [https://github.com/nodejs/node/pull/58760/](https://ci.nodejs.org/job/node-test-pull-request/67536/), [https://github.com/nodejs/node/pull/58767/](https://ci.nodejs.org/job/node-test-pull-request/67540/), [https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/67549/), [https://github.com/nodejs/node/pull/58715/](https://ci.nodejs.org/job/node-test-pull-request/67551/), [https://github.com/nodejs/node/pull/57688/](https://ci.nodejs.org/job/node-test-pull-request/67582/), [https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/67591/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/34955/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67504/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67591/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/34955/console">Example</a></summary>

```
not ok 1026 pummel/test-buffer-large-size-buffer-alloc-unsafe
  ---
  duration_ms: 171.11300
  severity: fail
  exitcode: 1
  stack: |-
    c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-buffer-large-size-buffer-alloc-unsafe.js:15
        throw e;
        ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
    + Comparison {}
    - Comparison {
    -   code: 'ERR_STRING_TOO_LONG'
    - }
    
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-buffer-large-size-buffer-alloc-unsafe.js:12:10)
        at Module._compile (node:internal/modules/cjs/loader:1691:14)
        at Object..js (node:internal/modules/cjs/loader:1823:10)
        at Module.load (node:internal/modules/cjs/loader:1426:32)
        at Module._load (node:internal/modules/cjs/loader:1249:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/lo...
```
</details>

-------

| Reason | <code>pummel/test-buffer-large-size-buffer-write</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/58758/](https://ci.nodejs.org/job/node-test-pull-request/67530/), [https://github.com/nodejs/node/pull/58678/](https://ci.nodejs.org/job/node-test-pull-request/67550/), [https://github.com/nodejs/node/pull/58588/](https://ci.nodejs.org/job/node-test-pull-request/67555/), [https://github.com/nodejs/node/pull/58767/](https://ci.nodejs.org/job/node-test-pull-request/67559/), [https://github.com/nodejs/node/pull/58749/](https://ci.nodejs.org/job/node-test-pull-request/67564/), [https://github.com/nodejs/node/pull/58691/](https://ci.nodejs.org/job/node-test-pull-request/67566/), [https://github.com/nodejs/node/pull/58765/](https://ci.nodejs.org/job/node-test-pull-request/67588/), [https://github.com/nodejs/node/pull/58711/](https://ci.nodejs.org/job/node-test-pull-request/67589/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/34952/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67530/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67589/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/34952/console">Example</a></summary>

```
not ok 1024 pummel/test-buffer-large-size-buffer-write
  ---
  duration_ms: 126.85200
  severity: fail
  exitcode: 1
  stack: |-
    c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-buffer-large-size-buffer-write.js:19
        throw e;
        ^
    
    RangeError: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at new Uint8Array (<anonymous>)
        at new FastBuffer (node:internal/buffer:968:5)
        at Buffer.alloc (node:buffer:399:10)
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-buffer-large-size-buffer-write.js:14:22)
        at Module._compile (node:internal/modules/cjs/loader:1691:14)
        at Object..js (node:internal/modules/cjs/loader:1823:10)
        at Module.load (node:internal/modules/cjs/loader:1426:32)
        at Module._load (node:internal/modules/cjs/loader:1249:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-npm-install</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58697/](https://ci.nodejs.org/job/node-test-pull-request/67571/), [https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/67576/), [https://github.com/nodejs/node/pull/58536/](https://ci.nodejs.org/job/node-test-pull-request/67581/), [https://github.com/nodejs/node/pull/58765/](https://ci.nodejs.org/job/node-test-pull-request/67588/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/34951/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67571/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67588/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/34951/console">Example</a></summary>

```
not ok 740 parallel/test-npm-install
  ---
  duration_ms: 132740.09300
  severity: fail
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>pummel/test-buffer-large-size-buffer-alloc</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58616/](https://ci.nodejs.org/job/node-test-pull-request/67498/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/67563/), [https://github.com/nodejs/node/pull/58712/](https://ci.nodejs.org/job/node-test-pull-request/67583/), [https://github.com/nodejs/node/pull/58711/](https://ci.nodejs.org/job/node-test-pull-request/67584/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/34945/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67498/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67584/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/34945/console">Example</a></summary>

```
not ok 1024 pummel/test-buffer-large-size-buffer-alloc
  ---
  duration_ms: 127.00800
  severity: fail
  exitcode: 1
  stack: |-
    c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-buffer-large-size-buffer-alloc.js:15
        throw e;
        ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
    + Comparison {}
    - Comparison {
    -   code: 'ERR_STRING_TOO_LONG'
    - }
    
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-buffer-large-size-buffer-alloc.js:12:10)
        at Module._compile (node:internal/modules/cjs/loader:1691:14)
        at Object..js (node:internal/modules/cjs/loader:1823:10)
        at Module.load (node:internal/modules/cjs/loader:1426:32)
        at Module._load (node:internal/modules/cjs/loader:1249:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
        ...
```
</details>

-------

| Reason | <code>pummel/test-buffer-large-size-buffer-alloc-unsafe-slow</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58573/](https://ci.nodejs.org/job/node-test-pull-request/67512/), [https://github.com/nodejs/node/pull/58719/](https://ci.nodejs.org/job/node-test-pull-request/67517/), [https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/67524/), [https://github.com/nodejs/node/pull/58715/](https://ci.nodejs.org/job/node-test-pull-request/67544/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/34905/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67512/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67544/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/34905/console">Example</a></summary>

```
not ok 1028 pummel/test-buffer-large-size-buffer-alloc-unsafe-slow
  ---
  duration_ms: 173.01000
  severity: fail
  exitcode: 1
  stack: |-
    c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-buffer-large-size-buffer-alloc-unsafe-slow.js:15
        throw e;
        ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
    + Comparison {}
    - Comparison {
    -   code: 'ERR_STRING_TOO_LONG'
    - }
    
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-buffer-large-size-buffer-alloc-unsafe-slow.js:12:10)
        at Module._compile (node:internal/modules/cjs/loader:1691:14)
        at Object..js (node:internal/modules/cjs/loader:1823:10)
        at Module.load (node:internal/modules/cjs/loader:1426:32)
        at Module._load (node:internal/modules/cjs/loader:1249:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal...
```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58645/](https://ci.nodejs.org/job/node-test-pull-request/67527/), [https://github.com/nodejs/node/pull/58588/](https://ci.nodejs.org/job/node-test-pull-request/67558/), [https://github.com/nodejs/node/pull/58758/](https://ci.nodejs.org/job/node-test-pull-request/67570/), [https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/67595/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51321/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51300/console), [test-linuxonecc-rhel9-s390x-3](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50150/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50148/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51283/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51275/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67527/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67595/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51321/console">Example</a></summary>

```
not ok 4470 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 7329.60300
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-fs-watch-recursive-delete</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/67505/), [https://github.com/nodejs/node/pull/58719/](https://ci.nodejs.org/job/node-test-pull-request/67507/), [https://github.com/nodejs/node/pull/58588/](https://ci.nodejs.org/job/node-test-pull-request/67556/)) |
| Appeared | [test-digitalocean-fedora40-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/65243/console), [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/34857/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67505/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67556/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/65243/console">Example</a></summary>

```
not ok 1286 parallel/test-fs-watch-recursive-delete
  ---
  duration_ms: 709.55400
  severity: fail
  exitcode: 1
  stack: |-
    node:events:502
          throw er; // Unhandled 'error' event
          ^
    
    Error: ENOENT: no such file or directory, scandir '/home/iojs/node-tmp/.tmp.1285/parent/child'
        at readdirSync (node:fs:1507:26)
        at #watchFolder (node:internal/fs/recursive_watch:111:21)
        at FSWatcher.<anonymous> (node:internal/fs/recursive_watch:191:26)
        at FSWatcher.emit (node:events:524:28)
        at FSWatcher._handle.onchange (node:internal/fs/watchers:215:12)
    Emitted 'error' event on FSWatcher instance at:
        at #watchFolder (node:internal/fs/recursive_watch:143:12)
        at FSWatcher.<anonymous> (node:internal/fs/recursive_watch:191:26)
        at FSWatcher.emit (node:events:524:28)
        at FSWatcher._handle.onchange (node:internal/fs/watchers:215:12) {
      errno: -2,
      code: 'ENOENT',
      syscall: 'scandir',
      path: '/home/iojs/node-tmp/...
```
</details>

-------

| Reason | <code>pummel/test-buffer-large-size-slowbuffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58719/](https://ci.nodejs.org/job/node-test-pull-request/67517/), [https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/67524/), [https://github.com/nodejs/node/pull/58715/](https://ci.nodejs.org/job/node-test-pull-request/67544/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/34905/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67517/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67544/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/34905/console">Example</a></summary>

```
not ok 1029 pummel/test-buffer-large-size-slowbuffer
  ---
  duration_ms: 156.01300
  severity: fail
  exitcode: 1
  stack: |-
    c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-buffer-large-size-slowbuffer.js:19
        throw e;
        ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
    + Comparison {}
    - Comparison {
    -   code: 'ERR_STRING_TOO_LONG'
    - }
    
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-buffer-large-size-slowbuffer.js:14:10)
        at Module._compile (node:internal/modules/cjs/loader:1691:14)
        at Object..js (node:internal/modules/cjs/loader:1823:10)
        at Module.load (node:internal/modules/cjs/loader:1426:32)
        at Module._load (node:internal/modules/cjs/loader:1249:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
        at Mod...
```
</details>

-------

| Reason | <code>wpt/test-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58573/](https://ci.nodejs.org/job/node-test-pull-request/67512/), [https://github.com/nodejs/node/pull/58691/](https://ci.nodejs.org/job/node-test-pull-request/67528/), [https://github.com/nodejs/node/pull/58646/](https://ci.nodejs.org/job/node-test-pull-request/67585/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57809/console), [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57781/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67512/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67585/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57809/console">Example</a></summary>

```
not ok 4550 wpt/test-streams
  ---
  duration_ms: 1272.86100
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] queuing-strategies-size-function-per-global.window.js: Browser-specific test
    [SKIPPED] readable-streams/cross-realm-crash.window.js: Browser-specific test
    [SKIPPED] readable-streams/owning-type-video-frame.any.js: Browser-specific test
    [SKIPPED] readable-streams/read-task-handling.window.js: Browser-specific test
    [SKIPPED] transferable/deserialize-error.window.js: Browser-specific test
    [SKIPPED] transferable/transfer-with-messageport.window.js: Browser-specific test
    [SKIPPED] transform-streams/invalid-realm.tentative.window.js: Browser-specific test
    [PASS] Closing must be propagated backward: starts closed; preventCancel omitted; fulfilled cancel promise
    [PASS] Closing must be propagated backward: starts closed; preventCancel omitted; rejected cancel promise
    [PASS] Closing must be propagated backward: starts closed; preventCancel = undefined (falsy); ful...
```
</details>

-------

| Reason | <code>es-module/test-vm-contextified-script-leak</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58616/](https://ci.nodejs.org/job/node-test-pull-request/67503/), [https://github.com/nodejs/node/pull/58678/](https://ci.nodejs.org/job/node-test-pull-request/67526/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34885/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67503/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67526/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34885/console">Example</a></summary>

```
not ok 65 es-module/test-vm-contextified-script-leak
  ---
  duration_ms: 277.00500
  severity: crashed
  exitcode: 3221225477
  stack: |-
    Created 128 objects
    Created 256 objects
    Found finalized object at 310, stop testing
  ...

```
</details>

-------

| Reason | <code>parallel/test-esm-loader-hooks-inspect-wait</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58588/](https://ci.nodejs.org/job/node-test-pull-request/67556/), [https://github.com/nodejs/node/pull/57688/](https://ci.nodejs.org/job/node-test-pull-request/67590/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022_clang/34953/console), [test-digitalocean-freebsd13-x64-1](https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd13-x64/60687/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67556/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67590/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022_clang/34953/console">Example</a></summary>

```
not ok 290 parallel/test-esm-loader-hooks-inspect-wait
  ---
  duration_ms: 2085.70100
  severity: fail
  exitcode: 1
  stack: |-
    [test] Connecting to a child Node process
    [test] Testing /json/list
    [err] Debugger listening on ws://127.0.0.1:60501/34ce2494-3094-426b-8eab-6928455e78d0
    [err] For help, see: https://nodejs.org/en/docs/inspector
    [err] 
    [err] Debugger attached.
    [err] 
    [err] Waiting for the debugger to disconnect...
    [err] 
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    3221225477 !== 0
    
        at runTest (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-esm-loader-hooks-inspect-wait.js:27:10)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 3221225477,
      expected: 0,
      operator: 'strictEqual'
    }
    1
  ...

```
</details>

-------

| Reason | <code>parallel/test-fs-write-buffer-large</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/67505/), [https://github.com/nodejs/node/pull/58719/](https://ci.nodejs.org/job/node-test-pull-request/67507/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/34857/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67505/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67507/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/34857/console">Example</a></summary>

```
not ok 355 parallel/test-fs-write-buffer-large
  ---
  duration_ms: 144.00700
  severity: fail
  exitcode: 3221226505
  stack: |-
  ...

```
</details>

-------

| Reason | <code>parallel/test-fs-write-file-invalid-path</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/67505/), [https://github.com/nodejs/node/pull/58719/](https://ci.nodejs.org/job/node-test-pull-request/67507/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/34857/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67505/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67507/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/34857/console">Example</a></summary>

```
not ok 356 parallel/test-fs-write-file-invalid-path
  ---
  duration_ms: 107.00700
  severity: crashed
  exitcode: 2147483651
  stack: |-
    
    <--- Last few GCs --->
    
    
    
    #
    # Fatal JavaScript out of memory: MemoryChunk allocation failed during deserialization.
    #
    ----- Native stack trace -----
    
     1: 00007FF6B752CA1D 
     2: 00007FF6B8852A26 
     3: 00007FF6B82195A6 
     4: 00007FF6B8018FF7 
     5: 00007FF6B7FCBA4A 
     6: 00007FF6B7FCBB0C 
     7: 00007FF6B7FCC3EB 
     8: 00007FF6B7F9F911 
     9: 00007FF6B8009503 
    10: 00007FF6B800926E 
    11: 00007FF6B8008088 
    12: 00007FF6B800800A 
    13: 00007FF6B7BC68D3 
    14: 00007FF6B7BC473C 
    15: 00007FF6B7BCA376 
    16: 00007FF6B7BC5428 
    17: 00007FF6B7BC491E 
    18: 00007FF6B7BCA376 
    19: 00007FF6B7BC5428 
    20: 00007FF6B7BC491E 
    21: 00007FF6B7BCA376 
    22: 00007FF6B7BC5428 
    23: 00007FF6B7BC491E 
    24: 00007FF6B7BCA376 
    25: 00007FF6B7BC5428 
    26: 00007FF6B7BC491E 
    27: 00007FF6B7B...
```
</details>

-------

| Reason | <code>parallel/test-net-listen-ipv6only</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58719/](https://ci.nodejs.org/job/node-test-pull-request/67510/), [https://github.com/nodejs/node/pull/58697/](https://ci.nodejs.org/job/node-test-pull-request/67571/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51301/console), [test-equinix-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/18999/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67510/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67571/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51301/console">Example</a></summary>

```
not ok 2094 parallel/test-net-listen-ipv6only
  ---
  duration_ms: 126.13800
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:117
      throw err;
      ^
    
    AssertionError [ERR_ASSERTION]: function should not have been called at /home/iojs/build/workspace/node-test-commit-linux-containered/test/parallel/test-net-listen-ipv6only.js:25
        at Socket.mustNotCall (/home/iojs/build/workspace/node-test-commit-linux-containered/test/common/index.js:495:12)
        at Socket.emit (node:events:507:28)
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1622:10) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: undefined,
      operator: 'fail'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-worker-nearheaplimit-deadlock</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58125/](https://ci.nodejs.org/job/node-test-pull-request/67569/), [https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/67595/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19058/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67569/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67595/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19058/console">Example</a></summary>

```
not ok 3965 parallel/test-worker-nearheaplimit-deadlock
  ---
  duration_ms: 811.84400
  severity: crashed
  exitcode: -6
  stack: |-
    
    <--- Last few GCs --->
     =[3116268:0xffff5c010000]       91 ms: Mark-Compact (reduce) 1.4 (2.0) -> 1.4 (2.0) MB, pooled: 0.0 MB, 2.77 / 0.00 ms (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 3 ms) (average mu = 0.468, current mu =[3116268:0xffff5c010000]       95 ms: Mark-Compact (reduce) 1.4 (2.0) -> 1.4 (2.0) MB, pooled: 0.0 MB, 2.42 / 0.00 ms (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 3 ms) (average mu = 0.485, current mu =
    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
    ----- Native stack trace -----
    
     1: 0xaaaae566d094 node::DumpNativeBacktrace(_IO_FILE*) [out/Debug/node]
     2: 0xaaaae57dc634 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [out/Debug/node]
     3: 0xaaaae5c238c0 v8::Utils::Repor...
```
</details>

-------


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 11 ([https://github.com/nodejs/node/pull/58734/](https://ci.nodejs.org/job/node-test-pull-request/67504/), [https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/67505/), [https://github.com/nodejs/node/pull/58719/](https://ci.nodejs.org/job/node-test-pull-request/67518/), [https://github.com/nodejs/node/pull/58749/](https://ci.nodejs.org/job/node-test-pull-request/67520/), [https://github.com/nodejs/node/pull/58767/](https://ci.nodejs.org/job/node-test-pull-request/67548/), [https://github.com/nodejs/node/pull/58715/](https://ci.nodejs.org/job/node-test-pull-request/67568/), [https://github.com/nodejs/node/pull/58697/](https://ci.nodejs.org/job/node-test-pull-request/67571/), [https://github.com/nodejs/node/pull/58765/](https://ci.nodejs.org/job/node-test-pull-request/67588/), [https://github.com/nodejs/node/pull/58711/](https://ci.nodejs.org/job/node-test-pull-request/67589/), [https://github.com/nodejs/node/pull/57688/](https://ci.nodejs.org/job/node-test-pull-request/67590/), [https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/67591/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/34950/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67504/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67591/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/34950/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Backing channel 'JNLP4-connect connection from ... is disconnected.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58645/](https://ci.nodejs.org/job/node-test-pull-request/67527/), [https://github.com/nodejs/node/pull/58691/](https://ci.nodejs.org/job/node-test-pull-request/67528/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19021/console), [test-equinix-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19019/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67527/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67528/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19021/console">Example</a></summary>

```
java.io.IOException: Backing channel 'JNLP4-connect connection from 145.40.81.219/145.40.81.219:37158' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:227)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:306)
	at jdk.proxy2/jdk.proxy2.$Proxy161.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1227)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1219)
```
</details>

-------

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58771/](https://ci.nodejs.org/job/node-test-pull-request/67562/), [https://github.com/nodejs/node/pull/58697/](https://ci.nodejs.org/job/node-test-pull-request/67571/)) |
| Appeared | [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51301/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67562/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67571/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51301/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58749/](https://ci.nodejs.org/job/node-test-pull-request/67520/), [https://github.com/nodejs/node/pull/58760/](https://ci.nodejs.org/job/node-test-pull-request/67536/), [https://github.com/nodejs/node/pull/58612/](https://ci.nodejs.org/job/node-test-pull-request/67545/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19033/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/65208/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67520/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67545/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19033/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1240)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1278)
```
</details>

-------


### Build Failure

| Reason | <code>Error: - process terminated with status 1, expected 0</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58765/](https://ci.nodejs.org/job/node-test-pull-request/67588/), [https://github.com/nodejs/node/pull/58711/](https://ci.nodejs.org/job/node-test-pull-request/67589/), [https://github.com/nodejs/node/pull/57688/](https://ci.nodejs.org/job/node-test-pull-request/67590/), [https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/67591/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2019/34950/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67588/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67591/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2019/34950/console">Example</a></summary>

```
Error: - process terminated with status 1, expected 0
  ---
  duration_ms: 24304.33100
  ...
ok 1001 sequential/test-single-executable-application-use-code-cache # skip Cannot find signtool: Error: - process terminated with status 1, expected 0
  ---
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58760/](https://ci.nodejs.org/job/node-test-pull-request/67536/), [https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/67595/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51321/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51285/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67536/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67595/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51321/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

