Failures in [node-test-pull-request/64896](https://ci.nodejs.org/job/node-test-pull-request/64896/) to [node-test-pull-request/64993](https://ci.nodejs.org/job/node-test-pull-request/64993/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-02-05.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-02-05 00:10 | 1       | 21      | 13       | 14      | 51      | 24.71%     |


### Jenkins Failure


### Build Failure

| Reason | <code>Error: list index out of range</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/56840/](https://ci.nodejs.org/job/node-test-pull-request/64898/), [https://github.com/nodejs/node/pull/56467/](https://ci.nodejs.org/job/node-test-pull-request/64911/), [https://github.com/nodejs/node/pull/56885/](https://ci.nodejs.org/job/node-test-pull-request/64943/), [https://github.com/nodejs/node/pull/56571/](https://ci.nodejs.org/job/node-test-pull-request/64947/), [https://github.com/nodejs/node/pull/56253/](https://ci.nodejs.org/job/node-test-pull-request/64955/), [https://github.com/nodejs/node/pull/56910/](https://ci.nodejs.org/job/node-test-pull-request/64978/), [https://github.com/nodejs/node/pull/56912/](https://ci.nodejs.org/job/node-test-pull-request/64992/)) |
| Appeared | [test-rackspace-win2016_vs2015-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2022-x86/32489/console), [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/32489/console), [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/32489/console), [test-azure_msft-win2016_vs2017-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2016-COMPILED_BY-vs2022-x86/32489/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64898/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64992/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2022-x86/32489/console">Example</a></summary>

```
Error: list index out of range

> if errorlevel 1 exit /b 

> if errorlevel 1 exit /b
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/56842/](https://ci.nodejs.org/job/node-test-pull-request/64896/), [https://github.com/nodejs/node/pull/56881/](https://ci.nodejs.org/job/node-test-pull-request/64922/), [https://github.com/nodejs/node/pull/56873/](https://ci.nodejs.org/job/node-test-pull-request/64929/), [https://github.com/nodejs/node/pull/56624/](https://ci.nodejs.org/job/node-test-pull-request/64946/), [https://github.com/nodejs/node/pull/56913/](https://ci.nodejs.org/job/node-test-pull-request/64987/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48873/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/57036/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48818/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48812/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48782/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64896/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64987/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48873/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>Error: - process terminated with status 1, expected 0</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56494/](https://ci.nodejs.org/job/node-test-pull-request/64933/), [https://github.com/nodejs/node/pull/56910/](https://ci.nodejs.org/job/node-test-pull-request/64978/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022/32483/console), [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022/32447/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64933/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64978/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022/32483/console">Example</a></summary>

```
Error: - process terminated with status 1, expected 0
  ---
  duration_ms: 16848.13300
  ...
ok 1024 sequential/test-single-executable-application-snapshot # skip Cannot find signtool: Error: - process terminated with status 1, expected 0
  ---
```
</details>

-------


### JSTest Failure

| Reason | <code>parallel/test-assert-fail</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 11 ([https://github.com/nodejs/node/pull/56842/](https://ci.nodejs.org/job/node-test-pull-request/64896/), [https://github.com/nodejs/node/pull/56467/](https://ci.nodejs.org/job/node-test-pull-request/64911/), [https://github.com/nodejs/node/pull/56881/](https://ci.nodejs.org/job/node-test-pull-request/64922/), [https://github.com/nodejs/node/pull/56888/](https://ci.nodejs.org/job/node-test-pull-request/64938/), [https://github.com/nodejs/node/pull/56886/](https://ci.nodejs.org/job/node-test-pull-request/64940/), [https://github.com/nodejs/node/pull/56840/](https://ci.nodejs.org/job/node-test-pull-request/64957/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/64963/), [https://github.com/nodejs/node/pull/56891/](https://ci.nodejs.org/job/node-test-pull-request/64966/), [https://github.com/nodejs/node/pull/56253/](https://ci.nodejs.org/job/node-test-pull-request/64968/), [https://github.com/nodejs/node/pull/56882/](https://ci.nodejs.org/job/node-test-pull-request/64979/), [https://github.com/nodejs/node/pull/56908/](https://ci.nodejs.org/job/node-test-pull-request/64983/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64896/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64983/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console">Example</a></summary>

```
not ok 18 parallel/test-assert-fail
  ---
  duration_ms: 432.50400
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'Object prototype get'
    Location: test/parallel/test-assert-fail.js:46:1
    Error: fail
        at TestContext.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/parallel/test-assert-fail.js:50:9)
        at Test.runInAsyncScope (node:async_hooks:211:14)
        at Test.run (node:internal/test_runner/test:980:25)
        at Test.processPendingSubtests (node:internal/test_runner/test:678:18)
        at Test.postRun (node:internal/test_runner/test:1091:19)
        at Test.run (node:internal/test_runner/test:1019:12)
        at async Test.processPendingSubtests (node:internal/test_runner/test:678:7)
    
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/56842/](https://ci.nodejs.org/job/node-test-pull-request/64896/), [https://github.com/nodejs/node/pull/56888/](https://ci.nodejs.org/job/node-test-pull-request/64938/), [https://github.com/nodejs/node/pull/56886/](https://ci.nodejs.org/job/node-test-pull-request/64940/), [https://github.com/nodejs/node/pull/56840/](https://ci.nodejs.org/job/node-test-pull-request/64957/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/64963/), [https://github.com/nodejs/node/pull/56891/](https://ci.nodejs.org/job/node-test-pull-request/64966/), [https://github.com/nodejs/node/pull/56253/](https://ci.nodejs.org/job/node-test-pull-request/64968/), [https://github.com/nodejs/node/pull/56882/](https://ci.nodejs.org/job/node-test-pull-request/64979/), [https://github.com/nodejs/node/pull/56908/](https://ci.nodejs.org/job/node-test-pull-request/64983/)) |
| Appeared | [vm-8vdtn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63509/console), [vm-jbbmk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63506/console), [vm-tl5th](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63426/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64896/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64983/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63509/console">Example</a></summary>

```
not ok 2581 parallel/test-runner-run-watch
  ---
  duration_ms: 28455.01800
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run tests with dependency repeatedly'
    Location: test/parallel/test-runner-run-watch.mjs:200:3
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 1/. Input:
    
    '# Subtest: test.js\n' +
      'not ok 2 - test.js\n' +
      '  ---\n' +
      '  duration_ms: 789.495349\n' +
      "  type: 'test'\n" +
      "  location: '/Users/admin/node-tmp/.tmp.2538/test.js:1:1'\n" +
      "  failureType: 'testCodeFailure'\n" +
      '  exitCode: ~\n' +
      "  signal: 'SIGTERM'\n" +
      "  error: 'test failed'\n" +
      "  code: 'ERR_TEST_FAILURE'\n" +
      '  ...\n' +
      '# Subtest: test has ran\n' +
      'ok 2 - test has ran\n' +
      '  ---\n' +
      '  duration_ms: 1.036307\n' +
      "  type: 'test'\n" +
      '  ...\n' +
      '1..2\n' +
      '# tests 2\n' +
      '# suites 0\n' +
      '# pass 1\n' +
      '# fail 1\n...
```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/56877/](https://ci.nodejs.org/job/node-test-pull-request/64918/), [https://github.com/nodejs/node/pull/56871/](https://ci.nodejs.org/job/node-test-pull-request/64921/), [https://github.com/nodejs/node/pull/56808/](https://ci.nodejs.org/job/node-test-pull-request/64932/), [https://github.com/nodejs/node/pull/56885/](https://ci.nodejs.org/job/node-test-pull-request/64943/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/64963/), [https://github.com/nodejs/node/pull/56882/](https://ci.nodejs.org/job/node-test-pull-request/64979/), [https://github.com/nodejs/node/pull/56624/](https://ci.nodejs.org/job/node-test-pull-request/64990/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57072/console), [vm-jmb2t](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/63506/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/48851/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/57033/console), [test-digitalocean-fedora41-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/62973/console), [test-ibm-alpine319_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/62965/console), [test-osuosl-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/57012/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64918/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64990/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57072/console">Example</a></summary>

```
not ok 4039 parallel/test-file-write-stream4
  ---
  duration_ms: 360107.42400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/56870/](https://ci.nodejs.org/job/node-test-pull-request/64902/), [https://github.com/nodejs/node/pull/56467/](https://ci.nodejs.org/job/node-test-pull-request/64911/), [https://github.com/nodejs/node/pull/56881/](https://ci.nodejs.org/job/node-test-pull-request/64922/), [https://github.com/nodejs/node/pull/56882/](https://ci.nodejs.org/job/node-test-pull-request/64925/), [https://github.com/nodejs/node/pull/56840/](https://ci.nodejs.org/job/node-test-pull-request/64949/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/64963/), [https://github.com/nodejs/node/pull/56624/](https://ci.nodejs.org/job/node-test-pull-request/64993/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57075/console), [test-digitalocean-ubuntu2204-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/63003/console), [test-mnx-smartos23-x64-5](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/59026/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/48814/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57016/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64902/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64993/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57075/console">Example</a></summary>

```
not ok 4186 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 360056.12400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-hex-string</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56840/](https://ci.nodejs.org/job/node-test-pull-request/64898/), [https://github.com/nodejs/node/pull/56808/](https://ci.nodejs.org/job/node-test-pull-request/64899/), [https://github.com/nodejs/node/pull/56886/](https://ci.nodejs.org/job/node-test-pull-request/64940/), [https://github.com/nodejs/node/pull/56885/](https://ci.nodejs.org/job/node-test-pull-request/64943/)) |
| Appeared | [test-rackspace-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/62984/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/48828/console), [test-ibm-alpine319_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/62942/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/48785/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64898/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64943/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/62984/console">Example</a></summary>

```
not ok 3319 parallel/test-net-write-fully-async-hex-string
  ---
  duration_ms: 120072.13100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>es-module/test-esm-loader-entry-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56624/](https://ci.nodejs.org/job/node-test-pull-request/64946/), [https://github.com/nodejs/node/pull/56869/](https://ci.nodejs.org/job/node-test-pull-request/64974/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48859/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48836/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64946/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64974/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48859/console">Example</a></summary>

```
not ok 3992 es-module/test-esm-loader-entry-url
  ---
  duration_ms: 120034.32400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>node-api/test_threadsafe_function/test</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56881/](https://ci.nodejs.org/job/node-test-pull-request/64928/), [https://github.com/nodejs/node/pull/56886/](https://ci.nodejs.org/job/node-test-pull-request/64940/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/15766/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64928/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64940/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/15766/console">Example</a></summary>

```
not ok 149 node-api/test_threadsafe_function/test
  ---
  duration_ms: 360060.48800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-rangeerror</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56845/](https://ci.nodejs.org/job/node-test-pull-request/64913/), [https://github.com/nodejs/node/pull/56416/](https://ci.nodejs.org/job/node-test-pull-request/64950/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15778/console), [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15746/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64913/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64950/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15778/console">Example</a></summary>

```
not ok 4009 parallel/test-buffer-tostring-rangeerror
  ---
  duration_ms: 360044.28300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    (node:2611881) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    (node:2611881) [DEP0030] DeprecationWarning: SlowBuffer() is deprecated. Please use Buffer.allocUnsafeSlow()
  ...

```
</details>

-------

| Reason | <code>parallel/test-child-process-cwd</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56885/](https://ci.nodejs.org/job/node-test-pull-request/64943/), [https://github.com/nodejs/node/pull/56910/](https://ci.nodejs.org/job/node-test-pull-request/64978/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/32482/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64943/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64978/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/32482/console">Example</a></summary>

```
not ok 98 parallel/test-child-process-cwd
  ---
  duration_ms: 239.00500
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:125
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    
    + 'C:\\Windows'
    - 'C:\\WINDOWS'
            ^
        at ChildProcess.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-child-process-cwd.js:55:26)
        at ChildProcess.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\common\index.js:467:15)
        at ChildProcess.emit (node:events:517:28)
        at maybeClose (node:internal/child_process:1098:16)
        at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'C:\\Windows',
      expected: 'C:\\WINDOWS',
      operator: 'strictEqual'
    }
    
    Node.js v18.20.7-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-node-output-eval</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56571/](https://ci.nodejs.org/job/node-test-pull-request/64947/), [https://github.com/nodejs/node/pull/56253/](https://ci.nodejs.org/job/node-test-pull-request/64968/)) |
| Appeared | [test-rackspace-win2016_vs2015-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/32474/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022/32459/console), [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/32459/console), [test-rackspace-win2019_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/32459/console), [test-rackspace-win2022_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2022-COMPILED_BY-vs2022/32459/console), [test-azure_msft-win11_vs2022-arm64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/32459/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64947/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64968/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/32474/console">Example</a></summary>

```
not ok 618 parallel/test-node-output-eval
  ---
  duration_ms: 2276.95700
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: eval output
        # Subtest: eval/eval_messages.js
        not ok 1 - eval/eval_messages.js
          ---
          duration_ms: 1749.7979
          location: 'C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\parallel\\test-node-output-eval.mjs:35:5'
          failureType: 'testCodeFailure'
          error: |-
            Expected values to be strictly equal:
            + actual - expected
            
              '[eval]\n' +
                '[eval]:1\n' +
                'with(this){__filename}\n' +
                '^^^^\n' +
            -   '\n' +
                'SyntaxError: Strict mode code may not include a with statement\n' +
            -   '\n' +
                'Node.js *\n' +
                '42\n' +
                '42\n' +
                '[eval]:1\n' +
                'throw new Error("hello")\n' +
                '^\n' +
     ...
```
</details>

-------

| Reason | <code>parallel/test-process-threadCpuUsage-worker-threads</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56842/](https://ci.nodejs.org/job/node-test-pull-request/64896/), [https://github.com/nodejs/node/pull/56467/](https://ci.nodejs.org/job/node-test-pull-request/64927/)) |
| Appeared | [test-digitalocean-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/62970/console), [test-osuosl-aix72-ppc64_be-3](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/55792/console), [test-mnx-smartos22-x64-1](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/59006/console), [test-mnx-smartos23-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/59006/console), [test-digitalocean-ubi81_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/48816/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48816/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/48816/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/48816/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/48816/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/48816/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/40605/console), [vm-jbbmk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63445/console), [test-ibm-alpine319_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/62956/console), [test-rackspace-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/62956/console), [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/62956/console), [test-digitalocean-fedora41-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/62956/console), [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/62956/console), [test-ibm-rhel9-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/62956/console), [test-ibm-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/62956/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/57550/console), [test-osuosl-rhel9-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/57550/console), [test-mnx-smartos23-x64-5](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/58993/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/48801/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/48801/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/48801/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/48801/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48801/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48801/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/48801/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/48801/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/47927/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022/32431/console), [test-azure_msft-win11_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/32431/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/32431/console), [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2022-COMPILED_BY-vs2022/32431/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/32431/console), [test-digitalocean-alpine319_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/62938/console), [test-ibm-rhel8-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/62938/console), [test-ibm-rhel9-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/62938/console), [test-rackspace-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/62938/console), [test-osuosl-rhel9-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/57532/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/48781/console), [test-osuosl-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/55761/console), [test-rackspace-win2022_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2022-COMPILED_BY-vs2022/32412/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/32412/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64896/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64927/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/62970/console">Example</a></summary>

```
not ok 2659 parallel/test-process-threadCpuUsage-worker-threads
  ---
  duration_ms: 17002.49400
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/process/promises:394
        triggerUncaughtException(err, true /* fromPromise */);
        ^
    
    AssertionError [ERR_ASSERTION]: threadDifference: 0 0.8331827492851622
        at validateResults (/home/iojs/build/workspace/node/test/parallel/test-process-threadCpuUsage-worker-threads.js:50:5)
        at Timeout.<anonymous> (/home/iojs/build/workspace/node/test/parallel/test-process-threadCpuUsage-worker-threads.js:77:5)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56881/](https://ci.nodejs.org/job/node-test-pull-request/64922/), [https://github.com/nodejs/node/pull/56869/](https://ci.nodejs.org/job/node-test-pull-request/64974/)) |
| Appeared | [test-ibm-rhel8-s390x-3](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/47977/console), [vm-8vdtn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63454/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64922/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64974/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/47977/console">Example</a></summary>

```
not ok 4352 sequential/test-perf-hooks
  ---
  duration_ms: 925.75500
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (686.282958984375) - process.uptime() * 1000 (534.016653) = 152.26630598437498 >= +- 50
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-linuxone/test/sequential/test-perf-hooks.js:36:3)
        at Module._compile (node:internal/modules/cjs/loader:1727:14)
        at Object..js (node:internal/modules/cjs/loader:1892:10)
        at Module.load (node:internal/modules/cjs/loader:1462:32)
        at Function._load (node:internal/modules/cjs/loader:1279:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:151:5)
        at node:internal/main/run_main_module:33:47 {
 ...
```
</details>

-------

| Reason | <code>wpt/test-timers</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56873/](https://ci.nodejs.org/job/node-test-pull-request/64917/), [https://github.com/nodejs/node/pull/56882/](https://ci.nodejs.org/job/node-test-pull-request/64971/)) |
| Appeared | [test-osuosl-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/57055/console), [test-ibm-rhel8-s390x-2](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/47932/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64917/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64971/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/57055/console">Example</a></summary>

```
not ok 4386 wpt/test-timers
  ---
  duration_ms: 1710.45300
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] negative-settimeout.any.js: unreliable in Node.js; Refs: https://github.com/nodejs/node/issues/37672
    [PASS] Clear timeout with clearInterval
    [PASS] Clear interval with clearTimeout
    [PASS] Calling setInterval with no interval should be the same as if called with 0 interval
    [PASS] Calling setInterval with undefined interval should be the same as if called with 0 interval
    [PASS] negative-setinterval
    [PASS] type-long-setinterval
    [UNEXPECTED_FAILURE][UNCAUGHT] evaluation in WPTRunner.runJsTests()
    assert_unreached: Reached unreachable code
    {
      message: 'assert_unreached: Reached unreachable code',
      stack: '    at listOnTimeout (node:internal/timers:614:17)\n' +
        '    at process.processTimers (node:internal/timers:549:7)'
    }
    Command: /home/iojs/build/workspace/node-test-commit-arm/out/Release/node --test-reporter=./test/common/test-error-repor...
```
</details>

-------

