Failures in [node-test-pull-request/64921](https://ci.nodejs.org/job/node-test-pull-request/64921/) to [node-test-pull-request/65018](https://ci.nodejs.org/job/node-test-pull-request/65018/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-02-06.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-02-06 00:09 | 4       | 22      | 10       | 13      | 51      | 26.51%     |


### Jenkins Failure


### Git Failure


### Build Failure

| Reason | <code>Error: list index out of range</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/56885/](https://ci.nodejs.org/job/node-test-pull-request/64943/), [https://github.com/nodejs/node/pull/56571/](https://ci.nodejs.org/job/node-test-pull-request/64947/), [https://github.com/nodejs/node/pull/56253/](https://ci.nodejs.org/job/node-test-pull-request/64955/), [https://github.com/nodejs/node/pull/56910/](https://ci.nodejs.org/job/node-test-pull-request/64978/), [https://github.com/nodejs/node/pull/56467/](https://ci.nodejs.org/job/node-test-pull-request/65000/), [https://github.com/nodejs/node/pull/56912/](https://ci.nodejs.org/job/node-test-pull-request/65011/)) |
| Appeared | [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2022-x86/32509/console), [test-rackspace-win2016_vs2015-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/32509/console), [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/32509/console), [test-azure_msft-win2016_vs2017-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2016-COMPILED_BY-vs2022-x86/32509/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64943/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65011/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2022-x86/32509/console">Example</a></summary>

```
Error: list index out of range

> if errorlevel 1 exit /b 

> if errorlevel 1 exit /b
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/56881/](https://ci.nodejs.org/job/node-test-pull-request/64922/), [https://github.com/nodejs/node/pull/56873/](https://ci.nodejs.org/job/node-test-pull-request/64929/), [https://github.com/nodejs/node/pull/56624/](https://ci.nodejs.org/job/node-test-pull-request/64946/), [https://github.com/nodejs/node/pull/56913/](https://ci.nodejs.org/job/node-test-pull-request/64987/), [https://github.com/nodejs/node/pull/56842/](https://ci.nodejs.org/job/node-test-pull-request/65008/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48894/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48873/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/57036/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48818/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48812/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64922/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65008/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48894/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56891/](https://ci.nodejs.org/job/node-test-pull-request/64953/), [https://github.com/nodejs/node/pull/56148/](https://ci.nodejs.org/job/node-test-pull-request/64998/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15812/console), [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/15812/console), [test-equinix-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/17063/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64953/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64998/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15812/console">Example</a></summary>

```
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
[PostBuildScript] - [INFO] Executing post build scripts.
[node-test-binary-armv7l] $ /bin/bash -ex /tmp/jenkins15152676060210203575.sh
+ '[' -d .git ']'
+ git clean -fdx
Removing out/
```
</details>

-------

| Reason | <code>Error: - process terminated with status 1, expected 0</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56494/](https://ci.nodejs.org/job/node-test-pull-request/64933/), [https://github.com/nodejs/node/pull/56910/](https://ci.nodejs.org/job/node-test-pull-request/64978/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022/32483/console), [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022/32447/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64933/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64978/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022/32483/console">Example</a></summary>

```
Error: - process terminated with status 1, expected 0
  ---
  duration_ms: 16848.13300
  ...
ok 1024 sequential/test-single-executable-application-snapshot # skip Cannot find signtool: Error: - process terminated with status 1, expected 0
  ---
```
</details>

-------

| Reason | <code>Failed to trigger sub builds</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56840/](https://ci.nodejs.org/job/node-test-pull-request/64984/), [https://github.com/nodejs/node/pull/56117/](https://ci.nodejs.org/job/node-test-pull-request/65018/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit/77646/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64984/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65018/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit/77646/console">Example</a></summary>

```
Failed to trigger sub builds
```
</details>

-------

| Reason | <code>error C1060: compiler is out of heap space [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56871/](https://ci.nodejs.org/job/node-test-pull-request/64921/), [https://github.com/nodejs/node/pull/56929/](https://ci.nodejs.org/job/node-test-pull-request/65012/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-6](https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/60305/console), [test-rackspace-win2022_vs2022-x64-1](https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/60223/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64921/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65012/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/60305/console">Example</a></summary>

```
error C1060: compiler is out of heap space [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
C:\workspace\node-compile-windows\node\out\Release\obj\global_intermediate\torque-generated\src\builtins\array-reverse-tq-csa.cc(1064,1): fatal  error C1060: compiler is out of heap space [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
  array-reduce-tq-csa.cc
  array-some-tq-csa.cc
  array-to-reversed-tq-csa.cc
```
</details>

-------


### JSTest Failure

| Reason | <code>parallel/test-assert-fail</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/56881/](https://ci.nodejs.org/job/node-test-pull-request/64922/), [https://github.com/nodejs/node/pull/56888/](https://ci.nodejs.org/job/node-test-pull-request/64938/), [https://github.com/nodejs/node/pull/56886/](https://ci.nodejs.org/job/node-test-pull-request/64940/), [https://github.com/nodejs/node/pull/56840/](https://ci.nodejs.org/job/node-test-pull-request/64957/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/64963/), [https://github.com/nodejs/node/pull/56891/](https://ci.nodejs.org/job/node-test-pull-request/64966/), [https://github.com/nodejs/node/pull/56253/](https://ci.nodejs.org/job/node-test-pull-request/64968/), [https://github.com/nodejs/node/pull/56882/](https://ci.nodejs.org/job/node-test-pull-request/64979/), [https://github.com/nodejs/node/pull/56908/](https://ci.nodejs.org/job/node-test-pull-request/64983/), [https://github.com/nodejs/node/pull/56655/](https://ci.nodejs.org/job/node-test-pull-request/65001/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64922/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65001/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console">Example</a></summary>

```
not ok 18 parallel/test-assert-fail
  ---
  duration_ms: 432.50400
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'Object prototype get'
    Location: test/parallel/test-assert-fail.js:46:1
    Error: fail
        at TestContext.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/parallel/test-assert-fail.js:50:9)
        at Test.runInAsyncScope (node:async_hooks:211:14)
        at Test.run (node:internal/test_runner/test:980:25)
        at Test.processPendingSubtests (node:internal/test_runner/test:678:18)
        at Test.postRun (node:internal/test_runner/test:1091:19)
        at Test.run (node:internal/test_runner/test:1019:12)
        at async Test.processPendingSubtests (node:internal/test_runner/test:678:7)
    
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/56888/](https://ci.nodejs.org/job/node-test-pull-request/64938/), [https://github.com/nodejs/node/pull/56886/](https://ci.nodejs.org/job/node-test-pull-request/64940/), [https://github.com/nodejs/node/pull/56840/](https://ci.nodejs.org/job/node-test-pull-request/64957/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/64963/), [https://github.com/nodejs/node/pull/56891/](https://ci.nodejs.org/job/node-test-pull-request/64966/), [https://github.com/nodejs/node/pull/56253/](https://ci.nodejs.org/job/node-test-pull-request/64968/), [https://github.com/nodejs/node/pull/56882/](https://ci.nodejs.org/job/node-test-pull-request/64979/), [https://github.com/nodejs/node/pull/56908/](https://ci.nodejs.org/job/node-test-pull-request/64983/)) |
| Appeared | [vm-8vdtn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63509/console), [vm-jbbmk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63506/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64938/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64983/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63509/console">Example</a></summary>

```
not ok 2581 parallel/test-runner-run-watch
  ---
  duration_ms: 28455.01800
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run tests with dependency repeatedly'
    Location: test/parallel/test-runner-run-watch.mjs:200:3
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 1/. Input:
    
    '# Subtest: test.js\n' +
      'not ok 2 - test.js\n' +
      '  ---\n' +
      '  duration_ms: 789.495349\n' +
      "  type: 'test'\n" +
      "  location: '/Users/admin/node-tmp/.tmp.2538/test.js:1:1'\n" +
      "  failureType: 'testCodeFailure'\n" +
      '  exitCode: ~\n' +
      "  signal: 'SIGTERM'\n" +
      "  error: 'test failed'\n" +
      "  code: 'ERR_TEST_FAILURE'\n" +
      '  ...\n' +
      '# Subtest: test has ran\n' +
      'ok 2 - test has ran\n' +
      '  ---\n' +
      '  duration_ms: 1.036307\n' +
      "  type: 'test'\n" +
      '  ...\n' +
      '1..2\n' +
      '# tests 2\n' +
      '# suites 0\n' +
      '# pass 1\n' +
      '# fail 1\n...
```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/56871/](https://ci.nodejs.org/job/node-test-pull-request/64921/), [https://github.com/nodejs/node/pull/56808/](https://ci.nodejs.org/job/node-test-pull-request/64932/), [https://github.com/nodejs/node/pull/56885/](https://ci.nodejs.org/job/node-test-pull-request/64943/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/64963/), [https://github.com/nodejs/node/pull/56882/](https://ci.nodejs.org/job/node-test-pull-request/64979/), [https://github.com/nodejs/node/pull/56624/](https://ci.nodejs.org/job/node-test-pull-request/64990/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57072/console), [vm-jmb2t](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/63506/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/48851/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/57033/console), [test-digitalocean-fedora41-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/62973/console), [test-ibm-alpine319_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/62965/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64921/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64990/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57072/console">Example</a></summary>

```
not ok 4039 parallel/test-file-write-stream4
  ---
  duration_ms: 360107.42400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/56881/](https://ci.nodejs.org/job/node-test-pull-request/64922/), [https://github.com/nodejs/node/pull/56882/](https://ci.nodejs.org/job/node-test-pull-request/64925/), [https://github.com/nodejs/node/pull/56840/](https://ci.nodejs.org/job/node-test-pull-request/64949/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/64963/), [https://github.com/nodejs/node/pull/56624/](https://ci.nodejs.org/job/node-test-pull-request/64993/), [https://github.com/nodejs/node/pull/56842/](https://ci.nodejs.org/job/node-test-pull-request/65008/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57090/console), [test-digitalocean-ubuntu2204-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/63003/console), [test-mnx-smartos23-x64-5](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/59026/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/48814/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57016/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64922/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65008/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57090/console">Example</a></summary>

```
not ok 4098 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 360041.57900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56881/](https://ci.nodejs.org/job/node-test-pull-request/64922/), [https://github.com/nodejs/node/pull/56869/](https://ci.nodejs.org/job/node-test-pull-request/64974/), [https://github.com/nodejs/node/pull/56655/](https://ci.nodejs.org/job/node-test-pull-request/65001/)) |
| Appeared | [vm-wtknr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63522/console), [test-ibm-rhel8-s390x-3](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/47977/console), [vm-8vdtn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63454/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64922/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65001/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63522/console">Example</a></summary>

```
not ok 4346 sequential/test-perf-hooks
  ---
  duration_ms: 517.82800
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (236.138916015625) - process.uptime() * 1000 (127.28866699999999) = 108.85024901562501 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-perf-hooks.js:36:3)
        at Module._compile (node:internal/modules/cjs/loader:1727:14)
        at Object..js (node:internal/modules/cjs/loader:1892:10)
        at Module.load (node:internal/modules/cjs/loader:1462:32)
        at Function._load (node:internal/modules/cjs/loader:1279:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:151:5)
        at node:internal/main/run_...
```
</details>

-------

| Reason | <code>es-module/test-esm-loader-entry-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56624/](https://ci.nodejs.org/job/node-test-pull-request/64946/), [https://github.com/nodejs/node/pull/56869/](https://ci.nodejs.org/job/node-test-pull-request/64974/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48859/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48836/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64946/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64974/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48859/console">Example</a></summary>

```
not ok 3992 es-module/test-esm-loader-entry-url
  ---
  duration_ms: 120034.32400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>node-api/test_threadsafe_function/test</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56881/](https://ci.nodejs.org/job/node-test-pull-request/64928/), [https://github.com/nodejs/node/pull/56886/](https://ci.nodejs.org/job/node-test-pull-request/64940/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/15766/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64928/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64940/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/15766/console">Example</a></summary>

```
not ok 149 node-api/test_threadsafe_function/test
  ---
  duration_ms: 360060.48800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-child-process-cwd</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56885/](https://ci.nodejs.org/job/node-test-pull-request/64943/), [https://github.com/nodejs/node/pull/56910/](https://ci.nodejs.org/job/node-test-pull-request/64978/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/32482/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64943/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64978/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/32482/console">Example</a></summary>

```
not ok 98 parallel/test-child-process-cwd
  ---
  duration_ms: 239.00500
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:125
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    
    + 'C:\\Windows'
    - 'C:\\WINDOWS'
            ^
        at ChildProcess.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-child-process-cwd.js:55:26)
        at ChildProcess.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\common\index.js:467:15)
        at ChildProcess.emit (node:events:517:28)
        at maybeClose (node:internal/child_process:1098:16)
        at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'C:\\Windows',
      expected: 'C:\\WINDOWS',
      operator: 'strictEqual'
    }
    
    Node.js v18.20.7-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-hex-string</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56886/](https://ci.nodejs.org/job/node-test-pull-request/64940/), [https://github.com/nodejs/node/pull/56885/](https://ci.nodejs.org/job/node-test-pull-request/64943/)) |
| Appeared | [test-rackspace-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/62984/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/48828/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64940/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64943/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/62984/console">Example</a></summary>

```
not ok 3319 parallel/test-net-write-fully-async-hex-string
  ---
  duration_ms: 120072.13100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-node-output-eval</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56571/](https://ci.nodejs.org/job/node-test-pull-request/64947/), [https://github.com/nodejs/node/pull/56253/](https://ci.nodejs.org/job/node-test-pull-request/64968/)) |
| Appeared | [test-rackspace-win2016_vs2015-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/32474/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022/32459/console), [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/32459/console), [test-rackspace-win2019_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/32459/console), [test-rackspace-win2022_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2022-COMPILED_BY-vs2022/32459/console), [test-azure_msft-win11_vs2022-arm64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/32459/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64947/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64968/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/32474/console">Example</a></summary>

```
not ok 618 parallel/test-node-output-eval
  ---
  duration_ms: 2276.95700
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: eval output
        # Subtest: eval/eval_messages.js
        not ok 1 - eval/eval_messages.js
          ---
          duration_ms: 1749.7979
          location: 'C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\parallel\\test-node-output-eval.mjs:35:5'
          failureType: 'testCodeFailure'
          error: |-
            Expected values to be strictly equal:
            + actual - expected
            
              '[eval]\n' +
                '[eval]:1\n' +
                'with(this){__filename}\n' +
                '^^^^\n' +
            -   '\n' +
                'SyntaxError: Strict mode code may not include a with statement\n' +
            -   '\n' +
                'Node.js *\n' +
                '42\n' +
                '42\n' +
                '[eval]:1\n' +
                'throw new Error("hello")\n' +
                '^\n' +
     ...
```
</details>

-------

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56911/](https://ci.nodejs.org/job/node-test-pull-request/65009/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/65010/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48896/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48895/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65009/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65010/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48896/console">Example</a></summary>

```
not ok 3626 parallel/test-without-async-context-frame
  ---
  duration_ms: 120106.83300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56913/](https://ci.nodejs.org/job/node-test-pull-request/64987/), [https://github.com/nodejs/node/pull/56919/](https://ci.nodejs.org/job/node-test-pull-request/64999/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48881/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64987/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64999/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48881/console">Example</a></summary>

```
not ok 4362 sequential/test-tls-session-timeout
  ---
  duration_ms: 218.20300
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:128
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at /home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:150:16
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:134:7)
        at ChildProcess.emit (node:events:507:28)
        at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual'
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

