Failures in [node-test-pull-request/67994](https://ci.nodejs.org/job/node-test-pull-request/67994/) to [node-test-pull-request/68091](https://ci.nodejs.org/job/node-test-pull-request/68091/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-07-22.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-07-22 00:13 | 0       | 0       | 27       | 1       | 72      | 0.00%      |


### JSTest Failure

| Reason | <code>wasi/test-wasi</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 14 ([https://github.com/nodejs/node/pull/58822/](https://ci.nodejs.org/job/node-test-pull-request/68001/), [https://github.com/nodejs/node/pull/59067/](https://ci.nodejs.org/job/node-test-pull-request/68003/), [https://github.com/nodejs/node/pull/59110/](https://ci.nodejs.org/job/node-test-pull-request/68007/), [https://github.com/nodejs/node/pull/59094/](https://ci.nodejs.org/job/node-test-pull-request/68009/), [https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/68021/), [https://github.com/nodejs/node/pull/57038/](https://ci.nodejs.org/job/node-test-pull-request/68032/), [https://github.com/nodejs/node/pull/59141/](https://ci.nodejs.org/job/node-test-pull-request/68056/), [https://github.com/nodejs/node/pull/59098/](https://ci.nodejs.org/job/node-test-pull-request/68070/), [https://github.com/nodejs/node/pull/59093/](https://ci.nodejs.org/job/node-test-pull-request/68074/), [https://github.com/nodejs/node/pull/59148/](https://ci.nodejs.org/job/node-test-pull-request/68078/), [https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/65695/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-linuxonecc-rhel9-s390x-3](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50608/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59440/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51793/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51793/console), [test-digitalocean-alpine321_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65694/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51792/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51792/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51792/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51792/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51792/console), [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19446/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59430/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19440/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68001/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/65695/console">Example</a></summary>

```
not ok 519 wasi/test-wasi
  ---
  duration_ms: 120034.35000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    Testing with --turbo-fast-api-calls: clock_getres
  ...

```
</details>

-------

| Reason | <code>wpt/test-web-locks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/68002/), [https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/68021/), [https://github.com/nodejs/node/pull/59020/](https://ci.nodejs.org/job/node-test-pull-request/68022/), [https://github.com/nodejs/node/pull/57038/](https://ci.nodejs.org/job/node-test-pull-request/68032/), [https://github.com/nodejs/node/pull/59059/](https://ci.nodejs.org/job/node-test-pull-request/68044/), [https://github.com/nodejs/node/pull/59086/](https://ci.nodejs.org/job/node-test-pull-request/68055/), [https://github.com/nodejs/node/pull/59141/](https://ci.nodejs.org/job/node-test-pull-request/68056/), [https://github.com/nodejs/node/pull/59132/](https://ci.nodejs.org/job/node-test-pull-request/68068/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/68081/), [https://github.com/nodejs/node/pull/59098/](https://ci.nodejs.org/job/node-test-pull-request/68085/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50606/console), [test-linuxonecc-rhel9-s390x-3](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50603/console), [test-mnx-smartos23-x64-6](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/61589/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/43145/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51769/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50583/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51745/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51736/console), [test-osuosl-rhel9-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/59908/console), [test-digitalocean-fedora40-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/65626/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68002/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68085/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50606/console">Example</a></summary>

```
not ok 4633 wpt/test-web-locks
  ---
  duration_ms: 844.40100
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] non-secure-context.any.js: navigator.locks is only present in secure contexts
    [SKIPPED] secure-context.https.any.js: Different secure context behavior in Node.js
    [SKIPPED] storage-buckets.tentative.https.any.js: Node.js does not implement Storage Buckets API
    [PASS] navigator.locks.request requires a name and a callback
    [PASS] mode must be "shared" or "exclusive"
    [PASS] The 'steal' and 'ifAvailable' options are mutually exclusive
    [PASS] The 'steal' option must be used with exclusive locks
    [PASS] The 'signal' and 'steal' options are mutually exclusive
    [PASS] The 'signal' and 'ifAvailable' options are mutually exclusive
    [PASS] callback must be a function
    [PASS] navigator.locks.request's returned promise resolves after lock is released
    [PASS] Returned Promise rejects if callback throws synchronously
    [PASS] Returned Promise rejects if callback throws...
```
</details>

-------

| Reason | <code>parallel/test-http-outgoing-end-cork</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/59094/](https://ci.nodejs.org/job/node-test-pull-request/68009/), [https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/68021/), [https://github.com/nodejs/node/pull/59141/](https://ci.nodejs.org/job/node-test-pull-request/68056/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68057/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68064/), [https://github.com/nodejs/node/pull/59098/](https://ci.nodejs.org/job/node-test-pull-request/68070/), [https://github.com/nodejs/node/pull/59148/](https://ci.nodejs.org/job/node-test-pull-request/68078/), [https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59440/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18032/console), [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19446/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19440/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59383/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68009/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59440/console">Example</a></summary>

```
not ok 1743 parallel/test-http-outgoing-end-cork
  ---
  duration_ms: 2036.28800
  severity: fail
  exitcode: 1
  stack: |-
    Sending req no 1
    node:assert:142
      throw err;
      ^
    
    AssertionError [ERR_ASSERTION]: () => {
        reject(new Error('Request timed out'));
      } at /home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-http-outgoing-end-cork.js:53
        at Timeout.mustNotCall [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-arm/test/common/index.js:495:12)
        at listOnTimeout (node:internal/timers:588:17)
        at process.processTimers (node:internal/timers:523:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: undefined,
      operator: 'fail'
    }
    
    Node.js v22.17.2-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-worker-message-port-transfer-filehandle</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/59013/](https://ci.nodejs.org/job/node-test-pull-request/68018/), [https://github.com/nodejs/node/pull/59020/](https://ci.nodejs.org/job/node-test-pull-request/68024/), [https://github.com/nodejs/node/pull/59059/](https://ci.nodejs.org/job/node-test-pull-request/68033/), [https://github.com/nodejs/node/pull/59042/](https://ci.nodejs.org/job/node-test-pull-request/68039/), [https://github.com/nodejs/node/pull/59072/](https://ci.nodejs.org/job/node-test-pull-request/68047/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/68058/), [https://github.com/nodejs/node/pull/59129/](https://ci.nodejs.org/job/node-test-pull-request/68061/), [https://github.com/nodejs/node/pull/59144/](https://ci.nodejs.org/job/node-test-pull-request/68080/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35575/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35549/console), [test-azure_msft-win11_vs2022-arm64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35488/console), [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35483/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68018/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68080/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35575/console">Example</a></summary>

```
not ok 998 parallel/test-worker-message-port-transfer-filehandle
  ---
  duration_ms: 280.10700
  severity: fail
  exitcode: 1
  stack: |-
    <anonymous_script>:0
    
    
    [Error: A FileHandle object was closed during garbage collection. This used to be allowed with a deprecation warning but is now considered an error. Please close FileHandle objects explicitly.] {
      code: 'ERR_INVALID_STATE'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-mock-timers-scheduler</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/68021/), [https://github.com/nodejs/node/pull/58842/](https://ci.nodejs.org/job/node-test-pull-request/68041/), [https://github.com/nodejs/node/pull/59141/](https://ci.nodejs.org/job/node-test-pull-request/68056/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68057/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68064/), [https://github.com/nodejs/node/pull/59098/](https://ci.nodejs.org/job/node-test-pull-request/68070/), [https://github.com/nodejs/node/pull/59148/](https://ci.nodejs.org/job/node-test-pull-request/68078/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19446/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19440/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59424/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68021/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68078/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19446/console">Example</a></summary>

```
not ok 3019 parallel/test-runner-mock-timers-scheduler
  ---
  duration_ms: 8660.13100
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should advance in time and trigger timers when calling the .tick function'
    Location: test/parallel/test-runner-mock-timers-scheduler.js:10:3
    AssertionError [ERR_ASSERTION]: time should be advanced less than the 100ms
        at /home/iojs/build/workspace/node-test-commit-arm-debug/test/parallel/test-runner-mock-timers-scheduler.js:21:14
        at /home/iojs/build/workspace/node-test-commit-arm-debug/test/common/index.js:437:15
        at async Test.run (node:internal/test_runner/test:1088:7)
        at async Promise.all (index 0)
        at async Suite.run (node:internal/test_runner/test:1485:7)
        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:332:3) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
  ...

```
</details>

-------

| Reason | <code>parallel/test-fs-watch-recursive-delete</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/68021/), [https://github.com/nodejs/node/pull/58674/](https://ci.nodejs.org/job/node-test-pull-request/68052/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/68058/), [https://github.com/nodejs/node/pull/59134/](https://ci.nodejs.org/job/node-test-pull-request/68060/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68065/), [https://github.com/nodejs/node/pull/59148/](https://ci.nodejs.org/job/node-test-pull-request/68091/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58190/console), [test-digitalocean-fedora41-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/65682/console), [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/65644/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68021/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68091/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58190/console">Example</a></summary>

```
not ok 2239 parallel/test-fs-watch-recursive-delete
  ---
  duration_ms: 120126.47900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-keep-alive-empty-line</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/58664/](https://ci.nodejs.org/job/node-test-pull-request/68021/), [https://github.com/nodejs/node/pull/57038/](https://ci.nodejs.org/job/node-test-pull-request/68032/), [https://github.com/nodejs/node/pull/59093/](https://ci.nodejs.org/job/node-test-pull-request/68051/), [https://github.com/nodejs/node/pull/59141/](https://ci.nodejs.org/job/node-test-pull-request/68056/), [https://github.com/nodejs/node/pull/59098/](https://ci.nodejs.org/job/node-test-pull-request/68070/), [https://github.com/nodejs/node/pull/59148/](https://ci.nodejs.org/job/node-test-pull-request/68078/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19446/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19440/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59414/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68021/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68078/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19446/console">Example</a></summary>

```
not ok 1762 parallel/test-http-keep-alive-empty-line
  ---
  duration_ms: 7065.73600
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:92
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    '408' !== '404'
    
        at Socket.<anonymous> (file:///home/iojs/build/workspace/node-test-commit-arm-debug/test/parallel/test-http-keep-alive-empty-line.mjs:44:16)
        at Socket.emit (node:events:507:28)
        at addChunk (node:internal/streams/readable:559:12)
        at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
        at Readable.push (node:internal/streams/readable:390:5)
        at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: '408',
      expected: '404',
      operator: 'strictEqual'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-files_watcher</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/58674/](https://ci.nodejs.org/job/node-test-pull-request/68052/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/68058/), [https://github.com/nodejs/node/pull/59134/](https://ci.nodejs.org/job/node-test-pull-request/68060/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68065/), [https://github.com/nodejs/node/pull/58966/](https://ci.nodejs.org/job/node-test-pull-request/68073/), [https://github.com/nodejs/node/pull/59148/](https://ci.nodejs.org/job/node-test-pull-request/68091/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58190/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68052/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68091/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58190/console">Example</a></summary>

```
not ok 3829 parallel/test-watch-mode-files_watcher
  ---
  duration_ms: 1701.55500
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should debounce changes'
    Location: test/parallel/test-watch-mode-files_watcher.mjs:82:3
    Error: ENOSPC: System limit for number of file watchers reached, watch '/home/iojs/build/.tmp.3814/file2'
        at FSWatcher.<computed> (node:internal/fs/watchers:254:19)
        at watch (node:fs:2510:36)
        at FilesWatcher.watchPath (node:internal/watch_mode/files_watcher:117:21)
        at FilesWatcher.filterFile (node:internal/watch_mode/files_watcher:136:12)
        at TestContext.<anonymous> (file:///home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/parallel/test-watch-mode-files_watcher.mjs:85:13)
        at Test.runInAsyncScope (node:async_hooks:213:14)
        at Test.run (node:internal/test_runner/test:1081:25)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Suite.processPendingSub...
```
</details>

-------

| Reason | <code>sequential/test-fs-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/58674/](https://ci.nodejs.org/job/node-test-pull-request/68052/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/68058/), [https://github.com/nodejs/node/pull/59134/](https://ci.nodejs.org/job/node-test-pull-request/68060/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68065/), [https://github.com/nodejs/node/pull/58966/](https://ci.nodejs.org/job/node-test-pull-request/68073/), [https://github.com/nodejs/node/pull/59148/](https://ci.nodejs.org/job/node-test-pull-request/68091/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58190/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68052/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68091/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58190/console">Example</a></summary>

```
not ok 4541 sequential/test-fs-watch
  ---
  duration_ms: 177.62800
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/fs/watchers:262
        throw error;
        ^
    
    Error: ENOENT: no such file or directory, watch '/home/iojs/build/.tmp.4540/watch.txt'
        at FSWatcher.<computed> (node:internal/fs/watchers:254:19)
        at Object.watch (node:fs:2510:36)
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/sequential/test-fs-watch.js:61:22)
        at Module._compile (node:internal/modules/cjs/loader:1722:14)
        at Object..js (node:internal/modules/cjs/loader:1854:10)
        at Module.load (node:internal/modules/cjs/loader:1454:32)
        at Module._load (node:internal/modules/cjs/loader:1274:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:236:24)
        at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5) {
      ...
```
</details>

-------

| Reason | <code>es-module/test-vm-contextified-script-leak</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59093/](https://ci.nodejs.org/job/node-test-pull-request/68015/), [https://github.com/nodejs/node/pull/58713/](https://ci.nodejs.org/job/node-test-pull-request/68020/), [https://github.com/nodejs/node/pull/59059/](https://ci.nodejs.org/job/node-test-pull-request/68054/), [https://github.com/nodejs/node/pull/59086/](https://ci.nodejs.org/job/node-test-pull-request/68055/), [https://github.com/nodejs/node/pull/59129/](https://ci.nodejs.org/job/node-test-pull-request/68082/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35574/console), [test-azure_msft-win11_vs2022-arm64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35546/console), [test-azure_msft-win11_vs2022-arm64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35477/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68015/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68082/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35574/console">Example</a></summary>

```
not ok 77 es-module/test-vm-contextified-script-leak
  ---
  duration_ms: 295.00000
  severity: crashed
  exitcode: 3221225477
  stack: |-
    Created 128 objects
    Created 256 objects
    Found finalized object at 289, stop testing
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-to-web</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59067/](https://ci.nodejs.org/job/node-test-pull-request/68003/), [https://github.com/nodejs/node/pull/59020/](https://ci.nodejs.org/job/node-test-pull-request/68026/), [https://github.com/nodejs/node/pull/59059/](https://ci.nodejs.org/job/node-test-pull-request/68037/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/68058/), [https://github.com/nodejs/node/pull/59144/](https://ci.nodejs.org/job/node-test-pull-request/68080/)) |
| Appeared | [test-osuosl-rhel9-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/59947/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50585/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/59910/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68003/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68080/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/59947/console">Example</a></summary>

```
not ok 4204 parallel/test-stream-readable-to-web
  ---
  duration_ms: 120016.65900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>pummel/test-fs-watch-non-recursive</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58674/](https://ci.nodejs.org/job/node-test-pull-request/68052/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/68058/), [https://github.com/nodejs/node/pull/59134/](https://ci.nodejs.org/job/node-test-pull-request/68060/), [https://github.com/nodejs/node/pull/58966/](https://ci.nodejs.org/job/node-test-pull-request/68073/), [https://github.com/nodejs/node/pull/59148/](https://ci.nodejs.org/job/node-test-pull-request/68091/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58190/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68052/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68091/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58190/console">Example</a></summary>

```
not ok 4211 pummel/test-fs-watch-non-recursive
  ---
  duration_ms: 185.30600
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/fs/watchers:262
        throw error;
        ^
    
    Error: ENOSPC: System limit for number of file watchers reached, watch '/home/iojs/build/.tmp.4210'
        at FSWatcher.<computed> (node:internal/fs/watchers:254:19)
        at Object.watch (node:fs:2510:36)
        at doWatch (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/pummel/test-fs-watch-non-recursive.js:42:22)
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/pummel/test-fs-watch-non-recursive.js:60:3)
        at Module._compile (node:internal/modules/cjs/loader:1722:14)
        at Object..js (node:internal/modules/cjs/loader:1854:10)
        at Module.load (node:internal/modules/cjs/loader:1454:32)
        at Module._load (node:internal/modules/cjs/loader:1274:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
...
```
</details>

-------

| Reason | <code>sequential/test-watch-mode-watch-flags</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58674/](https://ci.nodejs.org/job/node-test-pull-request/68052/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/68058/), [https://github.com/nodejs/node/pull/59134/](https://ci.nodejs.org/job/node-test-pull-request/68060/), [https://github.com/nodejs/node/pull/58966/](https://ci.nodejs.org/job/node-test-pull-request/68073/), [https://github.com/nodejs/node/pull/59148/](https://ci.nodejs.org/job/node-test-pull-request/68091/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58190/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68052/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68091/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58190/console">Example</a></summary>

```
not ok 4613 sequential/test-watch-mode-watch-flags
  ---
  duration_ms: 659.82500
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: '`--watch-path` args without `=` used alongside `--watch` should not make it into the script'
    Location: test/sequential/test-watch-mode-watch-flags.mjs:76:3
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    
    + 'node:internal/fs/recursive_watch:217\n' +
    +   '        throw error;\n' +
    +   '        ^\n' +
    +   '\n' +
    +   "Error: ENOENT: no such file or directory, watch '/home/iojs/build/.tmp.4612/project-watch-watch-path-args/1.js'\n" +
    +   '    at FSWatcher.<computed> (node:internal/fs/watchers:254:19)\n' +
    +   '    at watch (node:fs:2510:36)\n' +
    +   '    at #watchFile (node:internal/fs/recursive_watch:163:21)\n' +
    +   '    at [kFSWatchStart] (node:internal/fs/recursive_watch:210:22)\n' +
    +   '    at watch (node:fs:2507:36)\n' +
    +   '    at FilesWatcher.watchPath (node:int...
```
</details>

-------

| Reason | <code>es-module/test-esm-wasm</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-digitalocean-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65695/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51793/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51793/console), [test-digitalocean-alpine321_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65694/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51792/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65695/console">Example</a></summary>

```
not ok 4111 es-module/test-esm-wasm
  ---
  duration_ms: 120014.23400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>module-hooks/test-module-hooks-import-wasm</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-digitalocean-alpine321_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console">Example</a></summary>

```
not ok 3984 module-hooks/test-module-hooks-import-wasm
  ---
  duration_ms: 120062.84800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-blob</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59086/](https://ci.nodejs.org/job/node-test-pull-request/68055/), [https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50607/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51792/console), [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/65672/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68055/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 889 parallel/test-blob
  ---
  duration_ms: 120062.94500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-server-headers-timeout-keepalive</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59094/](https://ci.nodejs.org/job/node-test-pull-request/68009/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68057/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/68058/), [https://github.com/nodejs/node/pull/59148/](https://ci.nodejs.org/job/node-test-pull-request/68078/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19446/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59419/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68009/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68078/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19446/console">Example</a></summary>

```
not ok 1951 parallel/test-http-server-headers-timeout-keepalive
  ---
  duration_ms: 36917.45400
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:92
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    
    + 'HTTP/1.1 200 OK\r\n' +
    +   'Content-Type: text/plain\r\n' +
    +   'Date: Mon, 21 Jul 2025 19:09:49 GMT\r\n' +
    +   'Connection: close\r\n' +
    +   'Transfer-Encoding: chunked\r\n' +
    +   '\r\n' +
    +   '0\r\n' +
    +   '\r\n'
    - 'HTTP/1.1 408 Request Timeout\r\nConnection: close\r\n\r\n'
    
        at Socket.<anonymous> (/home/iojs/build/workspace/node-test-commit-arm-debug/test/parallel/test-http-server-headers-timeout-keepalive.js:82:12)
        at Socket.<anonymous> (/home/iojs/build/workspace/node-test-commit-arm-debug/test/common/index.js:437:15)
        at Socket.emit (node:events:519:35)
        at endReadableNT (node:internal/streams/readable:1701:12)
        at proc...
```
</details>

-------

| Reason | <code>parallel/test-messageevent-brandcheck</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51793/console), [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/65694/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50607/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 2363 parallel/test-messageevent-brandcheck
  ---
  duration_ms: 120009.26500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-websocket</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/51793/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 3727 parallel/test-websocket
  ---
  duration_ms: 120060.02300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59020/](https://ci.nodejs.org/job/node-test-pull-request/68023/), [https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/59098/](https://ci.nodejs.org/job/node-test-pull-request/68090/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51794/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51791/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51737/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68023/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68090/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51794/console">Example</a></summary>

```
not ok 4632 sequential/test-tls-session-timeout
  ---
  duration_ms: 210.95300
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:92
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at /home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:150:16
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:134:7)
        at ChildProcess.emit (node:events:507:28)
        at ChildProcess._handle.onexit (node:internal/child_process:293:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>wasi/test-wasi-exitcode</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51793/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51793/console), [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/65694/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50607/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51792/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51792/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 4042 wasi/test-wasi-exitcode
  ---
  duration_ms: 120022.50000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    Testing with --turbo-fast-api-calls: exitcode
    Testing with --no-turbo-fast-api-calls: exitcode
    Testing with --turbo-fast-api-calls: exitcode
  ...

```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-handshake-failure</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59094/](https://ci.nodejs.org/job/node-test-pull-request/68009/), [https://github.com/nodejs/node/pull/59141/](https://ci.nodejs.org/job/node-test-pull-request/68056/), [https://github.com/nodejs/node/pull/59148/](https://ci.nodejs.org/job/node-test-pull-request/68078/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19446/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19430/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59383/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68009/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68078/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19446/console">Example</a></summary>

```
not ok 27 client-proxy/test-https-proxy-request-handshake-failure
  ---
  duration_ms: 10890.37000
  severity: fail
  exitcode: 1
  stack: |-
    [CLOSE] 0 null
    [STDERR] Request timed out
    Request Error Error [ERR_PROXY_TUNNEL]: Connection to establish proxy tunnel timed out after 1000ms
        at Socket.onTimeout (node:https:373:19)
        at Object.onceWrapper (node:events:621:28)
        at Socket.emit (node:events:519:35)
        at Socket._onTimeout (node:net:604:8)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      code: 'ERR_PROXY_TUNNEL',
      proxyTunnelTimeout: 1000
    }
    
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /UNABLE_TO_VERIFY_LEAF_SIGNATURE/. Input:
    
    'Request timed out\n' +
      'Request Error Error [ERR_PROXY_TUNNEL]: Connection to establish proxy tunnel timed out after ...
```
</details>

-------

| Reason | <code>es-module/test-esm-extensionless-esm-and-wasm</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 3891 es-module/test-esm-extensionless-esm-and-wasm
  ---
  duration_ms: 120140.14700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    executed
    executed
  ...

```
</details>

-------

| Reason | <code>es-module/test-esm-type-flag-package-scopes</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-digitalocean-alpine321_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console), [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65694/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51792/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console">Example</a></summary>

```
not ok 4102 es-module/test-esm-type-flag-package-scopes
  ---
  duration_ms: 120093.22800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    executed
    executed
    executed
    executed
    (node:2964585) ExperimentalWarning: Importing WebAssembly modules is an experimental feature and might change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
  ...

```
</details>

-------

| Reason | <code>parallel/test-blocklist-clone</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51793/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51793/console), [test-digitalocean-alpine321_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65694/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console">Example</a></summary>

```
not ok 671 parallel/test-blocklist-clone
  ---
  duration_ms: 120023.68200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-crypto-x509</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/51793/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50607/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console">Example</a></summary>

```
not ok 1338 parallel/test-crypto-x509
  ---
  duration_ms: 120080.01800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-diagnostics-channel-module-import</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 1353 parallel/test-diagnostics-channel-module-import
  ---
  duration_ms: 120056.12300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-eventsource</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 1476 parallel/test-eventsource
  ---
  duration_ms: 120026.22800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-inspector-network-fetch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59093/](https://ci.nodejs.org/job/node-test-pull-request/68010/), [https://github.com/nodejs/node/pull/58842/](https://ci.nodejs.org/job/node-test-pull-request/68029/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/68031/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35500/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022_clang/35465/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68010/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68031/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35500/console">Example</a></summary>

```
not ok 566 parallel/test-inspector-network-fetch
  ---
  duration_ms: 667.98100
  severity: fail
  exitcode: 3221226505
  stack: |-
    Debugger listening on ws://127.0.0.1:52116/a75c730f-690f-454d-8d94-2a5c123efad1
    For help, see: https://nodejs.org/en/docs/inspector
    node:internal/deps/undici/undici:15422
          Error.captureStackTrace(err);
                ^
    
    TypeError: fetch failed
        at node:internal/deps/undici/undici:15422:13
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async testRequest (d:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-inspector-network-fetch.js:153:3)
        at async testNetworkInspection (d:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-inspector-network-fetch.js:198:3)
        at async Server.<anonymous> (d:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-inspector-network-fetch.js:212:7) {
      [cause]: [Error: 881D0000:error:0A00010B:SSL ...
```
</details>

-------

| Reason | <code>parallel/test-messaging-marktransfermode</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 2365 parallel/test-messaging-marktransfermode
  ---
  duration_ms: 120088.71800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    (node:3634837) internal/test/transfer: These APIs are for internal testing only. Do not use them.
    (Use `node --trace-warnings ...` to show where the warning was created)
  ...

```
</details>

-------

| Reason | <code>parallel/test-node-output-eval</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50607/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 2476 parallel/test-node-output-eval
  ---
  duration_ms: 120030.34800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-context</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console), [test-digitalocean-alpine321_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65694/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 2491 parallel/test-repl-context
  ---
  duration_ms: 120013.35900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-no-terminal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51793/console), [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65694/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51793/console">Example</a></summary>

```
not ok 2620 parallel/test-repl-no-terminal
  ---
  duration_ms: 120042.56300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    > 
    Error: Could not open history file.
    REPL session history will not be persisted.
    [1G[0J> [3G
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-preview</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/57038/](https://ci.nodejs.org/job/node-test-pull-request/68032/), [https://github.com/nodejs/node/pull/59141/](https://ci.nodejs.org/job/node-test-pull-request/68056/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/68058/)) |
| Appeared | [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59419/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59418/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68032/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68058/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59419/console">Example</a></summary>

```
not ok 2929 parallel/test-repl-preview
  ---
  duration_ms: 4707.14500
  severity: fail
  exitcode: 1
  stack: |-
    Testing foo
    Testing foo
    Testing foo
    Testing foo
    Testing foo
    Testing koo
    Testing koo
    Testing koo
    Testing a
    Testing a
    Testing a
    Testing  { b: 1 }['b'] === 1
    Testing  { b: 1 }['b'] === 1
    Testing  { b: 1 }['b'] === 1
    Testing { b: 1 }['b'] === 1;
    Testing { b: 1 }['b'] === 1;
    Testing { b: 1 }['b'] === 1;
    Testing koo
    Testing koo
    Testing { a: true }
    Testing { a: true }
    Testing { a: true }
    Testing { a: true };
    Testing { a: true };
    Testing { a: true };
    Testing  	 { a: true};
    Testing  	 { a: true};
    Testing  	 { a: true};
    Testing 1n + 2n
    Testing 1n + 2n
    Testing 1n + 2n
    Testing {};1
    Testing {};1
    Testing {};1
    Testing a
    Testing a
    Testing  { b: 1 }['b'] === 1
    Testing  { b: 1 }['b'] === 1
    Testing { b: 1 }['b'] === 1;
    Testing { b: 1 }['b'] === 1;
    Testing...
```
</details>

-------

| Reason | <code>parallel/test-repl-setprompt</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51793/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 2540 parallel/test-repl-setprompt
  ---
  duration_ms: 120113.94900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-syntax-error-stack</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console), [test-digitalocean-alpine321_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65694/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console">Example</a></summary>

```
not ok 3663 parallel/test-repl-syntax-error-stack
  ---
  duration_ms: 120123.04700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-uncaught-exception-async</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-digitalocean-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65695/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/51793/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65695/console">Example</a></summary>

```
not ok 2627 parallel/test-repl-uncaught-exception-async
  ---
  duration_ms: 120038.99700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-underscore</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51793/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50607/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 2971 parallel/test-repl-underscore
  ---
  duration_ms: 120106.65200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/57038/](https://ci.nodejs.org/job/node-test-pull-request/68032/), [https://github.com/nodejs/node/pull/58842/](https://ci.nodejs.org/job/node-test-pull-request/68041/), [https://github.com/nodejs/node/pull/59141/](https://ci.nodejs.org/job/node-test-pull-request/68056/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19430/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68032/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68056/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19430/console">Example</a></summary>

```
not ok 3055 parallel/test-runner-output
  ---
  duration_ms: 67862.69000
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'test-runner/output/timeout_in_before_each_should_not_affect_further_tests.js'
    Location: test/parallel/test-runner-output.mjs:346:5
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    ... Skipped lines
    
      'gonna timeout\n' +
        'TAP version 13\n' +
        'not gonna timeout\n' +
        'before each test second 2\n' +
        'after each test first 0\n' +
    ...

```
</details>

-------

| Reason | <code>parallel/test-socketaddress</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51793/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 3398 parallel/test-socketaddress
  ---
  duration_ms: 120028.09300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    (node:3646819) internal/test/binding: These APIs are for internal testing only. Do not use them.
    (Use `node --trace-warnings ...` to show where the warning was created)
  ...

```
</details>

-------

| Reason | <code>parallel/test-webstreams-clone-unref</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65694/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 3746 parallel/test-webstreams-clone-unref
  ---
  duration_ms: 120059.80900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-debug-prompt</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-digitalocean-alpine321_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65694/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 4412 sequential/test-debug-prompt
  ---
  duration_ms: 120061.53400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59042/](https://ci.nodejs.org/job/node-test-pull-request/68035/), [https://github.com/nodejs/node/pull/58185/](https://ci.nodejs.org/job/node-test-pull-request/68083/), [https://github.com/nodejs/node/pull/59098/](https://ci.nodejs.org/job/node-test-pull-request/68090/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51794/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51791/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51790/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50562/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68035/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68090/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51794/console">Example</a></summary>

```
not ok 4270 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 7302.65700
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:272
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>wasi/test-wasi-io</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51793/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51793/console">Example</a></summary>

```
not ok 4079 wasi/test-wasi-io
  ---
  duration_ms: 120047.36700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    Testing with --turbo-fast-api-calls: freopen
    Testing with --no-turbo-fast-api-calls: freopen
    Testing with --turbo-fast-api-calls: read_file
    Testing with --no-turbo-fast-api-calls: read_file
  ...

```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-connection-refused</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59059/](https://ci.nodejs.org/job/node-test-pull-request/68037/), [https://github.com/nodejs/node/pull/59098/](https://ci.nodejs.org/job/node-test-pull-request/68070/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35567/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51749/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68037/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68070/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35567/console">Example</a></summary>

```
not ok 25 client-proxy/test-https-proxy-request-connection-refused
  ---
  duration_ms: 716.99900
  severity: fail
  exitcode: 1
  stack: |-
    [CLOSE] 0 null
    [STDERR] Request Error Error [ERR_PROXY_TUNNEL]: Connection to establish proxy tunnel ended unexpectedly
        at Socket.onProxyEnd (node:https:289:17)
        at Socket.emit (node:events:519:35)
        at endReadableNT (node:internal/streams/readable:1701:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
      code: 'ERR_PROXY_TUNNEL'
    }
    
    [STDERR] Request Error Error [ERR_PROXY_TUNNEL]: Connection to establish proxy tunnel ended unexpectedly
        at Socket.onProxyEnd (node:https:289:17)
        at Socket.emit (node:events:519:35)
        at endReadableNT (node:internal/streams/readable:1701:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
      code: 'ERR_PROXY_TUNNEL'
    }
    
    node:internal/modules/run_main:107
        triggerUncaughtExce...
```
</details>

-------

| Reason | <code>es-module/test-esm-type-flag-loose-files</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/)) |
| Appeared | [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65694/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65694/console">Example</a></summary>

```
not ok 409 es-module/test-esm-type-flag-loose-files
  ---
  duration_ms: 120082.88400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>es-module/test-typescript</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 3942 es-module/test-typescript
  ---
  duration_ms: 120037.44800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>es-module/test-wasm-memory-out-of-bound</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console">Example</a></summary>

```
not ok 4103 es-module/test-wasm-memory-out-of-bound
  ---
  duration_ms: 120052.39800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>es-module/test-wasm-simple</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-digitalocean-alpine321_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console), [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65694/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console">Example</a></summary>

```
not ok 4107 es-module/test-wasm-simple
  ---
  duration_ms: 120093.04700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68057/), [https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68063/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18021/console), [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18018/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68057/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68063/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18021/console">Example</a></summary>

```
not ok 1238 parallel/test-async-context-frame
  ---
  duration_ms: 360498.36100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-child-process-prototype-tampering</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59020/](https://ci.nodejs.org/job/node-test-pull-request/68022/), [https://github.com/nodejs/node/pull/58497/](https://ci.nodejs.org/job/node-test-pull-request/68081/)) |
| Appeared | [test-linuxonecc-rhel9-s390x-3](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50603/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50550/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68022/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68081/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50603/console">Example</a></summary>

```
not ok 666 parallel/test-child-process-prototype-tampering
  ---
  duration_ms: 409.02800
  severity: fail
  exitcode: 1
  stack: |-
    Mismatched noop function calls. Expected exactly 1, actual 2.
        at Module.mustCall (/home/iojs/build/workspace/node-test-commit-linuxone/test/common/index.js:395:10)
        at file:///home/iojs/build/workspace/node-test-commit-linuxone/test/parallel/test-child-process-prototype-tampering.mjs:67:36
        at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
        at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:669:26)
        at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
    pwd: invalid option -- ' '
    Try 'pwd --help' for more information.
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-client-close-with-default-agent</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59141/](https://ci.nodejs.org/job/node-test-pull-request/68056/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68057/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18018/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19430/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68056/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68057/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18018/console">Example</a></summary>

```
not ok 1579 parallel/test-http-client-close-with-default-agent
  ---
  duration_ms: 3050.46400
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:142
      throw err;
      ^
    
    AssertionError [ERR_ASSERTION]: function should not have been called at /home/iojs/build/workspace/node-test-binary-armv7l/test/parallel/test-http-client-close-with-default-agent.js:23
        at Timeout.mustNotCall [as _onTimeout] (/home/iojs/build/workspace/node-test-binary-armv7l/test/common/index.js:495:12)
        at listOnTimeout (node:internal/timers:588:17)
        at process.processTimers (node:internal/timers:523:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: undefined,
      operator: 'fail'
    }
    
    Node.js v22.17.2-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-definecommand</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51793/console">Example</a></summary>

```
not ok 2507 parallel/test-repl-definecommand
  ---
  duration_ms: 120038.74400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-domain</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-digitalocean-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65695/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65695/console">Example</a></summary>

```
not ok 2617 parallel/test-repl-domain
  ---
  duration_ms: 125841.65300
  severity: fail
  stack: |-
    timeout
    ok
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-function-definition-edge-case</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51793/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51792/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51792/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51793/console">Example</a></summary>

```
not ok 3614 parallel/test-repl-function-definition-edge-case
  ---
  duration_ms: 120072.50300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-inspector</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-digitalocean-alpine321_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console">Example</a></summary>

```
not ok 2617 parallel/test-repl-inspector
  ---
  duration_ms: 120653.42400
  severity: fail
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-load-multiline</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 2518 parallel/test-repl-load-multiline
  ---
  duration_ms: 120094.75100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-load-multiline-no-trailing-newline</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58188/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/51793/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58188/console">Example</a></summary>

```
not ok 3894 parallel/test-repl-load-multiline-no-trailing-newline
  ---
  duration_ms: 120080.59700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-multiline</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/)) |
| Appeared | [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65694/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65694/console">Example</a></summary>

```
not ok 3008 parallel/test-repl-multiline
  ---
  duration_ms: 120015.90600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-null</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 2526 parallel/test-repl-null
  ---
  duration_ms: 120004.87500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    > > 
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-null-thrown</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console">Example</a></summary>

```
not ok 2898 parallel/test-repl-null-thrown
  ---
  duration_ms: 120111.48500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-pretty-stack-custom-writer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-digitalocean-alpine321_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51792/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console">Example</a></summary>

```
not ok 2627 parallel/test-repl-pretty-stack-custom-writer
  ---
  duration_ms: 120050.45900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-require-cache</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console">Example</a></summary>

```
not ok 2936 parallel/test-repl-require-cache
  ---
  duration_ms: 120056.14400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    > 
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-tab</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51793/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 2580 parallel/test-repl-tab
  ---
  duration_ms: 120105.96900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-tab-complete-crash</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console">Example</a></summary>

```
not ok 2695 parallel/test-repl-tab-complete-crash
  ---
  duration_ms: 120097.97300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-tab-complete-on-editor-mode</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51793/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51793/console">Example</a></summary>

```
not ok 3290 parallel/test-repl-tab-complete-on-editor-mode
  ---
  duration_ms: 120099.72100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-uncaught-exception</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-digitalocean-alpine321_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console">Example</a></summary>

```
not ok 2652 parallel/test-repl-uncaught-exception
  ---
  duration_ms: 120086.38300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-structuredClone-global</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/65695/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/65695/console">Example</a></summary>

```
not ok 3771 parallel/test-structuredClone-global
  ---
  duration_ms: 120028.85200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-webstream-structured-clone-no-leftovers</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51793/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51793/console">Example</a></summary>

```
not ok 4112 parallel/test-webstream-structured-clone-no-leftovers
  ---
  duration_ms: 120103.50000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-worker-broadcastchannel-wpt</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-ibm-rhel8-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/65695/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/65695/console">Example</a></summary>

```
not ok 4099 parallel/test-worker-broadcastchannel-wpt
  ---
  duration_ms: 120029.99100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-worker-message-event</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51793/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51793/console), [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65694/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50607/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51793/console">Example</a></summary>

```
not ok 4099 parallel/test-worker-message-event
  ---
  duration_ms: 120101.33900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-worker-message-mark-as-uncloneable</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51793/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51793/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50607/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51793/console">Example</a></summary>

```
not ok 4101 parallel/test-worker-message-mark-as-uncloneable
  ---
  duration_ms: 120023.26400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-worker-message-port-transfer-self</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68087/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-digitalocean-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65695/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50607/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68087/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65695/console">Example</a></summary>

```
not ok 4102 parallel/test-worker-message-port-transfer-self
  ---
  duration_ms: 120115.48600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>wasi/test-return-on-exit</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68088/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51793/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68088/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/51793/console">Example</a></summary>

```
not ok 4076 wasi/test-return-on-exit
  ---
  duration_ms: 120016.73200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    (node:2587325) ExperimentalWarning: WASI is an experimental feature and might change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
  ...

```
</details>

-------

| Reason | <code>wasi/test-wasi-symlinks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68086/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-digitalocean-alpine321_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50608/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51792/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68086/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65695/console">Example</a></summary>

```
not ok 3969 wasi/test-wasi-symlinks
  ---
  duration_ms: 120085.92700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    executing create_symlink
    (node:2960659) ExperimentalWarning: WASI is an experimental feature and might change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
    fd_prestat_get(3, 71064)
    fd_prestat_dir_name(3, 71088, 8)
    fd_prestat_get(4, 71064)
    fd_prestat_dir_name(4, 71088, 4)
    fd_prestat_get(5, 71064)
    path_symlink(1053, 21, 3, 1095, 16)
    path_readlink(3, 1095, 16, 70928, 128, 70892)
    fd_fdstat_get(3, 70872)
    path_open(3, 1, 1095, 16, 0, 264240830, 268435455, 0, 70868)
    fd_read(5, 70872, 1, 70868)
    fd_read(5, 70872, 1, 70868)
    fd_fdstat_get(1, 71048)
    fd_write(1, 71056, 2, 71052)
    
    executing follow_symlink
    (node:2960673) ExperimentalWarning: WASI is an experimental feature and might change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
    fd_pres...
```
</details>

-------


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 14 ([https://github.com/nodejs/node/pull/59011/](https://ci.nodejs.org/job/node-test-pull-request/67996/), [https://github.com/nodejs/node/pull/59110/](https://ci.nodejs.org/job/node-test-pull-request/68008/), [https://github.com/nodejs/node/pull/59093/](https://ci.nodejs.org/job/node-test-pull-request/68015/), [https://github.com/nodejs/node/pull/59086/](https://ci.nodejs.org/job/node-test-pull-request/68016/), [https://github.com/nodejs/node/pull/59013/](https://ci.nodejs.org/job/node-test-pull-request/68018/), [https://github.com/nodejs/node/pull/58713/](https://ci.nodejs.org/job/node-test-pull-request/68020/), [https://github.com/nodejs/node/pull/59020/](https://ci.nodejs.org/job/node-test-pull-request/68024/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/68028/), [https://github.com/nodejs/node/pull/58842/](https://ci.nodejs.org/job/node-test-pull-request/68029/), [https://github.com/nodejs/node/pull/58750/](https://ci.nodejs.org/job/node-test-pull-request/68031/), [https://github.com/nodejs/node/pull/59059/](https://ci.nodejs.org/job/node-test-pull-request/68042/), [https://github.com/nodejs/node/pull/59141/](https://ci.nodejs.org/job/node-test-pull-request/68069/), [https://github.com/nodejs/node/pull/58966/](https://ci.nodejs.org/job/node-test-pull-request/68073/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68089/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/35582/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50536/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67996/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/35582/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59059/](https://ci.nodejs.org/job/node-test-pull-request/68033/), [https://github.com/nodejs/node/pull/59072/](https://ci.nodejs.org/job/node-test-pull-request/68045/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58158/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51746/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68033/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68045/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58158/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/59011/](https://ci.nodejs.org/job/node-test-pull-request/67996/), [https://github.com/nodejs/node/pull/58666/](https://ci.nodejs.org/job/node-test-pull-request/68002/), [https://github.com/nodejs/node/pull/59094/](https://ci.nodejs.org/job/node-test-pull-request/68009/), [https://github.com/nodejs/node/pull/59093/](https://ci.nodejs.org/job/node-test-pull-request/68015/), [https://github.com/nodejs/node/pull/59086/](https://ci.nodejs.org/job/node-test-pull-request/68016/), [https://github.com/nodejs/node/pull/58713/](https://ci.nodejs.org/job/node-test-pull-request/68020/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68057/), [https://github.com/nodejs/node/pull/59134/](https://ci.nodejs.org/job/node-test-pull-request/68060/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/65678/console), [test-equinix-ubuntu2204_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19401/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67996/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68060/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/65678/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1240)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1278)
```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/59086/](https://ci.nodejs.org/job/node-test-pull-request/68016/), [https://github.com/nodejs/node/pull/58842/](https://ci.nodejs.org/job/node-test-pull-request/68041/), [https://github.com/nodejs/node/pull/59134/](https://ci.nodejs.org/job/node-test-pull-request/68060/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68064/), [https://github.com/nodejs/node/pull/59059/](https://ci.nodejs.org/job/node-test-pull-request/68067/), [https://github.com/nodejs/node/pull/59098/](https://ci.nodejs.org/job/node-test-pull-request/68090/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51794/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51778/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51773/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68016/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68090/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51794/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59011/](https://ci.nodejs.org/job/node-test-pull-request/67994/), [https://github.com/nodejs/node/pull/58822/](https://ci.nodejs.org/job/node-test-pull-request/67997/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-pull-request/67997/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67994/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67997/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/67997/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

-------

