Failures in [node-test-pull-request/68740](https://ci.nodejs.org/job/node-test-pull-request/68740/) to [node-test-pull-request/68839](https://ci.nodejs.org/job/node-test-pull-request/68839/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-08-24.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-08-24 00:12 | 1       | 0       | 34       | 10      | 55      | 0.00%      |


### JSTest Failure

| Reason | <code>parallel/test-max-old-space-size-percentage</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 11 ([https://github.com/nodejs/node/pull/59567/](https://ci.nodejs.org/job/node-test-pull-request/68781/), [https://github.com/nodejs/node/pull/59569/](https://ci.nodejs.org/job/node-test-pull-request/68791/), [https://github.com/nodejs/node/pull/59570/](https://ci.nodejs.org/job/node-test-pull-request/68804/), [https://github.com/nodejs/node/pull/59571/](https://ci.nodejs.org/job/node-test-pull-request/68807/), [https://github.com/nodejs/node/pull/59350/](https://ci.nodejs.org/job/node-test-pull-request/68809/), [https://github.com/nodejs/node/pull/59527/](https://ci.nodejs.org/job/node-test-pull-request/68817/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68818/), [https://github.com/nodejs/node/pull/59579/](https://ci.nodejs.org/job/node-test-pull-request/68824/), [https://github.com/nodejs/node/pull/58797/](https://ci.nodejs.org/job/node-test-pull-request/68833/), [https://github.com/nodejs/node/pull/59595/](https://ci.nodejs.org/job/node-test-pull-request/68838/), [https://github.com/nodejs/node/pull/58155/](https://ci.nodejs.org/job/node-test-pull-request/68839/)) |
| Appeared | [test-rackspace-win2016_vs2015-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/36452/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/60052/console), [test-equinix-debian11_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18537/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18537/console), [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/36439/console), [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18528/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68781/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68839/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/36452/console">Example</a></summary>

```
not ok 630 parallel/test-max-old-space-size-percentage
  ---
  duration_ms: 3351.98800
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:272
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: 50% heap size should be roughly half of 100% (got 1.11, expected ~0.5)
        at Object.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-max-old-space-size-percentage.js:101:1)
        at Module._compile (node:internal/modules/cjs/loader:1706:14)
        at Object..js (node:internal/modules/cjs/loader:1839:10)
        at Module.load (node:internal/modules/cjs/loader:1441:32)
        at Function._load (node:internal/modules/cjs/loader:1263:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
        at node:internal/main/run_main_module:36:49 {
      generatedMess...
```
</details>

-------

| Reason | <code>parallel/test-fastutf8stream-flush-mocks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/59567/](https://ci.nodejs.org/job/node-test-pull-request/68781/), [https://github.com/nodejs/node/pull/59570/](https://ci.nodejs.org/job/node-test-pull-request/68804/), [https://github.com/nodejs/node/pull/59571/](https://ci.nodejs.org/job/node-test-pull-request/68807/), [https://github.com/nodejs/node/pull/59350/](https://ci.nodejs.org/job/node-test-pull-request/68809/), [https://github.com/nodejs/node/pull/59527/](https://ci.nodejs.org/job/node-test-pull-request/68817/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68818/), [https://github.com/nodejs/node/pull/59579/](https://ci.nodejs.org/job/node-test-pull-request/68824/), [https://github.com/nodejs/node/pull/58797/](https://ci.nodejs.org/job/node-test-pull-request/68833/), [https://github.com/nodejs/node/pull/59595/](https://ci.nodejs.org/job/node-test-pull-request/68838/), [https://github.com/nodejs/node/pull/58155/](https://ci.nodejs.org/job/node-test-pull-request/68839/)) |
| Appeared | [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/36452/console), [test-rackspace-win2016_vs2015-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/36442/console), [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/36439/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68781/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68839/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/36452/console">Example</a></summary>

```
not ok 317 parallel/test-fastutf8stream-flush-mocks
  ---
  duration_ms: 915.04400
  severity: fail
  exitcode: 1
  stack: |-
    Can't clean tmpdir: C:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.301
    Files blocking: [
      'fastutf8stream-5852-1755947023994-0.log',
      'fastutf8stream-5852-1755947024001-2.log'
    ]
    
    C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:80
        throw e;
        ^
    
    Error: ENOTEMPTY: directory not empty, rmdir 'C:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.301'
        at Object.rmdirSync (node:fs:1206:11)
        at _rmdirSync (node:internal/fs/rimraf:261:21)
        at rimrafSync (node:internal/fs/rimraf:194:7)
        at Object.rmSync (node:fs:1252:10)
        at rmSync (C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:31:8)
        at onexit (C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:65:5)
        at process.<anonymous> (C:\workspace\no...
```
</details>

-------

| Reason | <code>parallel/test-fastutf8stream-sync</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/59567/](https://ci.nodejs.org/job/node-test-pull-request/68781/), [https://github.com/nodejs/node/pull/59570/](https://ci.nodejs.org/job/node-test-pull-request/68804/), [https://github.com/nodejs/node/pull/59571/](https://ci.nodejs.org/job/node-test-pull-request/68807/), [https://github.com/nodejs/node/pull/59350/](https://ci.nodejs.org/job/node-test-pull-request/68809/), [https://github.com/nodejs/node/pull/59527/](https://ci.nodejs.org/job/node-test-pull-request/68817/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68818/), [https://github.com/nodejs/node/pull/59579/](https://ci.nodejs.org/job/node-test-pull-request/68824/), [https://github.com/nodejs/node/pull/58797/](https://ci.nodejs.org/job/node-test-pull-request/68833/), [https://github.com/nodejs/node/pull/59595/](https://ci.nodejs.org/job/node-test-pull-request/68838/), [https://github.com/nodejs/node/pull/58155/](https://ci.nodejs.org/job/node-test-pull-request/68839/)) |
| Appeared | [test-azure_msft-win2016_vs2017-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2016-COMPILED_BY-vs2022-x86/36452/console), [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/36442/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68781/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68839/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2016-COMPILED_BY-vs2022-x86/36452/console">Example</a></summary>

```
not ok 314 parallel/test-fastutf8stream-sync
  ---
  duration_ms: 907.01200
  severity: fail
  exitcode: 1
  stack: |-
    Can't clean tmpdir: C:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.304
    Files blocking: [
      'fastutf8stream-4592-1755947030365-2.log',
      'fastutf8stream-4592-1755947030396-7.log'
    ]
    
    C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:80
        throw e;
        ^
    
    Error: ENOTEMPTY: directory not empty, rmdir 'C:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.304'
        at Object.rmdirSync (node:fs:1206:11)
        at _rmdirSync (node:internal/fs/rimraf:261:21)
        at rimrafSync (node:internal/fs/rimraf:194:7)
        at Object.rmSync (node:fs:1252:10)
        at rmSync (C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:31:8)
        at onexit (C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:65:5)
        at process.<anonymous> (C:\workspace\node-test...
```
</details>

-------

| Reason | <code>parallel/test-inspector-network-fetch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/59538/](https://ci.nodejs.org/job/node-test-pull-request/68741/), [https://github.com/nodejs/node/pull/59567/](https://ci.nodejs.org/job/node-test-pull-request/68781/), [https://github.com/nodejs/node/pull/59570/](https://ci.nodejs.org/job/node-test-pull-request/68804/), [https://github.com/nodejs/node/pull/59350/](https://ci.nodejs.org/job/node-test-pull-request/68809/), [https://github.com/nodejs/node/pull/59579/](https://ci.nodejs.org/job/node-test-pull-request/68824/), [https://github.com/nodejs/node/pull/59595/](https://ci.nodejs.org/job/node-test-pull-request/68838/), [https://github.com/nodejs/node/pull/58155/](https://ci.nodejs.org/job/node-test-pull-request/68839/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/36466/console), [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022_clang/36465/console), [test-rackspace-win2019_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022_clang/36448/console), [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/36428/console), [test-rackspace-win2022_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2022-COMPILED_BY-vs2022_clang/36424/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022_clang/36422/console), [test-azure_msft-win11_vs2022-arm64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36357/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68741/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68839/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/36466/console">Example</a></summary>

```
not ok 597 parallel/test-inspector-network-fetch
  ---
  duration_ms: 398.02500
  severity: fail
  exitcode: 1
  stack: |-
    Debugger listening on ws://127.0.0.1:61200/f4f5ebf5-ff64-4ea4-a254-ae2cc658d4fb
    For help, see: https://nodejs.org/en/docs/inspector
    node:internal/deps/undici/undici:15445
          Error.captureStackTrace(err);
                ^
    
    TypeError: fetch failed
        at node:internal/deps/undici/undici:15445:13
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async testRequest (C:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-inspector-network-fetch.js:153:3)
        at async testNetworkInspection (C:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-inspector-network-fetch.js:198:3)
        at async Server.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-inspector-network-fetch.js:212:7) {
      [cause]: [Error: B4170000:error:0A0000C6:SSL routines:...
```
</details>

-------

| Reason | <code>parallel/test-runner-mock-timers-scheduler</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/50353/](https://ci.nodejs.org/job/node-test-pull-request/68746/), [https://github.com/nodejs/node/pull/59491/](https://ci.nodejs.org/job/node-test-pull-request/68754/), [https://github.com/nodejs/node/pull/59455/](https://ci.nodejs.org/job/node-test-pull-request/68759/), [https://github.com/nodejs/node/pull/59350/](https://ci.nodejs.org/job/node-test-pull-request/68767/), [https://github.com/nodejs/node/pull/59464/](https://ci.nodejs.org/job/node-test-pull-request/68774/), [https://github.com/nodejs/node/pull/59567/](https://ci.nodejs.org/job/node-test-pull-request/68781/), [https://github.com/nodejs/node/pull/59558/](https://ci.nodejs.org/job/node-test-pull-request/68798/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20010/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60006/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59996/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68746/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68798/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20010/console">Example</a></summary>

```
not ok 3146 parallel/test-runner-mock-timers-scheduler
  ---
  duration_ms: 5583.36300
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should advance in time and trigger timers when calling the .tick function'
    Location: test/parallel/test-runner-mock-timers-scheduler.js:10:3
    AssertionError [ERR_ASSERTION]: time should be advanced less than the 100ms
        at /home/iojs/build/workspace/node-test-commit-arm-debug/test/parallel/test-runner-mock-timers-scheduler.js:21:14
        at /home/iojs/build/workspace/node-test-commit-arm-debug/test/common/index.js:468:15
        at async Test.run (node:internal/test_runner/test:1113:7)
        at async Promise.all (index 0)
        at async Suite.run (node:internal/test_runner/test:1516:7)
        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:358:3) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '==',
      diff: 'simple'
    }
    
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-keep-alive-empty-line</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/59350/](https://ci.nodejs.org/job/node-test-pull-request/68767/), [https://github.com/nodejs/node/pull/59550/](https://ci.nodejs.org/job/node-test-pull-request/68771/), [https://github.com/nodejs/node/pull/59464/](https://ci.nodejs.org/job/node-test-pull-request/68774/), [https://github.com/nodejs/node/pull/59527/](https://ci.nodejs.org/job/node-test-pull-request/68779/), [https://github.com/nodejs/node/pull/59570/](https://ci.nodejs.org/job/node-test-pull-request/68790/), [https://github.com/nodejs/node/pull/59558/](https://ci.nodejs.org/job/node-test-pull-request/68798/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20010/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/60027/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60019/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68767/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68798/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20010/console">Example</a></summary>

```
not ok 1876 parallel/test-http-keep-alive-empty-line
  ---
  duration_ms: 3582.76000
  severity: fail
  exitcode: 1
  stack: |-
    node:events:486
          throw er; // Unhandled 'error' event
          ^
    
    Error [ERR_STREAM_WRITE_AFTER_END]: write after end
        at _write (node:internal/streams/writable:487:11)
        at Writable.write (node:internal/streams/writable:508:10)
        at Timeout._onTimeout (file:///home/iojs/build/workspace/node-test-commit-arm-debug/test/parallel/test-http-keep-alive-empty-line.mjs:32:14)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7)
    Emitted 'error' event on Socket instance at:
        at emitErrorNT (node:internal/streams/destroy:170:8)
        at emitErrorCloseNT (node:internal/streams/destroy:129:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
      code: 'ERR_STREAM_WRITE_AFTER_END'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-outgoing-end-cork</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/59538/](https://ci.nodejs.org/job/node-test-pull-request/68741/), [https://github.com/nodejs/node/pull/59491/](https://ci.nodejs.org/job/node-test-pull-request/68754/), [https://github.com/nodejs/node/pull/59455/](https://ci.nodejs.org/job/node-test-pull-request/68759/), [https://github.com/nodejs/node/pull/59464/](https://ci.nodejs.org/job/node-test-pull-request/68774/), [https://github.com/nodejs/node/pull/59558/](https://ci.nodejs.org/job/node-test-pull-request/68798/), [https://github.com/nodejs/node/pull/59579/](https://ci.nodejs.org/job/node-test-pull-request/68820/)) |
| Appeared | [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/60053/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60053/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20010/console), [test-equinix-ubuntu2204_container-arm64-8](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19966/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68741/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68820/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/60053/console">Example</a></summary>

```
not ok 1907 parallel/test-http-outgoing-end-cork
  ---
  duration_ms: 1749.51600
  severity: fail
  exitcode: 1
  stack: |-
    Sending req no 1
    node:assert:177
      throw err;
      ^
    
    AssertionError [ERR_ASSERTION]: () => {
        reject(new Error('Request timed out'));
      } at /home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-http-outgoing-end-cork.js:53
        at Timeout.mustNotCall [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-arm/test/common/index.js:530:12)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: undefined,
      operator: 'fail',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-rangeerror</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68818/), [https://github.com/nodejs/node/pull/58797/](https://ci.nodejs.org/job/node-test-pull-request/68822/), [https://github.com/nodejs/node/pull/59579/](https://ci.nodejs.org/job/node-test-pull-request/68824/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2019/36441/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68818/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68824/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2019/36441/console">Example</a></summary>

```
not ok 108 parallel/test-buffer-tostring-rangeerror
  ---
  duration_ms: 427.99800
  severity: fail
  exitcode: 134
  stack: |-
    
    <--- Last few GCs --->
    
    [4128:0000017395310080]      144 ms: Mark-Compact (reduce) 3.4 (6.0) -> 3.4 (5.0) MB, 14.07 / 0.00 ms  (average mu = 0.105, current mu = 0.053) external memory pressure; GC in old space requested
    [4128:0000017395310080]      148 ms: Mark-Compact (reduce) 3.4 (5.0) -> 3.4 (5.0) MB, 4.40 / 0.00 ms  (average mu = 0.075, current mu = 0.008) external memory pressure; GC in old space requested
    
    
    <--- JS stacktrace --->
    
    FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
    ----- Native stack trace -----
    
     1: 00007FF62E62B66B 
     2: 00007FF62E59A748 
     3: 00007FF62F014571 
     4: 00007FF62EFFDCC8 
     5: 00007FF62EE5F6A0 
     6: 00007FF62EE174A3 
     7: 00007FF62EE68D50 
     8: 00007FF62EE5C3C0 
     9: 00007FF62EE59F13 
    10: 00007FF62ED5BDF2 
    11: 00007FF62EFC...
```
</details>

-------

| Reason | <code>parallel/test-buffer-zero-fill-reset</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68818/), [https://github.com/nodejs/node/pull/58797/](https://ci.nodejs.org/job/node-test-pull-request/68822/), [https://github.com/nodejs/node/pull/59579/](https://ci.nodejs.org/job/node-test-pull-request/68824/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2019/36441/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68818/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68824/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2019/36441/console">Example</a></summary>

```
not ok 107 parallel/test-buffer-zero-fill-reset
  ---
  duration_ms: 345.00500
  severity: fail
  exitcode: 134
  stack: |-
    
    <--- Last few GCs --->
    
    
    <--- JS stacktrace --->
    
    FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
    ----- Native stack trace -----
    
     1: 00007FF62E62B66B 
     2: 00007FF62E59A748 
     3: 00007FF62F014571 
     4: 00007FF62EFFDCC8 
     5: 00007FF62EE5F6A0 
     6: 00007FF62EE174A3 
     7: 00007FF62EE68D50 
     8: 00007FF62EE5C3C0 
     9: 00007FF62EE71A2A 
    10: 00007FF62EE722A7 
    11: 00007FF62EE80B9F 
    12: 00007FF62EB41285 
    13: 00007FF62F0BF49E 
    14: 00007FF62F0E0DE7 
    15: 00007FF62F0DF70A 
    16: 00007FF62F0FF411 
    17: 00007FF5AF20E533 
  ...

```
</details>

-------

| Reason | <code>parallel/test-child-process-advanced-serialization-splitted-length-field</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68818/), [https://github.com/nodejs/node/pull/58797/](https://ci.nodejs.org/job/node-test-pull-request/68822/), [https://github.com/nodejs/node/pull/59579/](https://ci.nodejs.org/job/node-test-pull-request/68824/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2019/36441/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68818/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68824/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2019/36441/console">Example</a></summary>

```
not ok 106 parallel/test-child-process-advanced-serialization-splitted-length-field
  ---
  duration_ms: 273.03700
  severity: fail
  exitcode: 134
  stack: |-
    
    <--- Last few GCs --->
    
    
    <--- JS stacktrace --->
    
    FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
    ----- Native stack trace -----
    
     1: 00007FF62E62B66B 
     2: 00007FF62E59A748 
     3: 00007FF62F014571 
     4: 00007FF62EFFDCC8 
     5: 00007FF62EE5F6A0 
     6: 00007FF62EE174A3 
     7: 00007FF62EE68D50 
     8: 00007FF62EE5C3C0 
     9: 00007FF62EE5C84C 
    10: 00007FF62EE4DD91 
    11: 00007FF62EE4EB77 
    12: 00007FF62EE8D503 
    13: 00007FF62EFCE7DB 
    14: 00007FF62EFCE019 
    15: 00007FF62EF6A292 
    16: 00007FF62EF696AE 
    17: 00007FF62EFD8858 
    18: 00007FF62EEB4CD4 
    19: 00007FF62EB40DA9 
    20: 00007FF62EB415E9 
    21: 00007FF62F0BF49E 
    22: 00007FF62F19B3DA 
    23: 00007FF62F030A40 
    24: 00007FF62F030A40 
    25: 00007FF62F030A40 
  ...
```
</details>

-------

| Reason | <code>parallel/test-fs-write-stream-eagain</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58797/](https://ci.nodejs.org/job/node-test-pull-request/68833/), [https://github.com/nodejs/node/pull/59595/](https://ci.nodejs.org/job/node-test-pull-request/68838/), [https://github.com/nodejs/node/pull/58155/](https://ci.nodejs.org/job/node-test-pull-request/68839/)) |
| Appeared | [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2019-x86/36453/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68833/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68839/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2019-x86/36453/console">Example</a></summary>

```
not ok 332 parallel/test-fs-write-stream-eagain
  ---
  duration_ms: 224.00300
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: WriteStream EAGAIN
        # Subtest: _write
        not ok 1 - _write
          ---
          duration_ms: 14.6056
          location: 'C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\parallel\\test-fs-write-stream-eagain.mjs:15:3'
          failureType: 'testCodeFailure'
          error: |-
            Expected values to be strictly equal:
            
            '' !== 'foo'
            
          code: 'ERR_ASSERTION'
          name: 'AssertionError'
          expected: 'foo'
          actual: ''
          operator: 'strictEqual'
          stack: |-
            TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-fs-write-stream-eagain.mjs:30:12)
            process.processTicksAndRejections (node:internal/process/task_queues:95:5)
            async Test.run (node:internal/test_runner/...
```
</details>

-------

| Reason | <code>parallel/test-http2-close-while-writing</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59547/](https://ci.nodejs.org/job/node-test-pull-request/68780/), [https://github.com/nodejs/node/pull/59569/](https://ci.nodejs.org/job/node-test-pull-request/68791/), [https://github.com/nodejs/node/pull/59529/](https://ci.nodejs.org/job/node-test-pull-request/68823/)) |
| Appeared | [vm-e0fsz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66419/console), [vm-znf61](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66405/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/52398/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68780/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68823/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66419/console">Example</a></summary>

```
not ok 2799 parallel/test-http2-close-while-writing
  ---
  duration_ms: 120012.46000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59527/](https://ci.nodejs.org/job/node-test-pull-request/68779/), [https://github.com/nodejs/node/pull/59547/](https://ci.nodejs.org/job/node-test-pull-request/68780/), [https://github.com/nodejs/node/pull/59567/](https://ci.nodejs.org/job/node-test-pull-request/68781/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52400/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52398/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52397/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68779/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68781/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52400/console">Example</a></summary>

```
not ok 3877 parallel/test-without-async-context-frame
  ---
  duration_ms: 120034.98300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59538/](https://ci.nodejs.org/job/node-test-pull-request/68747/), [https://github.com/nodejs/node/pull/59504/](https://ci.nodejs.org/job/node-test-pull-request/68763/), [https://github.com/nodejs/node/pull/59350/](https://ci.nodejs.org/job/node-test-pull-request/68776/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51170/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/51158/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51148/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68747/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68776/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51170/console">Example</a></summary>

```
not ok 4716 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 14720.67400
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:273
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linuxone/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '==',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-debugger-break</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59504/](https://ci.nodejs.org/job/node-test-pull-request/68745/), [https://github.com/nodejs/node/pull/59595/](https://ci.nodejs.org/job/node-test-pull-request/68836/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/36464/console), [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18488/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68745/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68836/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/36464/console">Example</a></summary>

```
not ok 230 parallel/test-debugger-break
  ---
  duration_ms: 446.00700
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/process/promises:332
        triggerUncaughtException(err, true /* fromPromise */);
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert.ok(cli.output.includes(`#1 ${script}:16`))
    
        at c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-debugger-break.js:64:10
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '==',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-debugger-breakpoint-exists</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59570/](https://ci.nodejs.org/job/node-test-pull-request/68790/), [https://github.com/nodejs/node/pull/59569/](https://ci.nodejs.org/job/node-test-pull-request/68791/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60028/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/60027/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68790/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68791/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60028/console">Example</a></summary>

```
not ok 974 parallel/test-debugger-breakpoint-exists
  ---
  duration_ms: 17551.16600
  severity: fail
  exitcode: 1
  stack: |-
    /home/iojs/build/workspace/node-test-commit-arm/test/common/debugger.js:95
              reject(new Error([
                     ^
    
    Error: Timeout (10000) while waiting for /break (?:on start )?in/i; found: < Debugger listening on ws://127.0.0.1:46183/8a4a8d73-b224-42d1-8ac5-f6c84213f80b
    < For help, see: https://nodejs.org/en/docs/inspector
    < 
    
    connecting to 127.0.0.1:46183 ...
     ok
    
    
    < Debugger attached.
    < 
    
        at Timeout.<anonymous> (/home/iojs/build/workspace/node-test-commit-arm/test/common/debugger.js:95:18)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7)
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-preview</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59570/](https://ci.nodejs.org/job/node-test-pull-request/68790/), [https://github.com/nodejs/node/pull/59569/](https://ci.nodejs.org/job/node-test-pull-request/68791/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60028/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/60027/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68790/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68791/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60028/console">Example</a></summary>

```
not ok 3059 parallel/test-repl-preview
  ---
  duration_ms: 4424.29500
  severity: fail
  exitcode: 1
  stack: |-
    Testing foo
    Testing foo
    Testing foo
    Testing foo
    Testing foo
    Testing koo
    Testing koo
    Testing koo
    Testing a
    Testing a
    Testing a
    Testing  { b: 1 }['b'] === 1
    Testing  { b: 1 }['b'] === 1
    Testing  { b: 1 }['b'] === 1
    Testing { b: 1 }['b'] === 1;
    Testing { b: 1 }['b'] === 1;
    Testing { b: 1 }['b'] === 1;
    Testing koo
    Testing koo
    Testing { a: true }
    Testing { a: true }
    Testing { a: true }
    Testing { a: true };
    Testing { a: true };
    Testing { a: true };
    Testing  	 { a: true};
    Testing  	 { a: true};
    Testing  	 { a: true};
    Testing 1n + 2n
    Testing 1n + 2n
    Testing 1n + 2n
    Testing {};1
    Testing {};1
    Testing {};1
    Testing a
    Testing a
    Testing  { b: 1 }['b'] === 1
    Testing  { b: 1 }['b'] === 1
    Testing { b: 1 }['b'] === 1;
    Testing { a: true }
    Testing { a: tru...
```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59547/](https://ci.nodejs.org/job/node-test-pull-request/68780/), [https://github.com/nodejs/node/pull/59527/](https://ci.nodejs.org/job/node-test-pull-request/68793/)) |
| Appeared | [test-osuosl-ubuntu2204_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60030/console), [vm-cdv4h](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66397/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68780/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68793/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60030/console">Example</a></summary>

```
not ok 2876 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 2114.22400
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'can be overridden (to SIGINT)'
    Location: test/parallel/test-runner-watch-mode-kill-signal.mjs:72:3
    AssertionError [ERR_ASSERTION]: The input was expected to not match the regular expression /__SIGTERM received__/. Input:
    
    "Restarting '/home/iojs/node-tmp/.tmp.2876/index.js'\n" +
      '__SIGINT received__\n' +
      "Restarting '/home/iojs/node-tmp/.tmp.2876/index.js'\n" +
      '__SIGINT received__\n' +
      '__SIGTERM received__\n'
    
        at TestContext.<anonymous> (file:///home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-runner-watch-mode-kill-signal.mjs:103:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Test.run (node:internal/test_runner/test:1113:7)
        at async Suite.processPendingSubtests (node:internal/test_runner/test:788:7) {
      generatedMessage...
```
</details>

-------

| Reason | <code>wpt/test-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58989/](https://ci.nodejs.org/job/node-test-pull-request/68787/), [https://github.com/nodejs/node/pull/59571/](https://ci.nodejs.org/job/node-test-pull-request/68807/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58710/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68787/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68807/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58710/console">Example</a></summary>

```
not ok 4780 wpt/test-streams
  ---
  duration_ms: 1555.74100
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] queuing-strategies-size-function-per-global.window.js: Browser-specific test
    [SKIPPED] readable-streams/cross-realm-crash.window.js: Browser-specific test
    [SKIPPED] readable-streams/owning-type-video-frame.any.js: Browser-specific test
    [SKIPPED] readable-streams/read-task-handling.window.js: Browser-specific test
    [SKIPPED] transferable/deserialize-error.window.js: Browser-specific test
    [SKIPPED] transferable/transfer-with-messageport.window.js: Browser-specific test
    [SKIPPED] transform-streams/invalid-realm.tentative.window.js: Browser-specific test
    [EXPECTED_FAILURE][FAIL] enqueue() must not synchronously call write algorithm
    assert_false: write algorithm must not run synchronously expected false got true
        at Test.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/fixtures/wpt/streams/piping/general-addition.any.js:14...
```
</details>

-------


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59503/](https://ci.nodejs.org/job/node-test-pull-request/68750/), [https://github.com/nodejs/node/pull/59544/](https://ci.nodejs.org/job/node-test-pull-request/68756/), [https://github.com/nodejs/node/pull/59571/](https://ci.nodejs.org/job/node-test-pull-request/68807/), [https://github.com/nodejs/node/pull/59527/](https://ci.nodejs.org/job/node-test-pull-request/68817/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68818/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36440/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68750/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68818/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36440/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 1572969, exit value: 1</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68795/), [https://github.com/nodejs/node/pull/59558/](https://ci.nodejs.org/job/node-test-pull-request/68798/)) |
| Appeared | [test-rackspace-debian11-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/66250/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68795/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68798/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/66250/console">Example</a></summary>

```
java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 1572969, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at Jenkins v2.516.1//hudson.Proc$LocalProc.<init>(Proc.java:252)
	at Jenkins v2.516.1//hudson.Proc$LocalProc.<init>(Proc.java:221)
	at Jenkins v2.516.1//hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
```
</details>

-------

| Reason | <code>Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 1574737, exit value: 1</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68801/), [https://github.com/nodejs/node/pull/59571/](https://ci.nodejs.org/job/node-test-pull-request/68807/)) |
| Appeared | [test-rackspace-debian11-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/66254/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68801/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68807/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/66254/console">Example</a></summary>

```
java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 1574737, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at Jenkins v2.516.1//hudson.Proc$LocalProc.<init>(Proc.java:252)
	at Jenkins v2.516.1//hudson.Proc$LocalProc.<init>(Proc.java:221)
	at Jenkins v2.516.1//hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
```
</details>

-------


### Git Failure


### Build Failure

| Reason | <code>ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59527/](https://ci.nodejs.org/job/node-test-pull-request/68779/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68782/), [https://github.com/nodejs/node/pull/59595/](https://ci.nodejs.org/job/node-test-pull-request/68837/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20043/console), [test-equinix-debian11_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18515/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18515/console), [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=debian11-armv7l/18515/console), [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/18515/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/60018/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68779/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68837/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20043/console">Example</a></summary>

```
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>fatal error: ld terminated with signal 9 [Killed]</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58169/](https://ci.nodejs.org/job/node-test-pull-request/68825/), [https://github.com/nodejs/node/pull/59539/](https://ci.nodejs.org/job/node-test-pull-request/68832/), [https://github.com/nodejs/node/pull/59595/](https://ci.nodejs.org/job/node-test-pull-request/68837/)) |
| Appeared | [test-azure-ubuntu2204_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=test-azure-ubuntu2204_container-arm64-1/20032/console), [test-azure-ubuntu2204_container-arm64-3](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20038/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68825/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68837/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=test-azure-ubuntu2204_container-arm64-1/20032/console">Example</a></summary>

```
fatal error: ld terminated with signal 9 [Killed]
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59538/](https://ci.nodejs.org/job/node-test-pull-request/68741/), [https://github.com/nodejs/node/pull/59527/](https://ci.nodejs.org/job/node-test-pull-request/68799/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52411/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52368/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68741/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68799/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52411/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

