Failures in [node-test-pull-request/66597](https://ci.nodejs.org/job/node-test-pull-request/66597/) to [node-test-pull-request/66696](https://ci.nodejs.org/job/node-test-pull-request/66696/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-05-08.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-05-08 00:11 | 0       | 9       | 17       | 2       | 72      | 9.18%      |


### Jenkins Failure

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 16 ([https://github.com/nodejs/node/pull/58151/](https://ci.nodejs.org/job/node-test-pull-request/66598/), [https://github.com/nodejs/node/pull/58171/](https://ci.nodejs.org/job/node-test-pull-request/66600/), [https://github.com/nodejs/node/pull/58143/](https://ci.nodejs.org/job/node-test-pull-request/66618/), [https://github.com/nodejs/node/pull/58103/](https://ci.nodejs.org/job/node-test-pull-request/66621/), [https://github.com/nodejs/node/pull/58183/](https://ci.nodejs.org/job/node-test-pull-request/66623/), [https://github.com/nodejs/node/pull/58181/](https://ci.nodejs.org/job/node-test-pull-request/66638/), [https://github.com/nodejs/node/pull/58163/](https://ci.nodejs.org/job/node-test-pull-request/66639/), [https://github.com/nodejs/node/pull/58190/](https://ci.nodejs.org/job/node-test-pull-request/66645/), [https://github.com/nodejs/node/pull/58144/](https://ci.nodejs.org/job/node-test-pull-request/66646/), [https://github.com/nodejs/node/pull/57643/](https://ci.nodejs.org/job/node-test-pull-request/66654/), [https://github.com/nodejs/node/pull/58122/](https://ci.nodejs.org/job/node-test-pull-request/66656/), [https://github.com/nodejs/node/pull/58200/](https://ci.nodejs.org/job/node-test-pull-request/66662/), [https://github.com/nodejs/node/pull/58209/](https://ci.nodejs.org/job/node-test-pull-request/66668/), [https://github.com/nodejs/node/pull/58211/](https://ci.nodejs.org/job/node-test-pull-request/66683/), [https://github.com/nodejs/node/pull/58182/](https://ci.nodejs.org/job/node-test-pull-request/66684/), [https://github.com/nodejs/node/pull/56534/](https://ci.nodejs.org/job/node-test-pull-request/66686/)) |
| Appeared | [vm-zs9lr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64976/console), [vm-6fxpx](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64974/console), [vm-k6rxd](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64967/console), [vm-xxmkg](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64964/console), [vm-zvdmf](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64956/console), [vm-k24dw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64953/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/50507/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/50507/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50506/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/50506/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/50506/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/50506/console), [vm-g7z6n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64943/console), [vm-d54f5](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64937/console), [vm-nm7dc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64918/console), [vm-zgnbb](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64917/console), [vm-lkh4k](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64916/console), [vm-4dn6g](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64895/console), [vm-fd526](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64894/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66598/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66686/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64976/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 12 ([https://github.com/nodejs/node/pull/58122/](https://ci.nodejs.org/job/node-test-pull-request/66622/), [https://github.com/nodejs/node/pull/58183/](https://ci.nodejs.org/job/node-test-pull-request/66625/), [https://github.com/nodejs/node/pull/58141/](https://ci.nodejs.org/job/node-test-pull-request/66627/), [https://github.com/nodejs/node/pull/58143/](https://ci.nodejs.org/job/node-test-pull-request/66634/), [https://github.com/nodejs/node/pull/58184/](https://ci.nodejs.org/job/node-test-pull-request/66635/), [https://github.com/nodejs/node/pull/58151/](https://ci.nodejs.org/job/node-test-pull-request/66647/), [https://github.com/nodejs/node/pull/58074/](https://ci.nodejs.org/job/node-test-pull-request/66660/), [https://github.com/nodejs/node/pull/58147/](https://ci.nodejs.org/job/node-test-pull-request/66663/), [https://github.com/nodejs/node/pull/57643/](https://ci.nodejs.org/job/node-test-pull-request/66675/), [https://github.com/nodejs/node/pull/57954/](https://ci.nodejs.org/job/node-test-pull-request/66681/), [https://github.com/nodejs/node/pull/57931/](https://ci.nodejs.org/job/node-test-pull-request/66687/), [https://github.com/nodejs/node/pull/56534/](https://ci.nodejs.org/job/node-test-pull-request/66695/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/34057/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022_clang/34050/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022_clang/34040/console), [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022_clang/34040/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66622/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66695/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/34057/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58182/](https://ci.nodejs.org/job/node-test-pull-request/66664/), [https://github.com/nodejs/node/pull/58211/](https://ci.nodejs.org/job/node-test-pull-request/66683/)) |
| Appeared | [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/64527/console), [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/64515/console), [test-osuosl-rhel9-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/58885/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66664/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66683/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/64527/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1240)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1278)
```
</details>

-------


### Build Failure

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56534/](https://ci.nodejs.org/job/node-test-pull-request/66630/), [https://github.com/nodejs/node/pull/58190/](https://ci.nodejs.org/job/node-test-pull-request/66653/), [https://github.com/nodejs/node/pull/58124/](https://ci.nodejs.org/job/node-test-pull-request/66692/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-pull-request/66692/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66630/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66692/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/66692/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

-------

| Reason | <code>fatal error: Killed signal terminated program cc1plus</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/57643/](https://ci.nodejs.org/job/node-test-pull-request/66654/), [https://github.com/nodejs/node/pull/58074/](https://ci.nodejs.org/job/node-test-pull-request/66660/), [https://github.com/nodejs/node/pull/58064/](https://ci.nodejs.org/job/node-test-pull-request/66685/)) |
| Appeared | [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50530/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/42085/console), [test-rackspace-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/64508/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/50506/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/50506/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66654/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66685/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50530/console">Example</a></summary>

```
fatal error: Killed signal terminated program cc1plus
```
</details>

-------


### JSTest Failure

| Reason | <code>parallel/test-cluster-fork-stdio</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/58151/](https://ci.nodejs.org/job/node-test-pull-request/66647/), [https://github.com/nodejs/node/pull/58074/](https://ci.nodejs.org/job/node-test-pull-request/66660/), [https://github.com/nodejs/node/pull/58147/](https://ci.nodejs.org/job/node-test-pull-request/66663/), [https://github.com/nodejs/node/pull/57643/](https://ci.nodejs.org/job/node-test-pull-request/66675/), [https://github.com/nodejs/node/pull/57954/](https://ci.nodejs.org/job/node-test-pull-request/66681/), [https://github.com/nodejs/node/pull/57931/](https://ci.nodejs.org/job/node-test-pull-request/66687/), [https://github.com/nodejs/node/pull/56534/](https://ci.nodejs.org/job/node-test-pull-request/66695/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/34057/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66647/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66695/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/34057/console">Example</a></summary>

```
not ok 1022 parallel/test-cluster-fork-stdio
  ---
  duration_ms: 120138.96800
  severity: fail
  exitcode: 1
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-rangeerror</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/58151/](https://ci.nodejs.org/job/node-test-pull-request/66647/), [https://github.com/nodejs/node/pull/58074/](https://ci.nodejs.org/job/node-test-pull-request/66660/), [https://github.com/nodejs/node/pull/58147/](https://ci.nodejs.org/job/node-test-pull-request/66663/), [https://github.com/nodejs/node/pull/57954/](https://ci.nodejs.org/job/node-test-pull-request/66681/), [https://github.com/nodejs/node/pull/57931/](https://ci.nodejs.org/job/node-test-pull-request/66687/), [https://github.com/nodejs/node/pull/56534/](https://ci.nodejs.org/job/node-test-pull-request/66695/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/34091/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66647/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66695/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/34091/console">Example</a></summary>

```
not ok 105 parallel/test-buffer-tostring-rangeerror
  ---
  duration_ms: 433.02600
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:377
          throw err;
          ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
      Comparison {
    +   name: 'RangeError'
    -   code: 'ERR_STRING_TOO_LONG',
    -   name: 'Error'
      }
        at Object.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-buffer-tostring-rangeerror.js:21:8)
        at Module._compile (node:internal/modules/cjs/loader:1529:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
        at Module.load (node:internal/modules/cjs/loader:1275:32)
        at Module._load (node:internal/modules/cjs/loader:1096:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
        at node:internal/main/run_main_module:28:49 {
      generatedMessage: true,
      code: 'ERR_ASSE...
```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58173/](https://ci.nodejs.org/job/node-test-pull-request/66624/), [https://github.com/nodejs/node/pull/58124/](https://ci.nodejs.org/job/node-test-pull-request/66641/), [https://github.com/nodejs/node/pull/58211/](https://ci.nodejs.org/job/node-test-pull-request/66672/), [https://github.com/nodejs/node/pull/58206/](https://ci.nodejs.org/job/node-test-pull-request/66673/), [https://github.com/nodejs/node/pull/58064/](https://ci.nodejs.org/job/node-test-pull-request/66685/)) |
| Appeared | [vm-2kr49](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64975/console), [vm-gmdc7](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64963/console), [vm-g7z6n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64939/console), [vm-nm7dc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64920/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66624/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66685/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64975/console">Example</a></summary>

```
not ok 2618 parallel/test-runner-run-watch
  ---
  duration_ms: 29942.43000
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should support running tests without a file'
    Location: test/parallel/test-runner-run-watch.mjs:210:3
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 1/. Input:
    
    '# Subtest: test.js\n' +
      'not ok 2 - test.js\n' +
      '  ---\n' +
      '  duration_ms: 947.822224\n' +
      "  type: 'test'\n" +
      "  location: '/Users/admin/node-tmp/.tmp.2576/test.js:1:1'\n" +
      "  failureType: 'testCodeFailure'\n" +
      '  exitCode: ~\n' +
      "  signal: 'SIGTERM'\n" +
      "  error: 'test failed'\n" +
      "  code: 'ERR_TEST_FAILURE'\n" +
      '  ...\n' +
      '# Subtest: test has ran\n' +
      'ok 2 - test has ran\n' +
      '  ---\n' +
      '  duration_ms: 3.735953\n' +
      "  type: 'test'\n" +
      '  ...\n' +
      '1..2\n' +
      '# tests 2\n' +
      '# suites 0\n' +
      '# pass 1\n' +
      '# fail 1\n...
```
</details>

-------

| Reason | <code>pummel/test-heapdump-zlib</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58143/](https://ci.nodejs.org/job/node-test-pull-request/66626/), [https://github.com/nodejs/node/pull/58141/](https://ci.nodejs.org/job/node-test-pull-request/66627/), [https://github.com/nodejs/node/pull/58147/](https://ci.nodejs.org/job/node-test-pull-request/66663/), [https://github.com/nodejs/node/pull/57931/](https://ci.nodejs.org/job/node-test-pull-request/66687/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022_clang/34098/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022_clang/34076/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/34040/console), [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022_clang/34039/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66626/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66687/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022_clang/34098/console">Example</a></summary>

```
not ok 1019 pummel/test-heapdump-zlib
  ---
  duration_ms: 720230.07000
  severity: fail
  exitcode: 1
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-http2-client-socket-destroy</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58173/](https://ci.nodejs.org/job/node-test-pull-request/66624/), [https://github.com/nodejs/node/pull/58183/](https://ci.nodejs.org/job/node-test-pull-request/66629/), [https://github.com/nodejs/node/pull/56534/](https://ci.nodejs.org/job/node-test-pull-request/66631/)) |
| Appeared | [vm-nm7dc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64927/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66624/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66631/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64927/console">Example</a></summary>

```
not ok 1552 parallel/test-http2-client-socket-destroy
  ---
  duration_ms: 202.50200
  severity: fail
  exitcode: 1
  stack: |-
    node:events:485
          throw er; // Unhandled 'error' event
          ^
    
    Error: read ECONNRESET
        at TCP.onStreamRead (node:internal/stream_base_commons:216:20)
    Emitted 'error' event on ServerHttp2Stream instance at:
        at emitErrorNT (node:internal/streams/destroy:170:8)
        at emitErrorCloseNT (node:internal/streams/destroy:129:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
      errno: -54,
      code: 'ECONNRESET',
      syscall: 'read'
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-http2-close-while-writing</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/57643/](https://ci.nodejs.org/job/node-test-pull-request/66606/), [https://github.com/nodejs/node/pull/58173/](https://ci.nodejs.org/job/node-test-pull-request/66624/), [https://github.com/nodejs/node/pull/58183/](https://ci.nodejs.org/job/node-test-pull-request/66625/)) |
| Appeared | [vm-nm7dc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64921/console), [vm-5cpq7](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64902/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66606/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66625/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64921/console">Example</a></summary>

```
not ok 2533 parallel/test-http2-close-while-writing
  ---
  duration_ms: 120074.07300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58174/](https://ci.nodejs.org/job/node-test-pull-request/66605/), [https://github.com/nodejs/node/pull/58206/](https://ci.nodejs.org/job/node-test-pull-request/66673/), [https://github.com/nodejs/node/pull/58212/](https://ci.nodejs.org/job/node-test-pull-request/66680/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/50527/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/50521/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/50459/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66605/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66680/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/50527/console">Example</a></summary>

```
not ok 4484 sequential/test-tls-session-timeout
  ---
  duration_ms: 450.52200
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:94
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at /home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:150:16
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:134:7)
        at ChildProcess.emit (node:events:507:28)
        at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-autoselectfamily</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58193/](https://ci.nodejs.org/job/node-test-pull-request/66649/), [https://github.com/nodejs/node/pull/57576/](https://ci.nodejs.org/job/node-test-pull-request/66688/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/50533/console), [test-osuosl-rhel9-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/58880/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66649/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66688/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/50533/console">Example</a></summary>

```
not ok 2102 parallel/test-net-autoselectfamily
  ---
  duration_ms: 5234.51200
  severity: fail
  exitcode: 1
  stack: |-
    Mismatched <anonymous> function calls. Expected exactly 1, actual 0.
        at Proxy.mustCall (/home/iojs/build/workspace/node-test-commit-linux-containered/test/common/index.js:393:10)
        at Server.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/parallel/test-net-autoselectfamily.js:60:30)
        at Server.emit (node:events:507:28)
        at TCP.onconnection (node:net:2301:8)
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-listen-ipv6only</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58193/](https://ci.nodejs.org/job/node-test-pull-request/66649/), [https://github.com/nodejs/node/pull/57576/](https://ci.nodejs.org/job/node-test-pull-request/66688/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/50533/console), [test-osuosl-rhel9-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/58880/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66649/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66688/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/50533/console">Example</a></summary>

```
not ok 2070 parallel/test-net-listen-ipv6only
  ---
  duration_ms: 140.33700
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:141
      throw err;
      ^
    
    AssertionError [ERR_ASSERTION]: function should not have been called at /home/iojs/build/workspace/node-test-commit-linux-containered/test/parallel/test-net-listen-ipv6only.js:25
        at Socket.mustNotCall (/home/iojs/build/workspace/node-test-commit-linux-containered/test/common/index.js:493:12)
        at Socket.emit (node:events:507:28)
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1621:10) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: undefined,
      operator: 'fail'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>pummel/test-timers</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58124/](https://ci.nodejs.org/job/node-test-pull-request/66641/), [https://github.com/nodejs/node/pull/57643/](https://ci.nodejs.org/job/node-test-pull-request/66696/)) |
| Appeared | [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50538/console), [test-ibm-rhel8-s390x-3](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/49325/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66641/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66696/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50538/console">Example</a></summary>

```
not ok 4109 pummel/test-timers
  ---
  duration_ms: 5027.51900
  severity: fail
  exitcode: 1
  stack: |-
    diff: 1002
    diff: 1002
    diff: 2003
    diff: 4760
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert.ok(Math.abs(diff - t) < WINDOW * interval_count)
    
        at Timeout.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/pummel/test-timers.js:64:12)
        at Timeout._onTimeout (/home/iojs/build/workspace/node-test-commit-linux-containered/test/common/index.js:437:15)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58182/](https://ci.nodejs.org/job/node-test-pull-request/66684/), [https://github.com/nodejs/node/pull/57576/](https://ci.nodejs.org/job/node-test-pull-request/66688/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/49352/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66684/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66688/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/49352/console">Example</a></summary>

```
not ok 4427 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 14728.96000
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linuxone/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

